// GENERATED by scripts/design-tavern-interior.mjs — edit the generator, not this file.
// The Tavern Interior: 12 m × 8 m cutaway, two walls + bar, roof off, camera looks in.
// Built from the 25-asset tavern kit per docs/tavern-mockups/components.tsv and
// docs/tavern-mockups/construction.md.
//
// Grid: 6 × 4 tiles of 2 m. col 1..6 west->east, row 1..4 north->south.
// Cell (c,r) center: x = (c-3.5)*2, z = (r-2.5)*2. +X east, -Z north.
import type { Place } from './chibi-quest.js';

export function tavernInteriorPlaces(): Place[] {
  const X = (c: number) => (c - 3.5) * 2;
  const Z = (r: number) => (r - 2.5) * 2;
  const places: Place[] = [];
  const put = (asset: string, x: number, z: number, y: number, opts: { yaw?: number; scale?: number } = {}) => {
    const p: Place = { asset, at: [x, y, z] };
    if (opts.yaw !== undefined) p.yaw = opts.yaw;
    if (opts.scale !== undefined) p.scale = opts.scale;
    places.push(p);
  };

  // --- floor: 6x4 wood-floor tiles
  for (let c = 1; c <= 6; c++) for (let r = 1; r <= 4; r++) put('wood-floor', X(c), Z(r), 0);

  // --- back wall (north row r=1): 3 plaster-wall tiles across c=1..3
  for (let c = 1; c <= 3; c++) put('plaster-wall', X(c), Z(1), 0, { yaw: 90 });
  // --- right wall (east col c=6): 2 plaster-wall tiles along r=2..3
  for (let r = 2; r <= 3; r++) put('plaster-wall', X(6), Z(r), 0, { yaw: 180 });
  // --- doorway on back wall: replace middle wall with wall-door
  put('plaster-wall-door', X(2), Z(1), 0, { yaw: 90 });
  // --- window on right wall: replace middle with wall-window
  put('plaster-wall-window', X(6), Z(2.5), 0, { yaw: 180 });

  // --- focal: stone fireplace on the south wall (camera-facing), centered
  put('fireplace', X(3), Z(4) + 0.4, 0);

  // --- bar: counter along the back (south of doorway), with shelves behind it on the wall
  put('counter', X(2), Z(3.4), 0, { yaw: 0 });
  put('shelf', X(3.6), Z(0.6), 0, { yaw: 90 });
  put('shelf', X(3.6), Z(1.6), 0, { yaw: 90 });
  // bottles on the shelf
  put('bottle', X(3.6) + 0.18, Z(0.6) + 0.2, 0, { scale: 0.85 });
  put('bottle', X(3.6) + 0.05, Z(0.6) + 0.1, 0, { scale: 0.85 });
  put('bottle', X(3.6) - 0.08, Z(0.6) + 0.2, 0, { scale: 0.85 });

  // --- feast table (south-center) with benches flanking
  put('table', X(2.6), Z(2.4), 0, { yaw: 0 });
  put('bench', X(2.6) + 0.4, Z(2.4) + 0.7, 0, { yaw: 90 });
  put('bench', X(2.6) + 0.4, Z(2.4) - 0.7, 0, { yaw: -90 });
  // --- feast dishes on the table
  put('plate', X(2.6) - 0.25, Z(2.4) + 0.15, 0, { scale: 0.9 });
  put('plate', X(2.6) + 0.25, Z(2.4) + 0.15, 0, { scale: 0.9 });
  put('plate', X(2.6), Z(2.4) - 0.15, 0, { scale: 0.9 });
  put('bread', X(2.6), Z(2.4), 0, { scale: 1.0 });
  put('cheese', X(2.6) - 0.35, Z(2.4) + 0.05, 0, { scale: 0.95 });
  put('haunch', X(2.6) + 0.3, Z(2.4) - 0.1, 0, { scale: 1.0 });
  put('bowl', X(2.6) - 0.18, Z(2.4) - 0.25, 0, { scale: 0.9 });
  put('bowl', X(2.6) + 0.2, Z(2.4) - 0.25, 0, { scale: 0.9 });

  // --- drinks: mug on the table, tankard by the bar
  put('mug', X(2.6) + 0.4, Z(2.4) + 0.3, 0, { scale: 1.0 });
  put('mug', X(2.6) - 0.05, Z(2.4) + 0.35, 0, { scale: 1.0 });
  put('tankard', X(2.0), Z(3.4) + 0.3, 0, { scale: 1.0 });

  // --- second small round table + chairs (north-center near the doorway)
  put('round-table', X(4.4), Z(2.0), 0, { scale: 1.0 });
  put('chair', X(4.4) - 0.5, Z(2.0), 0, { yaw: 90 });
  put('chair', X(4.4) + 0.5, Z(2.0), 0, { yaw: -90 });
  put('mug', X(4.4) + 0.05, Z(2.0), 0, { scale: 1.0 });

  // --- stool by the bar
  put('stool', X(2.0), Z(3.0), 0, { yaw: 180 });

  // --- crates and sack in the SW corner (storage)
  put('crate', X(0.6), Z(3.4), 0, { yaw: 0, scale: 0.9 });
  put('crate', X(0.6), Z(3.0), 0, { yaw: 8, scale: 0.9 });
  put('sack', X(0.6) + 0.3, Z(3.7), 0, { yaw: 30, scale: 1.0 });
  put('sack', X(0.7), Z(2.7), 0, { yaw: 200, scale: 1.0 });

  // --- lighting: candelabra on the feast table, candle on the round table, chandelier hanging
  put('candelabra', X(2.6), Z(2.4) + 0.5, 0, { scale: 0.9 });
  put('candle', X(4.4), Z(2.0) + 0.15, 0, { scale: 0.9 });
  put('chandelier', X(3.2), Z(2.0), 1.6, { scale: 1.0 });

  return places;
}