/** Generated by scripts/apk2d-pack.ts: the 2D camera of the baked background (backgrounds/potion-rush.png). */
import type { Projection2D } from '../../../apk3d/view2d/projection.js';

export const BACKGROUND_FILE = 'background.potion-rush';
export const PROJECTION: Projection2D = {"elevation":45,"ppm":64,"uMin":-5.2,"vMax":4.9039031357806655,"width":666,"height":432};
