/** English UI text of RPG Battle (catalog scope `rpgBattle`). */
export default {
  rpgBattle: {
    title: 'RPG Battle',
    pitch: 'Pick a word card, know its meaning, and strike.',
    subtitle: 'Word cards',
    briefing: {
      objective: 'Help the heroes beat the monsters: each word card you know becomes a hero’s attack.',
      instructions: {
        pick: { title: 'Pick a card', description: 'Each card shows a word and an action. Pick the card you want to play.' },
        answer: { title: 'Know its meaning', description: 'Choose the right meaning to cast the card. A wrong choice goes back to the hand, and you can try again.' },
        power: { title: 'Power cards', description: 'A ★ power card hits twice as hard and gives courage back. There is no timer.' },
      },
      controls: { touch: { label: 'Tap', action: 'Tap a card, then tap a meaning' }, pointer: { label: 'Click', action: 'Click a card, then click a meaning' } },
      learningPreview: 'Words from your story',
      tip: 'A wrong choice costs courage, and the monster strikes. Courage always comes back.',
      start: 'Start the battle ⚔️',
    },
    hud: {
      place: 'The Sunken Vault',
      progress: '{index}/{count} · {name}',
      courage: 'Courage',
      story: '📖 Story',
      pickCard: 'Pick a word card',
      whichMeaning: 'What does this word mean?',
      back: '↩ Pick another card',
      again: 'Try this one again',
      power: '★ Power',
      basic: 'Basic',
      right: 'Great! ✓',
      wrong: 'Not quite. The answer is <b>{answer}</b>',
      continue: 'Continue',
      streak: 'Combo ×{count}',
      coins: '+{count}',
      courageLost: '-1 ❤',
      courageGained: '+{count} ❤',
      intro: 'A new monster wakes up!',
      rest: { title: 'Take a deep breath', text: 'The heroes rest together and feel brave again.' },
      victory: { title: 'Victory!', text: 'The Sunken Vault is safe.' },
    },
    actions: { slash: 'Slash', blaze: 'Blaze', mend: 'Mend' },
    monsters: { skeleton: 'Skeleton', mimic: 'Mimic', 'dragon-fire': 'Fire Dragon' },
    heroes: { knight: 'Knight', wizard: 'Wizard', cleric: 'Cleric' },
  },
} as const;
