import { cpSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { avatarPackVersion, stampAvatarPack, writeAvatarPackVersion } from '../../scripts/avatar-version.js';

const dirs: string[] = [];
afterEach(() => {
  for (const d of dirs.splice(0)) rmSync(d, { recursive: true, force: true });
});

const json = (value: unknown) => `${JSON.stringify(value, null, 1)}\n`;

/** A pack folder at version 1.0.0 with the given items (one GLB each) and a portrait index. */
function pack(items: string[], glb = 'glb'): string {
  const dir = mkdtempSync(join(tmpdir(), 'avatar-pack-'));
  dirs.push(dir);
  mkdirSync(join(dir, 'pieces'));
  for (const id of items) writeFileSync(join(dir, 'pieces', `${id}.glb`), `${glb}:${id}`);
  writeFileSync(join(dir, 'pack.json'), json({ id: 'avatar', version: '1.0.0', root: 'packs/avatar/1.0.0', files: {} }));
  writeFileSync(join(dir, 'catalog.json'), json({ version: '1.0.0', items: items.map((id) => ({ id, price: 50 })) }));
  writeFileSync(join(dir, 'portraits.json'), json({ version: '1.0.0', size: 512, layers: {} }));
  return dir;
}

describe('the avatar pack version', () => {
  it('stays when every file is the same', () => {
    expect(avatarPackVersion(pack(['wand', 'staff']), pack(['wand', 'staff']), '1.0.0')).toBe('1.0.0');
  });

  it('takes the next patch for changed files and the next minor for added or removed items', () => {
    expect(avatarPackVersion(pack(['wand', 'staff']), pack(['wand', 'staff'], 'glb2'), '1.0.0')).toBe('1.0.1');
    expect(avatarPackVersion(pack(['wand', 'staff']), pack(['wand', 'staff', 'echo-staff']), '1.0.1')).toBe('1.1.0');
    expect(avatarPackVersion(pack(['wand', 'staff']), pack(['wand']), '1.2.3')).toBe('1.3.0');
  });

  it('keeps the version when nothing is published yet', () => {
    expect(avatarPackVersion(join(tmpdir(), 'no-such-avatar-pack'), pack(['wand']), '1.0.0')).toBe('1.0.0');
  });

  it('stamps a new version into the manifests and keeps their layout', () => {
    const dir = pack(['wand']);
    stampAvatarPack(dir, '1.1.0');
    expect(readFileSync(join(dir, 'pack.json'), 'utf8')).toBe(json({ id: 'avatar', version: '1.1.0', root: 'packs/avatar/1.1.0', files: {} }));
    expect(JSON.parse(readFileSync(join(dir, 'catalog.json'), 'utf8')).version).toBe('1.1.0');
    expect(JSON.parse(readFileSync(join(dir, 'portraits.json'), 'utf8')).version).toBe('1.1.0');
  });

  it('rewrites the version file and keeps its comment', () => {
    const root = mkdtempSync(join(tmpdir(), 'avatar-root-'));
    dirs.push(root);
    mkdirSync(join(root, 'src', 'apk3d', 'avatar'), { recursive: true });
    cpSync('src/apk3d/avatar/pack-version.ts', join(root, 'src', 'apk3d', 'avatar', 'pack-version.ts'));
    writeAvatarPackVersion('1.1.0', root);
    const text = readFileSync(join(root, 'src', 'apk3d', 'avatar', 'pack-version.ts'), 'utf8');
    expect(text).toContain("export const AVATAR_PACK_VERSION = '1.1.0';");
    expect(text).toContain('Generated by scripts/rpg-skin.ts');
  });
});
