/**
 * English UI text of the standalone host. At port time these keys move under the app's locale
 * files; the APK host pages own this text there.
 */
export default {
  host: {
    brand: 'Chibi Quest',
    tagline: 'Read a story, then play it!',
    loading: 'Opening the gates…',
    back: 'Back',
    sound: 'Sound',
    selector: {
      hero: 'Hero',
      lookLocked: '⭐ 3 stars unlock a new look',
      level: 'Level',
      comingSoon: 'Coming soon',
      story: 'Choose a story',
      game: 'Choose a game',
      noGame: 'No game fits this story yet. Choose another story.',
      helper: 'Helper mode (easier)',
      read: '📖 Read the story',
      foot: 'A demo of Reading Advantage · primary stories · no sign-in',
      plainCover: 'Story',
    },
    reader: {
      readHint: 'Read the story. Tap a <b>yellow word</b> to see what it means.',
      lookHint: 'Look for the answer in the story.',
      readToMe: '🔊 Read to me',
      thai: 'ไทย',
      finished: 'You finished the story! Now use its words in the game.',
      next: 'Play {game} ▶',
      backToGame: 'Back to the game',
      close: 'Close',
      listen: 'Listen',
    },
    briefing: {
      eyebrow: 'How to play',
      objective: 'Your goal',
      instructions: 'Steps',
      controls: 'Controls',
      tip: 'Tip',
      preview: 'From your story',
      items: '{count} items',
      start: 'Start',
    },
    results: {
      title: 'Well done!',
      xp: '+{xp} XP',
      xpNote: 'Stars show how many you knew on the first try: {pct}%.',
      storyWords: 'Your answers',
      practice: 'Practice these again',
      rewardUnlocked: '⭐ New look unlocked: {hero} “{look}”! It is on now; change it on the first screen.',
      rewardAll: '⭐ Every look is unlocked for this hero!',
      rewardHint: 'Get 3 stars to unlock new hero colors!',
      again: 'Play again',
      other: 'Another game',
      classBoss: 'Help your class ⚔️',
      default: 'default',
    },
    boss: {
      title: 'Class quest',
      intro: 'This week your class fights <b>{boss}</b>.<br />Every student’s correct answers help.',
      yourDamage: 'Your answers: <span class="dmg">-{damage}</span> HP',
      played: '{played} of {size} classmates have helped this week.',
      defeated: '{played} of {size} classmates have helped this week, and the dragon is defeated! 🎉',
      helpers: 'Recent helpers',
      you: 'You',
      note: 'An example class. In the app, the whole class shares one boss, and every student can help. There is no ranking.',
      home: 'Read another story',
    },
    gate: {
      title: 'This device is not supported for this game',
      body: 'Try this game on a newer phone, a tablet, or a computer. You can still read the story here.',
      reason: {
        webgl: 'The browser cannot draw 3D graphics (WebGL 2).',
        softwareGl: 'The browser draws 3D graphics without the graphics chip.',
        textureSize: 'The graphics chip is too small for this game.',
        skinning: 'The graphics chip cannot animate the characters.',
        iosVersion: 'This game needs iOS 15 or newer.',
        webviewVersion: 'This app’s browser is too old for this game.',
        unknown: 'This device cannot run this game.',
      },
    },
    heroes: { knight: 'Knight', wizard: 'Wizard', cleric: 'Cleric' },
    games: {
      comingSoon: 'Coming soon',
      dragonFlight: { title: 'Dragon Flight', pitch: 'Fly through the gate with the right meaning.' },
      dungeonLiberator: { title: 'Dungeon Liberator', pitch: 'Free the prisoners in word order.' },
      devourerSlime: { title: 'Devourer Slime', pitch: 'Eat the words in order and grow.' },
    },
  },
} as const;
