/** Generated by scripts/apk2d-pack.ts: the 2D camera of the baked background (backgrounds/hero-vs-zombie.png). */
import type { Projection2D } from '../../../apk3d/view2d/projection.js';

export const BACKGROUND_FILE = 'background.hero-vs-zombie';
export const PROJECTION: Projection2D = {"elevation":45,"ppm":64,"uMin":-7.8,"vMax":7.167119653543571,"width":998,"height":812};
