/** Generated by scripts/apk2d-pack.ts: the 2D camera of the baked background (backgrounds/dungeon-liberator.png). */
import type { Projection2D } from '../../../apk3d/view2d/projection.js';

export const BACKGROUND_FILE = 'background.dungeon-liberator';
export const PROJECTION: Projection2D = {"elevation":45,"ppm":64,"uMin":-6.6,"vMax":5.6563165231403385,"width":845,"height":615};
