// GENERATED by scripts/design-apothecary.mjs — edit the generator, not this file.
import type { Place } from '../chibi-quest.js';
export function places(): Place[] {
  return [
  {
    asset: 'wood-floor',
    at: [
      -4,
      0,
      -3
    ]
  },
  {
    asset: 'wood-floor',
    at: [
      -4,
      0,
      -1
    ]
  },
  {
    asset: 'wood-floor',
    at: [
      -4,
      0,
      1
    ]
  },
  {
    asset: 'wood-floor',
    at: [
      -4,
      0,
      3
    ]
  },
  {
    asset: 'wood-floor',
    at: [
      -2,
      0,
      -3
    ]
  },
  {
    asset: 'wood-floor',
    at: [
      -2,
      0,
      -1
    ]
  },
  {
    asset: 'wood-floor',
    at: [
      -2,
      0,
      1
    ]
  },
  {
    asset: 'wood-floor',
    at: [
      -2,
      0,
      3
    ]
  },
  {
    asset: 'wood-floor',
    at: [
      0,
      0,
      -3
    ]
  },
  {
    asset: 'wood-floor',
    at: [
      0,
      0,
      -1
    ]
  },
  {
    asset: 'wood-floor',
    at: [
      0,
      0,
      1
    ]
  },
  {
    asset: 'wood-floor',
    at: [
      0,
      0,
      3
    ]
  },
  {
    asset: 'wood-floor',
    at: [
      2,
      0,
      -3
    ]
  },
  {
    asset: 'wood-floor',
    at: [
      2,
      0,
      -1
    ]
  },
  {
    asset: 'wood-floor',
    at: [
      2,
      0,
      1
    ]
  },
  {
    asset: 'wood-floor',
    at: [
      2,
      0,
      3
    ]
  },
  {
    asset: 'wood-floor',
    at: [
      4,
      0,
      -3
    ]
  },
  {
    asset: 'wood-floor',
    at: [
      4,
      0,
      -1
    ]
  },
  {
    asset: 'wood-floor',
    at: [
      4,
      0,
      1
    ]
  },
  {
    asset: 'wood-floor',
    at: [
      4,
      0,
      3
    ]
  },
  {
    asset: 'plaster-wall',
    at: [
      -4,
      0,
      -3.92
    ]
  },
  {
    asset: 'plaster-wall',
    at: [
      -2,
      0,
      -3.92
    ]
  },
  {
    asset: 'plaster-wall',
    at: [
      0,
      0,
      -3.92
    ]
  },
  {
    asset: 'plaster-wall',
    at: [
      2,
      0,
      -3.92
    ]
  },
  {
    asset: 'plaster-wall',
    at: [
      4,
      0,
      -3.92
    ]
  },
  {
    asset: 'plaster-wall',
    at: [
      -4.92,
      0,
      -3
    ],
    yaw: 90
  },
  {
    asset: 'plaster-wall',
    at: [
      -4.92,
      0,
      -1
    ],
    yaw: 90
  },
  {
    asset: 'plaster-wall',
    at: [
      -4.92,
      0,
      0.9
    ],
    yaw: 90
  },
  {
    asset: 'plaster-wall-door',
    at: [
      -4.92,
      0,
      2.9
    ],
    yaw: 90
  },
  {
    asset: 'shelf',
    at: [
      -4,
      0,
      -3.91
    ]
  },
  {
    asset: 'bottle',
    at: [
      -4.433,
      0.475,
      -3.758
    ],
    yaw: 180
  },
  {
    asset: 'candle',
    at: [
      -4.26,
      0.475,
      -3.743
    ],
    yaw: 180
  },
  {
    asset: 'candle',
    at: [
      -4.087,
      0.475,
      -3.733
    ]
  },
  {
    asset: 'candle',
    at: [
      -3.913,
      0.475,
      -3.762
    ]
  },
  {
    asset: 'candle',
    at: [
      -3.74,
      0.475,
      -3.768
    ],
    yaw: 90
  },
  {
    asset: 'bottle',
    at: [
      -3.567,
      0.475,
      -3.767
    ],
    yaw: 180
  },
  {
    asset: 'candle',
    at: [
      -4.433,
      0.805,
      -3.738
    ],
    yaw: 180
  },
  {
    asset: 'bottle',
    at: [
      -4.26,
      0.805,
      -3.745
    ],
    yaw: 90
  },
  {
    asset: 'vial',
    at: [
      -4.087,
      0.805,
      -3.734
    ]
  },
  {
    asset: 'candle',
    at: [
      -3.913,
      0.805,
      -3.764
    ]
  },
  {
    asset: 'jar',
    at: [
      -3.74,
      0.805,
      -3.74
    ],
    scale: 0.58
  },
  {
    asset: 'candle',
    at: [
      -3.567,
      0.805,
      -3.737
    ],
    yaw: 270
  },
  {
    asset: 'jar',
    at: [
      -4.433,
      1.115,
      -3.769
    ],
    scale: 0.58
  },
  {
    asset: 'vial',
    at: [
      -4.26,
      1.115,
      -3.764
    ],
    yaw: 180
  },
  {
    asset: 'vial',
    at: [
      -4.087,
      1.115,
      -3.758
    ],
    yaw: 270
  },
  {
    asset: 'vial',
    at: [
      -3.913,
      1.115,
      -3.735
    ],
    yaw: 180
  },
  {
    asset: 'vial',
    at: [
      -3.74,
      1.115,
      -3.752
    ],
    yaw: 180
  },
  {
    asset: 'bottle',
    at: [
      -3.567,
      1.115,
      -3.758
    ],
    yaw: 270
  },
  {
    asset: 'shelf',
    at: [
      -2.62,
      0,
      -3.91
    ]
  },
  {
    asset: 'jar',
    at: [
      -3.053,
      0.475,
      -3.756
    ],
    scale: 0.58
  },
  {
    asset: 'jar',
    at: [
      -2.88,
      0.475,
      -3.747
    ],
    scale: 0.58
  },
  {
    asset: 'vial',
    at: [
      -2.707,
      0.475,
      -3.747
    ]
  },
  {
    asset: 'bottle',
    at: [
      -2.533,
      0.475,
      -3.746
    ],
    yaw: 180
  },
  {
    asset: 'bottle',
    at: [
      -2.36,
      0.475,
      -3.758
    ],
    yaw: 90
  },
  {
    asset: 'bottle',
    at: [
      -2.187,
      0.475,
      -3.739
    ]
  },
  {
    asset: 'bottle',
    at: [
      -3.053,
      0.805,
      -3.736
    ],
    yaw: 180
  },
  {
    asset: 'jar',
    at: [
      -2.88,
      0.805,
      -3.733
    ],
    scale: 0.58
  },
  {
    asset: 'vial',
    at: [
      -2.707,
      0.805,
      -3.751
    ],
    yaw: 90
  },
  {
    asset: 'jar',
    at: [
      -2.533,
      0.805,
      -3.743
    ],
    scale: 0.58
  },
  {
    asset: 'vial',
    at: [
      -2.36,
      0.805,
      -3.762
    ],
    yaw: 180
  },
  {
    asset: 'bottle',
    at: [
      -2.187,
      0.805,
      -3.759
    ],
    yaw: 270
  },
  {
    asset: 'jar',
    at: [
      -3.053,
      1.115,
      -3.753
    ],
    scale: 0.58
  },
  {
    asset: 'vial',
    at: [
      -2.88,
      1.115,
      -3.75
    ],
    yaw: 90
  },
  {
    asset: 'vial',
    at: [
      -2.707,
      1.115,
      -3.736
    ],
    yaw: 90
  },
  {
    asset: 'bottle',
    at: [
      -2.533,
      1.115,
      -3.768
    ],
    yaw: 270
  },
  {
    asset: 'jar',
    at: [
      -2.36,
      1.115,
      -3.752
    ],
    scale: 0.58
  },
  {
    asset: 'bottle',
    at: [
      -2.187,
      1.115,
      -3.737
    ],
    yaw: 90
  },
  {
    asset: 'shelf',
    at: [
      -1.24,
      0,
      -3.91
    ]
  },
  {
    asset: 'vial',
    at: [
      -1.673,
      0.475,
      -3.752
    ],
    yaw: 270
  },
  {
    asset: 'vial',
    at: [
      -1.5,
      0.475,
      -3.77
    ],
    yaw: 90
  },
  {
    asset: 'bottle',
    at: [
      -1.327,
      0.475,
      -3.73
    ],
    yaw: 90
  },
  {
    asset: 'bottle',
    at: [
      -1.153,
      0.475,
      -3.746
    ],
    yaw: 270
  },
  {
    asset: 'jar',
    at: [
      -0.98,
      0.475,
      -3.731
    ],
    scale: 0.58
  },
  {
    asset: 'vial',
    at: [
      -0.807,
      0.475,
      -3.761
    ],
    yaw: 90
  },
  {
    asset: 'vial',
    at: [
      -1.673,
      0.805,
      -3.739
    ],
    yaw: 180
  },
  {
    asset: 'candle',
    at: [
      -1.5,
      0.805,
      -3.739
    ],
    yaw: 180
  },
  {
    asset: 'candle',
    at: [
      -1.327,
      0.805,
      -3.754
    ],
    yaw: 180
  },
  {
    asset: 'candle',
    at: [
      -1.153,
      0.805,
      -3.752
    ],
    yaw: 90
  },
  {
    asset: 'jar',
    at: [
      -0.98,
      0.805,
      -3.734
    ],
    scale: 0.58
  },
  {
    asset: 'candle',
    at: [
      -0.807,
      0.805,
      -3.763
    ]
  },
  {
    asset: 'vial',
    at: [
      -1.673,
      1.115,
      -3.768
    ]
  },
  {
    asset: 'jar',
    at: [
      -1.5,
      1.115,
      -3.737
    ],
    scale: 0.58
  },
  {
    asset: 'vial',
    at: [
      -1.327,
      1.115,
      -3.748
    ],
    yaw: 90
  },
  {
    asset: 'bottle',
    at: [
      -1.153,
      1.115,
      -3.746
    ],
    yaw: 180
  },
  {
    asset: 'candle',
    at: [
      -0.98,
      1.115,
      -3.734
    ]
  },
  {
    asset: 'jar',
    at: [
      -0.807,
      1.115,
      -3.765
    ],
    scale: 0.58
  },
  {
    asset: 'counter',
    at: [
      -2.6,
      0,
      -2
    ]
  },
  {
    asset: 'healer',
    at: [
      -3.3,
      0,
      -2.85
    ]
  },
  {
    asset: 'scales',
    at: [
      -1.95,
      0.75,
      -2
    ]
  },
  {
    asset: 'mortar-pestle',
    at: [
      -3.15,
      0.75,
      -2
    ],
    yaw: 20
  },
  {
    asset: 'jar',
    at: [
      -2.6,
      0.75,
      -2.05
    ],
    scale: 0.7
  },
  {
    asset: 'jar',
    at: [
      -2.35,
      0.75,
      -1.95
    ],
    yaw: 40,
    scale: 0.6
  },
  {
    asset: 'bottle',
    at: [
      -3.5,
      0.75,
      -1.818
    ]
  },
  {
    asset: 'vial',
    at: [
      -3.35,
      0.75,
      -1.867
    ]
  },
  {
    asset: 'bottle',
    at: [
      -2.85,
      0.75,
      -1.869
    ]
  },
  {
    asset: 'vial',
    at: [
      -1.6,
      0.75,
      -1.831
    ]
  },
  {
    asset: 'bottle',
    at: [
      -1.45,
      0.75,
      -1.889
    ]
  },
  {
    asset: 'candle',
    at: [
      -3.6,
      0.75,
      -2.1
    ]
  },
  {
    asset: 'healing-herb',
    at: [
      -2.2,
      0.75,
      -1.75
    ],
    yaw: 30,
    scale: 0.8
  },
  {
    asset: 'herb-root',
    at: [
      -2.05,
      0.75,
      -1.7
    ],
    yaw: 10,
    scale: 0.8
  },
  {
    asset: 'rug',
    at: [
      -2.6,
      0,
      -0.6
    ]
  },
  {
    asset: 'stool',
    at: [
      -3.2,
      0.04,
      -1.2
    ]
  },
  {
    asset: 'stool',
    at: [
      -2,
      0.04,
      -1.2
    ]
  },
  {
    asset: 'stool',
    at: [
      -2.6,
      0.04,
      -0.2
    ]
  },
  {
    asset: 'cupboard',
    at: [
      0,
      0,
      -3.65
    ]
  },
  {
    asset: 'cupboard',
    at: [
      1,
      0,
      -3.65
    ]
  },
  {
    asset: 'jar',
    at: [
      -0.2,
      1.4,
      -3.68
    ],
    scale: 0.5
  },
  {
    asset: 'bottle',
    at: [
      0.3,
      1.4,
      -3.68
    ]
  },
  {
    asset: 'jar',
    at: [
      0.6,
      1.4,
      -3.68
    ],
    scale: 0.5
  },
  {
    asset: 'bottle',
    at: [
      1.2,
      1.4,
      -3.68
    ]
  },
  {
    asset: 'herb-drying-rack',
    at: [
      2.5,
      0,
      -3.5
    ]
  },
  {
    asset: 'herb-drying-rack',
    at: [
      3.65,
      0,
      -3.5
    ]
  },
  {
    asset: 'herb-drying-rack',
    at: [
      4.45,
      0,
      -2.7
    ],
    yaw: 90
  },
  {
    asset: 'basket',
    at: [
      2,
      0,
      -2.7
    ],
    yaw: 270
  },
  {
    asset: 'healing-herb',
    at: [
      1.94,
      0.26,
      -2.7
    ],
    yaw: 30,
    scale: 0.9
  },
  {
    asset: 'healing-herb',
    at: [
      2.08,
      0.26,
      -2.67
    ],
    yaw: 150,
    scale: 0.8
  },
  {
    asset: 'herb-root',
    at: [
      2,
      0.3,
      -2.77
    ],
    yaw: 80,
    scale: 0.8
  },
  {
    asset: 'basket',
    at: [
      3.2,
      0,
      -2.75
    ],
    yaw: 90
  },
  {
    asset: 'healing-herb',
    at: [
      3.14,
      0.26,
      -2.75
    ],
    yaw: 30,
    scale: 0.9
  },
  {
    asset: 'healing-herb',
    at: [
      3.28,
      0.26,
      -2.72
    ],
    yaw: 150,
    scale: 0.8
  },
  {
    asset: 'herb-root',
    at: [
      3.2,
      0.3,
      -2.82
    ],
    yaw: 80,
    scale: 0.8
  },
  {
    asset: 'basket',
    at: [
      3.95,
      0,
      -2.65
    ],
    yaw: 90
  },
  {
    asset: 'healing-herb',
    at: [
      3.89,
      0.26,
      -2.65
    ],
    yaw: 30,
    scale: 0.9
  },
  {
    asset: 'healing-herb',
    at: [
      4.03,
      0.26,
      -2.62
    ],
    yaw: 150,
    scale: 0.8
  },
  {
    asset: 'herb-root',
    at: [
      3.95,
      0.3,
      -2.72
    ],
    yaw: 80,
    scale: 0.8
  },
  {
    asset: 'sack',
    at: [
      4.5,
      0,
      -1.2
    ],
    yaw: 20
  },
  {
    asset: 'sack',
    at: [
      4.6,
      0,
      -0.65
    ],
    yaw: 70
  },
  {
    asset: 'crate',
    at: [
      4.45,
      0,
      -1.9
    ]
  },
  {
    asset: 'healing-herb',
    at: [
      4.45,
      0.4,
      -1.9
    ],
    yaw: 20
  },
  {
    asset: 'herb-root',
    at: [
      4.2,
      0,
      -1.2
    ],
    yaw: 80
  },
  {
    asset: 'bookshelf',
    at: [
      -4.74,
      0,
      -0.1
    ],
    yaw: 90
  },
  {
    asset: 'bookshelf',
    at: [
      -4.74,
      0,
      0.95
    ],
    yaw: 90
  },
  {
    asset: 'lantern',
    at: [
      -4.7,
      0,
      1.9
    ],
    scale: 0.9
  },
  {
    asset: 'barrel',
    at: [
      -4.55,
      0,
      3.55
    ]
  },
  {
    asset: 'basket',
    at: [
      -4.55,
      0,
      2.85
    ],
    yaw: 90
  },
  {
    asset: 'rug',
    at: [
      0.2,
      0,
      0.9
    ]
  },
  {
    asset: 'table',
    at: [
      0.2,
      0.04,
      0.9
    ]
  },
  {
    asset: 'stool',
    at: [
      -0.7,
      0,
      0.95
    ],
    yaw: 90
  },
  {
    asset: 'stool',
    at: [
      1.1,
      0,
      0.9
    ],
    yaw: 270
  },
  {
    asset: 'stool',
    at: [
      0.2,
      0,
      1.8
    ]
  },
  {
    asset: 'bottle',
    at: [
      -0.05,
      0.64,
      0.85
    ]
  },
  {
    asset: 'vial',
    at: [
      0.12,
      0.64,
      1
    ]
  },
  {
    asset: 'mortar-pestle',
    at: [
      0.45,
      0.64,
      0.75
    ],
    yaw: 10,
    scale: 0.8
  },
  {
    asset: 'candle',
    at: [
      0.3,
      0.64,
      1.1
    ]
  },
  {
    asset: 'jar',
    at: [
      0.55,
      0.64,
      1.05
    ],
    scale: 0.5
  },
  {
    asset: 'cauldron',
    at: [
      3.1,
      0,
      2.2
    ],
    yaw: 200
  },
  {
    asset: 'barrel',
    at: [
      4.5,
      0,
      3.4
    ]
  },
  {
    asset: 'barrel',
    at: [
      4.5,
      0,
      2.55
    ]
  },
  {
    asset: 'barrel',
    at: [
      3.75,
      0,
      3.55
    ]
  },
  {
    asset: 'sack',
    at: [
      2.7,
      0,
      3.5
    ],
    yaw: 330
  },
  {
    asset: 'crate',
    at: [
      4.4,
      0,
      1.45
    ],
    yaw: 10
  },
  {
    asset: 'jar',
    at: [
      4.4,
      0.4,
      1.45
    ],
    scale: 0.6
  },
  {
    asset: 'bottle',
    at: [
      4.55,
      0.92,
      2.55
    ]
  },
  {
    asset: 'vial',
    at: [
      4.4,
      0.92,
      2.5
    ]
  },
  {
    asset: 'basket',
    at: [
      2,
      0,
      3.55
    ],
    yaw: 20
  },
  {
    asset: 'healing-herb',
    at: [
      1.95,
      0.3,
      3.55
    ],
    yaw: 80,
    scale: 0.9
  },
  {
    asset: 'herb-root',
    at: [
      2.1,
      0.3,
      3.5
    ],
    yaw: 20,
    scale: 0.8
  },
  {
    asset: 'mortar-pestle',
    at: [
      -2.6,
      0,
      3.4
    ],
    yaw: 40,
    scale: 2.2
  },
  {
    asset: 'healing-herb',
    at: [
      -3.3,
      0,
      3.7
    ]
  },
  {
    asset: 'healing-herb',
    at: [
      -3.1,
      0,
      3.8
    ],
    yaw: 90
  },
  {
    asset: 'healing-herb',
    at: [
      -3.2,
      0,
      3.55
    ],
    yaw: 200
  },
  {
    asset: 'herb-root',
    at: [
      -1.5,
      0,
      3.75
    ],
    yaw: 40
  },
  {
    asset: 'healing-herb',
    at: [
      -1.3,
      0,
      3.8
    ],
    yaw: 120
  },
  {
    asset: 'healing-herb',
    at: [
      -1.15,
      0,
      3.7
    ],
    yaw: 20
  },
  {
    asset: 'herb-root',
    at: [
      1.6,
      0,
      3.8
    ],
    yaw: 144
  },
  {
    asset: 'herb-root',
    at: [
      1.8,
      0,
      3.8
    ],
    yaw: 162
  },
  {
    asset: 'healing-herb',
    at: [
      3,
      0,
      3.8
    ],
    yaw: 10
  },
  {
    asset: 'healing-herb',
    at: [
      3.2,
      0,
      3.7
    ],
    yaw: 130
  }
];
}
