// GENERATED by scripts/design-bakery.mjs — edit the generator, not this file.
import type { Place } from '../chibi-quest.js';
export function places(): Place[] {
  return [
  {
    asset: 'wood-floor',
    at: [
      -3,
      0,
      -2
    ]
  },
  {
    asset: 'wood-floor',
    at: [
      -3,
      0,
      0
    ]
  },
  {
    asset: 'wood-floor',
    at: [
      -3,
      0,
      2
    ]
  },
  {
    asset: 'stone-floor',
    at: [
      -1,
      0,
      -2
    ]
  },
  {
    asset: 'wood-floor',
    at: [
      -1,
      0,
      0
    ]
  },
  {
    asset: 'wood-floor',
    at: [
      -1,
      0,
      2
    ]
  },
  {
    asset: 'stone-floor',
    at: [
      1,
      0,
      -2
    ]
  },
  {
    asset: 'wood-floor',
    at: [
      1,
      0,
      0
    ]
  },
  {
    asset: 'wood-floor',
    at: [
      1,
      0,
      2
    ]
  },
  {
    asset: 'wood-floor',
    at: [
      3,
      0,
      -2
    ]
  },
  {
    asset: 'wood-floor',
    at: [
      3,
      0,
      0
    ]
  },
  {
    asset: 'wood-floor',
    at: [
      3,
      0,
      2
    ]
  },
  {
    asset: 'plaster-wall-window',
    at: [
      -3,
      0,
      -2.92
    ]
  },
  {
    asset: 'brick-wall',
    at: [
      -1,
      0,
      -2.92
    ]
  },
  {
    asset: 'brick-wall',
    at: [
      1,
      0,
      -2.92
    ]
  },
  {
    asset: 'plaster-wall',
    at: [
      3,
      0,
      -2.92
    ]
  },
  {
    asset: 'plaster-wall',
    at: [
      -3.92,
      0,
      -2
    ],
    yaw: 90
  },
  {
    asset: 'plaster-wall-window',
    at: [
      -3.92,
      0,
      0
    ],
    yaw: 90
  },
  {
    asset: 'plaster-wall-door',
    at: [
      -3.92,
      0,
      2
    ],
    yaw: 90
  },
  {
    asset: 'fireplace',
    at: [
      -1.5,
      0,
      -2.78
    ],
    scale: 1.15
  },
  {
    asset: 'kiln',
    at: [
      1.15,
      0,
      -2.45
    ],
    scale: 1.4
  },
  {
    asset: 'firewood',
    at: [
      -0.25,
      0,
      -2.6
    ],
    yaw: 90,
    scale: 0.85
  },
  {
    asset: 'firewood',
    at: [
      2.45,
      0,
      -2.45
    ],
    scale: 0.7
  },
  {
    asset: 'innkeeper',
    at: [
      -0.3,
      0,
      -1.55
    ]
  },
  {
    asset: 'cooking-pot',
    at: [
      -2.2,
      0,
      -1.8
    ],
    yaw: 20
  },
  {
    asset: 'bucket',
    at: [
      0.8,
      0,
      -1.55
    ]
  },
  {
    asset: 'bread',
    at: [
      -1.3,
      0,
      -1.55
    ]
  },
  {
    asset: 'wall-sconce',
    at: [
      -2.45,
      1,
      -2.8
    ]
  },
  {
    asset: 'curtain',
    at: [
      -3,
      0,
      -2.75
    ],
    scale: 0.8
  },
  {
    asset: 'basket',
    at: [
      2.1,
      0,
      -1.6
    ]
  },
  {
    asset: 'loaf',
    at: [
      2.1,
      0.28,
      -1.6
    ],
    yaw: 30
  },
  {
    asset: 'counter',
    at: [
      -3.45,
      0,
      -1.2
    ],
    yaw: 90
  },
  {
    asset: 'counter',
    at: [
      -3.45,
      0,
      0.8
    ],
    yaw: 90
  },
  {
    asset: 'awning',
    at: [
      -3.9,
      0,
      -1.2
    ],
    yaw: 90
  },
  {
    asset: 'awning',
    at: [
      -3.9,
      0,
      0.8
    ],
    yaw: 90
  },
  {
    asset: 'loaf',
    at: [
      -3.438,
      0.75,
      -2
    ],
    yaw: 90
  },
  {
    asset: 'bread',
    at: [
      -3.423,
      0.75,
      -1.65
    ],
    yaw: 90
  },
  {
    asset: 'loaf',
    at: [
      -3.464,
      0.75,
      -1.3
    ],
    yaw: 90
  },
  {
    asset: 'bread',
    at: [
      -3.435,
      0.75,
      -0.95
    ],
    yaw: 90
  },
  {
    asset: 'loaf',
    at: [
      -3.425,
      0.75,
      -0.6
    ],
    yaw: 180
  },
  {
    asset: 'bread',
    at: [
      -3.484,
      0.75,
      -0.2
    ],
    yaw: 90
  },
  {
    asset: 'loaf',
    at: [
      -3.441,
      0.75,
      0.2
    ],
    yaw: 270
  },
  {
    asset: 'bread',
    at: [
      -3.462,
      0.75,
      0.55
    ],
    yaw: 90
  },
  {
    asset: 'loaf',
    at: [
      -3.425,
      0.75,
      0.9
    ]
  },
  {
    asset: 'bread',
    at: [
      -3.43,
      0.75,
      1.25
    ],
    yaw: 90
  },
  {
    asset: 'candle',
    at: [
      -3.3,
      0.75,
      1.5
    ]
  },
  {
    asset: 'basket',
    at: [
      -3.6,
      0.75,
      1.6
    ]
  },
  {
    asset: 'wicker-basket',
    at: [
      -3,
      0,
      1.75
    ],
    yaw: 40
  },
  {
    asset: 'loaf',
    at: [
      -3,
      0.3,
      1.75
    ],
    yaw: 30
  },
  {
    asset: 'stool',
    at: [
      -3.6,
      0,
      2.5
    ]
  },
  {
    asset: 'rug',
    at: [
      -2.9,
      0,
      2
    ],
    yaw: 90,
    scale: 0.8
  },
  {
    asset: 'lantern',
    at: [
      -3.55,
      0,
      2.7
    ],
    scale: 0.8
  },
  {
    asset: 'table',
    at: [
      0.3,
      0,
      0.5
    ],
    scale: 1.45
  },
  {
    asset: 'plate',
    at: [
      0,
      0.87,
      0.45
    ],
    scale: 1.2
  },
  {
    asset: 'bowl',
    at: [
      0.45,
      0.87,
      0.35
    ],
    scale: 1.2
  },
  {
    asset: 'loaf',
    at: [
      0.15,
      0.87,
      0.8
    ],
    yaw: 30,
    scale: 1.2
  },
  {
    asset: 'bread',
    at: [
      0.55,
      0.87,
      0.7
    ],
    yaw: 20,
    scale: 1.2
  },
  {
    asset: 'bread',
    at: [
      -0.1,
      0.87,
      0.15
    ],
    scale: 1.2
  },
  {
    asset: 'candle',
    at: [
      0.7,
      0.87,
      0.15
    ]
  },
  {
    asset: 'stool',
    at: [
      -0.7,
      0,
      0.5
    ],
    yaw: 90,
    scale: 1.2
  },
  {
    asset: 'stool',
    at: [
      1.3,
      0,
      0.5
    ],
    yaw: 270,
    scale: 1.2
  },
  {
    asset: 'stool',
    at: [
      0.3,
      0,
      1.4
    ],
    scale: 1.2
  },
  {
    asset: 'herb-drying-rack',
    at: [
      2.35,
      0,
      0.45
    ]
  },
  {
    asset: 'shelf',
    at: [
      3.3,
      0,
      -2.78
    ]
  },
  {
    asset: 'loaf',
    at: [
      2.962,
      0.475,
      -2.61
    ],
    scale: 1.3
  },
  {
    asset: 'bread',
    at: [
      3.187,
      0.475,
      -2.61
    ],
    yaw: 90,
    scale: 1.3
  },
  {
    asset: 'basket',
    at: [
      3.412,
      0.475,
      -2.61
    ],
    yaw: 270,
    scale: 0.55
  },
  {
    asset: 'wicker-basket',
    at: [
      3.637,
      0.475,
      -2.61
    ],
    yaw: 180,
    scale: 0.55
  },
  {
    asset: 'bread',
    at: [
      2.962,
      0.805,
      -2.61
    ],
    yaw: 90,
    scale: 1.3
  },
  {
    asset: 'loaf',
    at: [
      3.187,
      0.805,
      -2.61
    ],
    yaw: 180,
    scale: 1.3
  },
  {
    asset: 'loaf',
    at: [
      3.412,
      0.805,
      -2.61
    ],
    yaw: 180,
    scale: 1.3
  },
  {
    asset: 'bread',
    at: [
      3.637,
      0.805,
      -2.61
    ],
    yaw: 90,
    scale: 1.3
  },
  {
    asset: 'bread',
    at: [
      2.962,
      1.115,
      -2.61
    ],
    yaw: 90,
    scale: 1.3
  },
  {
    asset: 'wicker-basket',
    at: [
      3.187,
      1.115,
      -2.61
    ],
    yaw: 90,
    scale: 0.55
  },
  {
    asset: 'bread',
    at: [
      3.412,
      1.115,
      -2.61
    ],
    yaw: 90,
    scale: 1.3
  },
  {
    asset: 'loaf',
    at: [
      3.637,
      1.115,
      -2.61
    ],
    scale: 1.3
  },
  {
    asset: 'sack',
    at: [
      3.5,
      0,
      0
    ],
    yaw: 311
  },
  {
    asset: 'sack',
    at: [
      3.55,
      0,
      -0.7
    ],
    yaw: 305
  },
  {
    asset: 'sack',
    at: [
      3.5,
      0,
      1.2
    ],
    yaw: 94
  },
  {
    asset: 'sack',
    at: [
      2.9,
      0,
      2.55
    ],
    yaw: 28
  },
  {
    asset: 'sack',
    at: [
      3.5,
      0,
      2.6
    ],
    yaw: 6
  },
  {
    asset: 'sack',
    at: [
      3.55,
      0.4,
      0
    ],
    yaw: 40,
    scale: 0.9
  },
  {
    asset: 'sack',
    at: [
      3.5,
      0.4,
      1.2
    ],
    yaw: 140,
    scale: 0.9
  },
  {
    asset: 'barrel',
    at: [
      3.55,
      0,
      1.95
    ]
  },
  {
    asset: 'barrel',
    at: [
      2.35,
      0,
      2.6
    ]
  },
  {
    asset: 'crate',
    at: [
      1.6,
      0,
      2.6
    ],
    yaw: 10
  },
  {
    asset: 'loaf',
    at: [
      1.6,
      0.44,
      2.6
    ],
    yaw: 40
  },
  {
    asset: 'wicker-basket',
    at: [
      0.5,
      0,
      2.7
    ]
  },
  {
    asset: 'basket',
    at: [
      -0.6,
      0,
      2.7
    ],
    yaw: 20
  },
  {
    asset: 'barrel',
    at: [
      -1.3,
      0,
      2.65
    ]
  },
  {
    asset: 'lantern',
    at: [
      3,
      0,
      1.6
    ],
    scale: 0.8
  },
  {
    asset: 'crate',
    at: [
      -2,
      0,
      1.3
    ],
    yaw: 20
  },
  {
    asset: 'loaf',
    at: [
      -2,
      0.44,
      1.3
    ],
    yaw: 70
  },
  {
    asset: 'sack',
    at: [
      3.55,
      0,
      -1.4
    ],
    yaw: 257
  },
  {
    asset: 'sack',
    at: [
      3.55,
      0.4,
      -1.4
    ],
    yaw: 90,
    scale: 0.9
  },
  {
    asset: 'sack',
    at: [
      3.5,
      0,
      -2.1
    ],
    yaw: 181
  },
  {
    asset: 'sack',
    at: [
      3.5,
      0.4,
      -2.1
    ],
    yaw: 90,
    scale: 0.9
  },
  {
    asset: 'basket',
    at: [
      1.7,
      0,
      -0.8
    ],
    yaw: 90
  },
  {
    asset: 'loaf',
    at: [
      1.7,
      0.27,
      -0.8
    ],
    scale: 0.8
  },
  {
    asset: 'wicker-basket',
    at: [
      2.4,
      0,
      -1
    ],
    yaw: 90
  },
  {
    asset: 'loaf',
    at: [
      2.4,
      0.27,
      -1
    ],
    scale: 0.8
  },
  {
    asset: 'basket',
    at: [
      2.9,
      0,
      0.9
    ]
  },
  {
    asset: 'bread',
    at: [
      2.9,
      0.27,
      0.9
    ],
    yaw: 90,
    scale: 0.8
  },
  {
    asset: 'wicker-basket',
    at: [
      -2.3,
      0,
      2.6
    ],
    yaw: 270
  },
  {
    asset: 'bread',
    at: [
      -2.3,
      0.27,
      2.6
    ],
    yaw: 270,
    scale: 0.8
  },
  {
    asset: 'basket',
    at: [
      -1,
      0,
      1.4
    ],
    yaw: 270
  },
  {
    asset: 'bread',
    at: [
      -1,
      0.27,
      1.4
    ],
    scale: 0.8
  },
  {
    asset: 'bucket',
    at: [
      2,
      0,
      2.2
    ]
  },
  {
    asset: 'bucket',
    at: [
      -2.4,
      0,
      -0.3
    ]
  },
  {
    asset: 'workbench',
    at: [
      -1.9,
      0,
      0.5
    ],
    yaw: 90
  },
  {
    asset: 'loaf',
    at: [
      -1.9,
      0.85,
      0.2
    ],
    yaw: 90
  },
  {
    asset: 'bread',
    at: [
      -1.9,
      0.85,
      0.5
    ]
  },
  {
    asset: 'loaf',
    at: [
      -1.9,
      0.85,
      0.8
    ]
  },
  {
    asset: 'bowl',
    at: [
      -2,
      0.85,
      0.05
    ]
  },
  {
    asset: 'stool',
    at: [
      -1.2,
      0,
      0.5
    ],
    yaw: 90
  }
];
}
