// GENERATED by scripts/design-coral-reef.mjs — edit the generator, not this file.
import type { Place } from '../chibi-quest.js';
export function places(): Place[] {
  return [
    {
      "asset": "desert-ground",
      "at": [
        -10,
        0,
        -8
      ]
    },
    {
      "asset": "desert-ground",
      "at": [
        -8,
        0,
        -8
      ]
    },
    {
      "asset": "desert-ground",
      "at": [
        -6,
        0,
        -8
      ]
    },
    {
      "asset": "desert-ground",
      "at": [
        -4,
        0,
        -8
      ]
    },
    {
      "asset": "desert-ground",
      "at": [
        -2,
        0,
        -8
      ]
    },
    {
      "asset": "desert-ground",
      "at": [
        0,
        0,
        -8
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        2,
        0,
        -8
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        4,
        0,
        -8
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        6,
        0,
        -8
      ]
    },
    {
      "asset": "desert-ground",
      "at": [
        8,
        0,
        -8
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        10,
        0,
        -8
      ]
    },
    {
      "asset": "desert-ground",
      "at": [
        -10,
        0,
        -6
      ]
    },
    {
      "asset": "desert-ground",
      "at": [
        -8,
        0,
        -6
      ]
    },
    {
      "asset": "desert-ground",
      "at": [
        -6,
        0,
        -6
      ]
    },
    {
      "asset": "desert-ground",
      "at": [
        -4,
        0,
        -6
      ]
    },
    {
      "asset": "desert-ground",
      "at": [
        -2,
        0,
        -6
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        0,
        0,
        -6
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        2,
        0,
        -6
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        4,
        0,
        -6
      ]
    },
    {
      "asset": "desert-ground",
      "at": [
        6,
        0,
        -6
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        8,
        0,
        -6
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        10,
        0,
        -6
      ]
    },
    {
      "asset": "desert-ground",
      "at": [
        -10,
        0,
        -4
      ]
    },
    {
      "asset": "desert-ground",
      "at": [
        -8,
        0,
        -4
      ]
    },
    {
      "asset": "desert-ground",
      "at": [
        -6,
        0,
        -4
      ]
    },
    {
      "asset": "desert-ground",
      "at": [
        -4,
        0,
        -4
      ]
    },
    {
      "asset": "desert-ground",
      "at": [
        -2,
        0,
        -4
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        0,
        0,
        -4
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        2,
        0,
        -4
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        4,
        0,
        -4
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        6,
        0,
        -4
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        8,
        0,
        -4
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        10,
        0,
        -4
      ]
    },
    {
      "asset": "desert-ground",
      "at": [
        -10,
        0,
        -2
      ]
    },
    {
      "asset": "desert-ground",
      "at": [
        -8,
        0,
        -2
      ]
    },
    {
      "asset": "desert-ground",
      "at": [
        -6,
        0,
        -2
      ]
    },
    {
      "asset": "desert-ground",
      "at": [
        -4,
        0,
        -2
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        -2,
        0,
        -2
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        0,
        0,
        -2
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        2,
        0,
        -2
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        4,
        0,
        -2
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        6,
        0,
        -2
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        8,
        0,
        -2
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        10,
        0,
        -2
      ]
    },
    {
      "asset": "desert-ground",
      "at": [
        -10,
        0,
        0
      ]
    },
    {
      "asset": "desert-ground",
      "at": [
        -8,
        0,
        0
      ]
    },
    {
      "asset": "desert-ground",
      "at": [
        -6,
        0,
        0
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        -4,
        0,
        0
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        -2,
        0,
        0
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        0,
        0,
        0
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        2,
        0,
        0
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        4,
        0,
        0
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        6,
        0,
        0
      ]
    },
    {
      "asset": "desert-ground",
      "at": [
        8,
        0,
        0
      ]
    },
    {
      "asset": "desert-ground",
      "at": [
        10,
        0,
        0
      ]
    },
    {
      "asset": "desert-ground",
      "at": [
        -10,
        0,
        2
      ]
    },
    {
      "asset": "desert-ground",
      "at": [
        -8,
        0,
        2
      ]
    },
    {
      "asset": "desert-ground",
      "at": [
        -6,
        0,
        2
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        -4,
        0,
        2
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        -2,
        0,
        2
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        0,
        0,
        2
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        2,
        0,
        2
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        4,
        0,
        2
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        6,
        0,
        2
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        8,
        0,
        2
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        10,
        0,
        2
      ]
    },
    {
      "asset": "desert-ground",
      "at": [
        -10,
        0,
        4
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        -8,
        0,
        4
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        -6,
        0,
        4
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        -4,
        0,
        4
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        -2,
        0,
        4
      ]
    },
    {
      "asset": "desert-ground",
      "at": [
        0,
        0,
        4
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        2,
        0,
        4
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        4,
        0,
        4
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        6,
        0,
        4
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        8,
        0,
        4
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        10,
        0,
        4
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        -10,
        0,
        6
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        -8,
        0,
        6
      ]
    },
    {
      "asset": "desert-ground",
      "at": [
        -6,
        0,
        6
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        -4,
        0,
        6
      ]
    },
    {
      "asset": "desert-ground",
      "at": [
        -2,
        0,
        6
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        0,
        0,
        6
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        2,
        0,
        6
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        4,
        0,
        6
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        6,
        0,
        6
      ]
    },
    {
      "asset": "desert-ground",
      "at": [
        8,
        0,
        6
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        10,
        0,
        6
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        -10,
        0,
        8
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        -8,
        0,
        8
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        -6,
        0,
        8
      ]
    },
    {
      "asset": "desert-ground",
      "at": [
        -4,
        0,
        8
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        -2,
        0,
        8
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        0,
        0,
        8
      ]
    },
    {
      "asset": "desert-ground",
      "at": [
        2,
        0,
        8
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        4,
        0,
        8
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        6,
        0,
        8
      ]
    },
    {
      "asset": "sea-water",
      "at": [
        8,
        0,
        8
      ]
    },
    {
      "asset": "desert-ground",
      "at": [
        10,
        0,
        8
      ]
    },
    {
      "asset": "boulder",
      "at": [
        -7.6,
        0,
        -3.6
      ],
      "yaw": 30,
      "scale": 1.7
    },
    {
      "asset": "boulder",
      "at": [
        -4.4,
        0,
        -6.2
      ],
      "yaw": 200,
      "scale": 1.8
    },
    {
      "asset": "boulder",
      "at": [
        -9.2,
        0,
        -6.6
      ],
      "yaw": 100,
      "scale": 1.4
    },
    {
      "asset": "boulder",
      "at": [
        -1.6,
        0,
        -7.6
      ],
      "yaw": 300,
      "scale": 1.3
    },
    {
      "asset": "rock-cluster",
      "at": [
        -5.8,
        0,
        -3.4
      ],
      "yaw": 60,
      "scale": 1.1
    },
    {
      "asset": "rock-cluster",
      "at": [
        -2.2,
        0,
        -6
      ],
      "yaw": 160
    },
    {
      "asset": "shell",
      "at": [
        -7.6,
        1.4,
        -3.6
      ],
      "yaw": 20,
      "scale": 2.2
    },
    {
      "asset": "shell",
      "at": [
        -4.4,
        1.5,
        -6.2
      ],
      "yaw": 200,
      "scale": 2.2
    },
    {
      "asset": "rowboat",
      "at": [
        -3.6,
        0,
        -1.2
      ],
      "yaw": 55,
      "scale": 0.9
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -2,
        0,
        -8
      ],
      "yaw": 104,
      "scale": 0.9684407387713161
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -2.093382274257999,
        0,
        -8.703644852871458
      ],
      "yaw": 118,
      "scale": 1.4016424144625863
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        0,
        0,
        -8
      ],
      "yaw": 246,
      "scale": 1.3087316835805456
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        0.25207889392505123,
        0,
        -8.569287953938991
      ],
      "yaw": 134,
      "scale": 1.3663210826769103
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -0.18274541750816456,
        0,
        -8.53586217282093
      ],
      "yaw": 246,
      "scale": 1.1743165301039427
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        0.6988169104850623,
        0,
        -8.373191272150832
      ],
      "yaw": 44,
      "scale": 1.2104443704758048
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        8,
        0,
        -8
      ],
      "yaw": 231,
      "scale": 1.2619461888735863
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        8.698673117602825,
        0,
        -8.43400752671826
      ],
      "yaw": 134,
      "scale": 1.068309022238622
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        8.336828310305831,
        0,
        -8.55554020296684
      ],
      "yaw": 55,
      "scale": 1.0381116663283259
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        7.425321411181043,
        0,
        -7.721830499207011
      ],
      "yaw": 336,
      "scale": 1.2458965560635071
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -2,
        0,
        -6
      ],
      "yaw": 21,
      "scale": 1.0187926759099555
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -2.652734929764398,
        0,
        -6.260078024455705
      ],
      "yaw": 151,
      "scale": 0.9543599200222455
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -1.5245831996976054,
        0,
        -6.307993952465532
      ],
      "yaw": 131,
      "scale": 1.0752978840262155
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -2.425222677730141,
        0,
        -6.709660613315748
      ],
      "yaw": 185,
      "scale": 0.9324403223267014
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        6,
        0,
        -6
      ],
      "yaw": 131,
      "scale": 1.139160234266501
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        5.648848521991847,
        0,
        -5.383493581911555
      ],
      "yaw": 220,
      "scale": 0.986584470507961
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        6.570995668091745,
        0,
        -6.3826426493453905
      ],
      "yaw": 310,
      "scale": 1.3081042113285997
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -2,
        0,
        -4
      ],
      "yaw": 181,
      "scale": 1.351196028921379
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -1.3793725380760844,
        0,
        -4.249809531971398
      ],
      "yaw": 254,
      "scale": 1.00089661972639
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -2.5606371793738627,
        0,
        -4.339031006550604
      ],
      "yaw": 119,
      "scale": 1.1131454618243248
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -10,
        0,
        0
      ],
      "yaw": 40,
      "scale": 1.455349686674471
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -9.406449964949108,
        0,
        0.31517883851178835
      ],
      "yaw": 55,
      "scale": 0.8623071912966237
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -9.384223152200574,
        0,
        -0.016640459184809317
      ],
      "yaw": 227,
      "scale": 0.9154022541434516
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -10.701317361801578,
        0,
        0.19482208728070466
      ],
      "yaw": 49,
      "scale": 1.5374967366165933
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -8,
        0,
        0
      ],
      "yaw": 318,
      "scale": 1.5262098472221801
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -7.9573340551343374,
        0,
        -0.6311860839430313
      ],
      "yaw": 4,
      "scale": 0.9986351420165204
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -7.51110504860863,
        0,
        0.2529912355373045
      ],
      "yaw": 221,
      "scale": 0.9851010245201649
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -8.040374111194328,
        0,
        -0.6956375984667261
      ],
      "yaw": 247,
      "scale": 0.9904388450972917
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -6,
        0,
        0
      ],
      "yaw": 134,
      "scale": 1.5154218300783178
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -5.487042316736665,
        0,
        0.47156574190281114
      ],
      "yaw": 1,
      "scale": 1.530392666501176
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -6.540365304782365,
        0,
        -0.6255644994743341
      ],
      "yaw": 8,
      "scale": 1.520042274482568
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -5.680938564672924,
        0,
        0.7777169857599345
      ],
      "yaw": 203,
      "scale": 1.3435005067584573
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        8,
        0,
        0
      ],
      "yaw": 75,
      "scale": 1.2515286414192657
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        8.73901638974794,
        0,
        0.2520826372030494
      ],
      "yaw": 252,
      "scale": 1.3712618878908744
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        10,
        0,
        0
      ],
      "yaw": 40,
      "scale": 1.5352236929979286
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        10.515353970787025,
        0,
        0.5536140524630725
      ],
      "yaw": 321,
      "scale": 0.8296487480540056
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        10.598567363605735,
        0,
        -0.5433635347182884
      ],
      "yaw": 356,
      "scale": 1.56343261188056
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -10,
        0,
        2
      ],
      "yaw": 89,
      "scale": 1.3821327882735677
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -9.506900718963095,
        0,
        1.547153317309274
      ],
      "yaw": 84,
      "scale": 1.1239072760212736
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -9.457142266891275,
        0,
        1.5306361758941431
      ],
      "yaw": 126,
      "scale": 1.2972087769290475
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -10.063172011326554,
        0,
        1.35256785977676
      ],
      "yaw": 260,
      "scale": 1.1382018742795112
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -8,
        0,
        2
      ],
      "yaw": 354,
      "scale": 1.5953177798517597
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -8.547812088871185,
        0,
        1.4010929879129153
      ],
      "yaw": 330,
      "scale": 0.9596308783440064
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -6,
        0,
        2
      ],
      "yaw": 179,
      "scale": 1.2458985613872757
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -5.890256482495545,
        0,
        1.1735246351192115
      ],
      "yaw": 173,
      "scale": 0.9497207910519656
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -6.56618729735049,
        0,
        2.198061605589201
      ],
      "yaw": 238,
      "scale": 1.2173766417509768
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -10,
        0,
        4
      ],
      "yaw": 272,
      "scale": 1.089962557465752
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -9.998252879837903,
        0,
        3.442197080676334
      ],
      "yaw": 107,
      "scale": 1.2333529008707744
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -9.775213102707966,
        0,
        4.733194671636425
      ],
      "yaw": 104,
      "scale": 0.9885718841983806
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        0,
        0,
        4
      ],
      "yaw": 27,
      "scale": 1.418305366401703
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        0.3625525474896245,
        0,
        3.2593402790737627
      ],
      "yaw": 327,
      "scale": 1.3447234551164897
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        0.5386273087509992,
        0,
        3.855922708385085
      ],
      "yaw": 274,
      "scale": 1.2808341304216695
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -6,
        0,
        6
      ],
      "yaw": 13,
      "scale": 0.9087680262088628
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -5.48998344412632,
        0,
        6.281344208430182
      ],
      "yaw": 30,
      "scale": 0.8075970746612163
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -6.659619717826605,
        0,
        5.490099653856935
      ],
      "yaw": 69,
      "scale": 0.9069174614301498
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -5.777004672393806,
        0,
        6.718672059680359
      ],
      "yaw": 87,
      "scale": 1.1650856884033818
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -2,
        0,
        6
      ],
      "yaw": 242,
      "scale": 1.4194750703030616
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -2.537642257268799,
        0,
        6.408010908979505
      ],
      "yaw": 22,
      "scale": 0.984104605849881
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -1.703608294890616,
        0,
        5.211560245018282
      ],
      "yaw": 55,
      "scale": 1.5404299981614715
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -2.5858194224348017,
        0,
        5.968808919094518
      ],
      "yaw": 75,
      "scale": 1.2820929626385185
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        8,
        0,
        6
      ],
      "yaw": 98,
      "scale": 1.3172395362133344
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        7.348077098845699,
        0,
        5.761471125554319
      ],
      "yaw": 357,
      "scale": 0.8601850856375811
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -4,
        0,
        8
      ],
      "yaw": 1,
      "scale": 0.8049223996721778
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -4.493742090192441,
        0,
        8.299355183734415
      ],
      "yaw": 84,
      "scale": 1.5392528094068416
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -3.868132334807325,
        0,
        7.232059474983151
      ],
      "yaw": 157,
      "scale": 1.483951327150665
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        2,
        0,
        8
      ],
      "yaw": 238,
      "scale": 1.257730613862039
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        1.6123041707997954,
        0,
        8.549009567201788
      ],
      "yaw": 178,
      "scale": 1.1958620777334377
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        1.3006673268852569,
        0,
        7.686152564182399
      ],
      "yaw": 239,
      "scale": 1.3062523460510431
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        1.890725954687583,
        0,
        7.192004722726381
      ],
      "yaw": 303,
      "scale": 1.5905962068543753
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        10,
        0,
        8
      ],
      "yaw": 344,
      "scale": 1.580072958758135
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        9.641002438478639,
        0,
        8.447577888252502
      ],
      "yaw": 123,
      "scale": 1.5061204678873161
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        9.798876831095024,
        0,
        7.255254615563647
      ],
      "yaw": 343,
      "scale": 1.4296046680908674
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -4.2,
        0,
        0.4
      ],
      "yaw": 287,
      "scale": 0.8832946062475884
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -3.5197275976071625,
        0,
        -0.0017649333276176238
      ],
      "yaw": 228,
      "scale": 1.3691693163333318
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -8,
        0,
        -1.2
      ],
      "yaw": 313,
      "scale": 1.2507109513742436
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -7.558607115387523,
        0,
        -1.6511696293217017
      ],
      "yaw": 247,
      "scale": 1.1472074771054124
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -8.478765236684868,
        0,
        -0.8280740718078397
      ],
      "yaw": 211,
      "scale": 0.9851561297593434
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -2.4,
        0,
        -2.6
      ],
      "yaw": 121,
      "scale": 1.3462903494696554
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -1.9815047469207925,
        0,
        -3.008442814925538
      ],
      "yaw": 110,
      "scale": 1.5367407064590328
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -1.8104759695329111,
        0,
        -2.5951247390378906
      ],
      "yaw": 143,
      "scale": 0.8172638952812478
    },
    {
      "asset": "coral-reef-cluster",
      "at": [
        -2.689579343362208,
        0,
        -3.366476780271303
      ],
      "yaw": 62,
      "scale": 0.9696410936162068
    },
    {
      "asset": "shipwreck-hull",
      "at": [
        5,
        -0.03,
        -2.4
      ],
      "yaw": 215,
      "scale": 0.8
    },
    {
      "asset": "treasure-chest",
      "at": [
        2.6,
        -0.03,
        1.8
      ],
      "yaw": 25,
      "scale": 1.2
    },
    {
      "asset": "chest",
      "at": [
        1.4,
        -0.03,
        3.2
      ],
      "yaw": 300
    },
    {
      "asset": "shell",
      "at": [
        4.4,
        -0.03,
        4.6
      ],
      "yaw": 160,
      "scale": 4.5
    },
    {
      "asset": "giant-crystal",
      "at": [
        4.4,
        0.4,
        4.6
      ],
      "scale": 0.12
    },
    {
      "asset": "barrel",
      "at": [
        7,
        -0.03,
        2.6
      ],
      "yaw": 60
    },
    {
      "asset": "crate",
      "at": [
        0.2,
        -0.03,
        -3
      ],
      "yaw": 20
    },
    {
      "asset": "reeds",
      "at": [
        8.946510189653612,
        -0.03,
        3.1974060066032255
      ],
      "yaw": 63,
      "scale": 0.8584169270277102
    },
    {
      "asset": "reeds",
      "at": [
        2.5317021890225355,
        -0.03,
        -7.745047278583537
      ],
      "yaw": 291,
      "scale": 1.0957919653485493
    },
    {
      "asset": "reeds",
      "at": [
        5.022464522636712,
        -0.03,
        -5.951014435827274
      ],
      "yaw": 119,
      "scale": 1.1574092655244326
    },
    {
      "asset": "reeds",
      "at": [
        9.101026765583562,
        -0.03,
        0.7654793303299137
      ],
      "yaw": 211,
      "scale": 1.1887279850378298
    },
    {
      "asset": "reeds",
      "at": [
        4.04978123216414,
        -0.03,
        3.7385351861540865
      ],
      "yaw": 215,
      "scale": 0.8501292727655402
    },
    {
      "asset": "reeds",
      "at": [
        -5.502372652060526,
        -0.03,
        1.2982694549943652
      ],
      "yaw": 90,
      "scale": 0.9115196054389326
    },
    {
      "asset": "reeds",
      "at": [
        2.4003444856034335,
        -0.03,
        2.0718156295231616
      ],
      "yaw": 292,
      "scale": 0.9197389634883679
    },
    {
      "asset": "reeds",
      "at": [
        8.110373959927994,
        -0.03,
        -7.155884392166456
      ],
      "yaw": 248,
      "scale": 1.0033614556786425
    },
    {
      "asset": "reeds",
      "at": [
        5.839423637762398,
        -0.03,
        2.5544638980899297
      ],
      "yaw": 289,
      "scale": 0.8523269907815042
    },
    {
      "asset": "reeds",
      "at": [
        8.389362589637454,
        -0.03,
        0.01363522932568273
      ],
      "yaw": 295,
      "scale": 1.0124670165183336
    },
    {
      "asset": "reeds",
      "at": [
        7.325864945224424,
        -0.03,
        4.649707509507289
      ],
      "yaw": 261,
      "scale": 1.25391379085086
    },
    {
      "asset": "reeds",
      "at": [
        7.163313216140175,
        -0.03,
        -4.955821065677247
      ],
      "yaw": 258,
      "scale": 0.8772929506270648
    },
    {
      "asset": "reeds",
      "at": [
        -7.495152436893039,
        -0.03,
        7.178394510959459
      ],
      "yaw": 343,
      "scale": 0.8282345733271141
    },
    {
      "asset": "reeds",
      "at": [
        8.814624566032844,
        -0.03,
        5.916065051181272
      ],
      "yaw": 343,
      "scale": 0.9385196124382874
    },
    {
      "asset": "reeds",
      "at": [
        -0.6032493387364077,
        -0.03,
        0.9506910857514903
      ],
      "yaw": 51,
      "scale": 0.9615541424423243
    },
    {
      "asset": "reeds",
      "at": [
        -0.38111887424305024,
        -0.03,
        -4.3719355223569725
      ],
      "yaw": 20,
      "scale": 0.8221959157018903
    },
    {
      "asset": "reeds",
      "at": [
        -0.6410327137638969,
        -0.03,
        4.9305438161504185
      ],
      "yaw": 261,
      "scale": 1.055390622539162
    },
    {
      "asset": "reeds",
      "at": [
        4.007720627825577,
        -0.03,
        -1.7915265084204854
      ],
      "yaw": 220,
      "scale": 1.282619462992353
    },
    {
      "asset": "reeds",
      "at": [
        5.412580499151991,
        -0.03,
        7.392359398022462
      ],
      "yaw": 255,
      "scale": 1.101683902880961
    },
    {
      "asset": "reeds",
      "at": [
        6.054228812481384,
        -0.03,
        -5.261078900313507
      ],
      "yaw": 23,
      "scale": 1.1632904956411991
    },
    {
      "asset": "reeds",
      "at": [
        2.934409665378933,
        -0.03,
        -1.101403181022686
      ],
      "yaw": 196,
      "scale": 0.9934757673616874
    },
    {
      "asset": "river-rock",
      "at": [
        -9.020000808043406,
        -0.06,
        -7.07019986522859
      ],
      "yaw": 127,
      "scale": 0.5378520886124355
    },
    {
      "asset": "stepping-stone",
      "at": [
        -6.23722792148461,
        -0.06,
        2.350645991205539
      ],
      "yaw": 45,
      "scale": 0.42087229360866935
    },
    {
      "asset": "stepping-stone",
      "at": [
        -10.366788592919143,
        -0.06,
        5.641019037198749
      ],
      "yaw": 312,
      "scale": 0.41777278874897067
    },
    {
      "asset": "stepping-stone",
      "at": [
        -2.031600513882749,
        -0.06,
        6.857439485591575
      ],
      "yaw": 286,
      "scale": 0.40464076511777974
    },
    {
      "asset": "stepping-stone",
      "at": [
        10.261645395244306,
        -0.06,
        -4.947795565681437
      ],
      "yaw": 231,
      "scale": 0.571024768506654
    },
    {
      "asset": "river-rock",
      "at": [
        -9.709216850674347,
        -0.06,
        -5.498453652252655
      ],
      "yaw": 271,
      "scale": 0.7015469533864163
    },
    {
      "asset": "stepping-stone",
      "at": [
        -5.218430594177186,
        -0.06,
        6.006810651722741
      ],
      "yaw": 292,
      "scale": 0.5271722313608845
    },
    {
      "asset": "stepping-stone",
      "at": [
        -0.8479909159466583,
        -0.06,
        -3.378838870198856
      ],
      "yaw": 91,
      "scale": 0.7526118887367714
    },
    {
      "asset": "river-rock",
      "at": [
        7.696727943651718,
        -0.06,
        2.9937510785617647
      ],
      "yaw": 179,
      "scale": 0.7466845901434704
    },
    {
      "asset": "stepping-stone",
      "at": [
        6.6511401479370615,
        -0.06,
        5.260068997768718
      ],
      "yaw": 273,
      "scale": 0.7881404494811504
    },
    {
      "asset": "stepping-stone",
      "at": [
        7.571094754511067,
        -0.06,
        -5.662295368529063
      ],
      "yaw": 303,
      "scale": 0.6634096744765573
    },
    {
      "asset": "river-rock",
      "at": [
        6.1511774579767025,
        -0.06,
        5.524240788595863
      ],
      "yaw": 15,
      "scale": 0.49272792325016485
    },
    {
      "asset": "stepping-stone",
      "at": [
        -6.3332845929699415,
        -0.06,
        -8.007585960071342
      ],
      "yaw": 207,
      "scale": 0.7247605681069011
    },
    {
      "asset": "stepping-stone",
      "at": [
        2.6451449797698956,
        -0.06,
        5.937891340226816
      ],
      "yaw": 311,
      "scale": 0.725369368645069
    },
    {
      "asset": "river-rock",
      "at": [
        -6.085101481007925,
        -0.06,
        1.0495224113806731
      ],
      "yaw": 165,
      "scale": 0.5544246614698436
    },
    {
      "asset": "stepping-stone",
      "at": [
        0.7948368303453712,
        -0.06,
        4.218259996463667
      ],
      "yaw": 186,
      "scale": 0.5535193594887478
    },
    {
      "asset": "stepping-stone",
      "at": [
        -0.006503776091385305,
        -0.06,
        -4.288010004855697
      ],
      "yaw": 252,
      "scale": 0.7086641849524641
    },
    {
      "asset": "river-rock",
      "at": [
        -4.214262204717035,
        -0.06,
        -4.123168010135725
      ],
      "yaw": 220,
      "scale": 0.6206684884711489
    },
    {
      "asset": "stepping-stone",
      "at": [
        9.11485819905757,
        -0.06,
        1.1483377989140973
      ],
      "yaw": 114,
      "scale": 0.6401040901616701
    },
    {
      "asset": "stepping-stone",
      "at": [
        1.5310540537960158,
        -0.06,
        2.282120197770242
      ],
      "yaw": 205,
      "scale": 0.4645971019121805
    },
    {
      "asset": "river-rock",
      "at": [
        -6.0584244231034186,
        -0.06,
        -6.412494657008208
      ],
      "yaw": 120,
      "scale": 0.6535818317223256
    },
    {
      "asset": "stepping-stone",
      "at": [
        7.791979370541862,
        -0.06,
        2.420880563008078
      ],
      "yaw": 140,
      "scale": 0.5389277842542752
    },
    {
      "asset": "stepping-stone",
      "at": [
        -2.1179619966624124,
        -0.06,
        -6.289724461869208
      ],
      "yaw": 56,
      "scale": 0.42124058009183063
    },
    {
      "asset": "river-rock",
      "at": [
        -0.4976606233500238,
        -0.06,
        -2.085539596940177
      ],
      "yaw": 33,
      "scale": 0.6536896200169295
    },
    {
      "asset": "stepping-stone",
      "at": [
        -2.0049315242119743,
        -0.06,
        -0.7141029247614101
      ],
      "yaw": 36,
      "scale": 0.7361045799851905
    },
    {
      "asset": "stepping-stone",
      "at": [
        -4.696857823010935,
        -0.06,
        -3.303002239997965
      ],
      "yaw": 44,
      "scale": 0.48116707060540426
    },
    {
      "asset": "river-rock",
      "at": [
        -1.3023054184868492,
        -0.06,
        -5.04578994915159
      ],
      "yaw": 218,
      "scale": 0.6312311289046105
    },
    {
      "asset": "stepping-stone",
      "at": [
        5.282341988981861,
        -0.06,
        4.782999430030118
      ],
      "yaw": 177,
      "scale": 0.7467765660708662
    },
    {
      "asset": "stepping-stone",
      "at": [
        3.834789558423118,
        -0.06,
        -6.374220124433851
      ],
      "yaw": 224,
      "scale": 0.6945175470293116
    },
    {
      "asset": "river-rock",
      "at": [
        8.133471925246281,
        -0.06,
        1.3429076884607358
      ],
      "yaw": 347,
      "scale": 0.5162371589412155
    },
    {
      "asset": "stepping-stone",
      "at": [
        10.292376900414181,
        -0.06,
        -7.771158827548455
      ],
      "yaw": 37,
      "scale": 0.5230881462446825
    },
    {
      "asset": "stepping-stone",
      "at": [
        7.408644587643744,
        -0.06,
        6.695433657567683
      ],
      "yaw": 260,
      "scale": 0.6186764852230794
    },
    {
      "asset": "river-rock",
      "at": [
        -5.4242684966997565,
        -0.06,
        0.5810344350435948
      ],
      "yaw": 279,
      "scale": 0.47420269757239275
    },
    {
      "asset": "stepping-stone",
      "at": [
        6.486381158645441,
        -0.06,
        3.0758000166508364
      ],
      "yaw": 209,
      "scale": 0.780420221565487
    },
    {
      "asset": "stepping-stone",
      "at": [
        -4.021479740748871,
        -0.06,
        -7.923463772760455
      ],
      "yaw": 264,
      "scale": 0.6058812192668586
    },
    {
      "asset": "river-rock",
      "at": [
        2.373915340739263,
        -0.06,
        3.226837226947227
      ],
      "yaw": 245,
      "scale": 0.4181997085074893
    },
    {
      "asset": "shell",
      "at": [
        4.125044268614166,
        -0.03,
        7.69521807865017
      ],
      "yaw": 304,
      "scale": 1.2758253660406105
    },
    {
      "asset": "shell",
      "at": [
        1.340772701120363,
        -0.03,
        -4.5065698160354835
      ],
      "yaw": 226,
      "scale": 1.1972277968177703
    },
    {
      "asset": "shell",
      "at": [
        7.25668212271141,
        -0.03,
        2.445149128532572
      ],
      "yaw": 351,
      "scale": 1.015441246524193
    },
    {
      "asset": "shell",
      "at": [
        4.886580917465771,
        -0.03,
        7.012383877771153
      ],
      "yaw": 205,
      "scale": 1.2356184126043779
    },
    {
      "asset": "shell",
      "at": [
        -1.0674927807727332,
        -0.03,
        -1.0809331578579418
      ],
      "yaw": 17,
      "scale": 1.1973253167687568
    },
    {
      "asset": "shell",
      "at": [
        5.617112356991093,
        -0.03,
        5.445907159450421
      ],
      "yaw": 31,
      "scale": 1.0142280129316394
    },
    {
      "asset": "shell",
      "at": [
        2.2918097732084846,
        -0.03,
        -1.2425133479957067
      ],
      "yaw": 114,
      "scale": 1.0029601501780376
    },
    {
      "asset": "shell",
      "at": [
        -1.3576068036992144,
        -0.03,
        2.1619601818555783
      ],
      "yaw": 181,
      "scale": 1.1805261116384185
    },
    {
      "asset": "shell",
      "at": [
        -1.3611912314599337,
        -0.03,
        1.9671782823126662
      ],
      "yaw": 322,
      "scale": 1.4616602422490996
    },
    {
      "asset": "shell",
      "at": [
        -0.751671982347812,
        -0.03,
        5.319194144252313
      ],
      "yaw": 352,
      "scale": 1.2539943570056904
    },
    {
      "asset": "shell",
      "at": [
        -1.9097658674743805,
        -0.03,
        2.0520522864777835
      ],
      "yaw": 19,
      "scale": 1.0005426202437573
    },
    {
      "asset": "boulder",
      "at": [
        -9.5,
        0,
        2.5
      ],
      "yaw": 10,
      "scale": 0.8522004813664594
    },
    {
      "asset": "boulder",
      "at": [
        -5,
        0,
        6.5
      ],
      "yaw": 40,
      "scale": 0.6719105087555528
    },
    {
      "asset": "boulder",
      "at": [
        9.6,
        0,
        -4
      ],
      "yaw": 239,
      "scale": 0.6664414627786919
    }
  ];
}
