// GENERATED by scripts/design-general-store.mjs — edit the generator, not this file.
import type { Place } from '../chibi-quest.js';
export function places(): Place[] {
  return [
  {
    asset: 'wood-floor',
    at: [
      -4,
      0,
      -3
    ]
  },
  {
    asset: 'wood-floor',
    at: [
      -4,
      0,
      -1
    ]
  },
  {
    asset: 'wood-floor',
    at: [
      -4,
      0,
      1
    ]
  },
  {
    asset: 'wood-floor',
    at: [
      -4,
      0,
      3
    ]
  },
  {
    asset: 'wood-floor',
    at: [
      -2,
      0,
      -3
    ]
  },
  {
    asset: 'wood-floor',
    at: [
      -2,
      0,
      -1
    ]
  },
  {
    asset: 'wood-floor',
    at: [
      -2,
      0,
      1
    ]
  },
  {
    asset: 'wood-floor',
    at: [
      -2,
      0,
      3
    ]
  },
  {
    asset: 'wood-floor',
    at: [
      0,
      0,
      -3
    ]
  },
  {
    asset: 'wood-floor',
    at: [
      0,
      0,
      -1
    ]
  },
  {
    asset: 'wood-floor',
    at: [
      0,
      0,
      1
    ]
  },
  {
    asset: 'wood-floor',
    at: [
      0,
      0,
      3
    ]
  },
  {
    asset: 'wood-floor',
    at: [
      2,
      0,
      -3
    ]
  },
  {
    asset: 'stone-floor',
    at: [
      2,
      0,
      -1
    ]
  },
  {
    asset: 'wood-floor',
    at: [
      2,
      0,
      1
    ]
  },
  {
    asset: 'wood-floor',
    at: [
      2,
      0,
      3
    ]
  },
  {
    asset: 'wood-floor',
    at: [
      4,
      0,
      -3
    ]
  },
  {
    asset: 'stone-floor',
    at: [
      4,
      0,
      -1
    ]
  },
  {
    asset: 'wood-floor',
    at: [
      4,
      0,
      1
    ]
  },
  {
    asset: 'wood-floor',
    at: [
      4,
      0,
      3
    ]
  },
  {
    asset: 'plaster-wall',
    at: [
      -4,
      0,
      -3.92
    ]
  },
  {
    asset: 'plaster-wall',
    at: [
      -2,
      0,
      -3.92
    ]
  },
  {
    asset: 'plaster-wall-window',
    at: [
      0,
      0,
      -3.92
    ]
  },
  {
    asset: 'plaster-wall',
    at: [
      2,
      0,
      -3.92
    ]
  },
  {
    asset: 'plaster-wall',
    at: [
      4,
      0,
      -3.92
    ]
  },
  {
    asset: 'plaster-wall',
    at: [
      -4.92,
      0,
      -3
    ],
    yaw: 90
  },
  {
    asset: 'plaster-wall',
    at: [
      -4.92,
      0,
      -1
    ],
    yaw: 90
  },
  {
    asset: 'plaster-wall',
    at: [
      -4.92,
      0,
      1
    ],
    yaw: 90
  },
  {
    asset: 'plaster-wall-door',
    at: [
      -4.92,
      0,
      3
    ],
    yaw: 90
  },
  {
    asset: 'curtain',
    at: [
      -0.55,
      0.1,
      -3.82
    ],
    scale: 0.7
  },
  {
    asset: 'curtain',
    at: [
      0.55,
      0.1,
      -3.82
    ],
    scale: 0.7
  },
  {
    asset: 'shelf',
    at: [
      -4,
      0,
      -3.91
    ]
  },
  {
    asset: 'pot',
    at: [
      -4.4,
      0.475,
      -3.754
    ],
    yaw: 270,
    scale: 0.45
  },
  {
    asset: 'sack',
    at: [
      -4.2,
      0.475,
      -3.753
    ],
    yaw: 180,
    scale: 0.45
  },
  {
    asset: 'bread',
    at: [
      -4,
      0.475,
      -3.744
    ],
    scale: 0.7
  },
  {
    asset: 'pot',
    at: [
      -3.8,
      0.475,
      -3.741
    ],
    yaw: 90,
    scale: 0.45
  },
  {
    asset: 'bread',
    at: [
      -3.6,
      0.475,
      -3.762
    ],
    yaw: 180,
    scale: 0.7
  },
  {
    asset: 'pot',
    at: [
      -4.4,
      0.805,
      -3.765
    ],
    yaw: 270,
    scale: 0.45
  },
  {
    asset: 'jar',
    at: [
      -4.2,
      0.805,
      -3.738
    ],
    yaw: 270,
    scale: 0.5
  },
  {
    asset: 'pot',
    at: [
      -4,
      0.805,
      -3.756
    ],
    yaw: 180,
    scale: 0.45
  },
  {
    asset: 'pot',
    at: [
      -3.8,
      0.805,
      -3.749
    ],
    yaw: 180,
    scale: 0.45
  },
  {
    asset: 'sack',
    at: [
      -3.6,
      0.805,
      -3.759
    ],
    yaw: 270,
    scale: 0.45
  },
  {
    asset: 'bottle',
    at: [
      -4.4,
      1.115,
      -3.76
    ]
  },
  {
    asset: 'bottle',
    at: [
      -4.2,
      1.115,
      -3.739
    ],
    yaw: 270
  },
  {
    asset: 'sack',
    at: [
      -4,
      1.115,
      -3.763
    ],
    scale: 0.45
  },
  {
    asset: 'jar',
    at: [
      -3.8,
      1.115,
      -3.75
    ],
    yaw: 90,
    scale: 0.5
  },
  {
    asset: 'sack',
    at: [
      -3.6,
      1.115,
      -3.763
    ],
    yaw: 90,
    scale: 0.45
  },
  {
    asset: 'shelf',
    at: [
      -2.65,
      0,
      -3.91
    ]
  },
  {
    asset: 'sack',
    at: [
      -3.05,
      0.475,
      -3.763
    ],
    scale: 0.45
  },
  {
    asset: 'pot',
    at: [
      -2.85,
      0.475,
      -3.755
    ],
    yaw: 270,
    scale: 0.45
  },
  {
    asset: 'jar',
    at: [
      -2.65,
      0.475,
      -3.739
    ],
    yaw: 270,
    scale: 0.5
  },
  {
    asset: 'bottle',
    at: [
      -2.45,
      0.475,
      -3.764
    ],
    yaw: 90
  },
  {
    asset: 'pot',
    at: [
      -2.25,
      0.475,
      -3.761
    ],
    scale: 0.45
  },
  {
    asset: 'jar',
    at: [
      -3.05,
      0.805,
      -3.761
    ],
    yaw: 270,
    scale: 0.5
  },
  {
    asset: 'jar',
    at: [
      -2.85,
      0.805,
      -3.75
    ],
    yaw: 180,
    scale: 0.5
  },
  {
    asset: 'jar',
    at: [
      -2.65,
      0.805,
      -3.765
    ],
    scale: 0.5
  },
  {
    asset: 'bottle',
    at: [
      -2.45,
      0.805,
      -3.761
    ],
    yaw: 180
  },
  {
    asset: 'pot',
    at: [
      -2.25,
      0.805,
      -3.738
    ],
    yaw: 90,
    scale: 0.45
  },
  {
    asset: 'sack',
    at: [
      -3.05,
      1.115,
      -3.747
    ],
    yaw: 270,
    scale: 0.45
  },
  {
    asset: 'sack',
    at: [
      -2.85,
      1.115,
      -3.74
    ],
    yaw: 270,
    scale: 0.45
  },
  {
    asset: 'jar',
    at: [
      -2.65,
      1.115,
      -3.736
    ],
    yaw: 90,
    scale: 0.5
  },
  {
    asset: 'pot',
    at: [
      -2.45,
      1.115,
      -3.76
    ],
    yaw: 270,
    scale: 0.45
  },
  {
    asset: 'pot',
    at: [
      -2.25,
      1.115,
      -3.743
    ],
    yaw: 90,
    scale: 0.45
  },
  {
    asset: 'shelf',
    at: [
      -1.3,
      0,
      -3.91
    ]
  },
  {
    asset: 'pot',
    at: [
      -1.7,
      0.475,
      -3.742
    ],
    yaw: 90,
    scale: 0.45
  },
  {
    asset: 'pot',
    at: [
      -1.5,
      0.475,
      -3.745
    ],
    scale: 0.45
  },
  {
    asset: 'bread',
    at: [
      -1.3,
      0.475,
      -3.736
    ],
    yaw: 270,
    scale: 0.7
  },
  {
    asset: 'pot',
    at: [
      -1.1,
      0.475,
      -3.752
    ],
    yaw: 90,
    scale: 0.45
  },
  {
    asset: 'bread',
    at: [
      -0.9,
      0.475,
      -3.757
    ],
    yaw: 90,
    scale: 0.7
  },
  {
    asset: 'pot',
    at: [
      -1.7,
      0.805,
      -3.751
    ],
    yaw: 90,
    scale: 0.45
  },
  {
    asset: 'jar',
    at: [
      -1.5,
      0.805,
      -3.739
    ],
    scale: 0.5
  },
  {
    asset: 'jar',
    at: [
      -1.3,
      0.805,
      -3.748
    ],
    yaw: 180,
    scale: 0.5
  },
  {
    asset: 'sack',
    at: [
      -1.1,
      0.805,
      -3.74
    ],
    scale: 0.45
  },
  {
    asset: 'bread',
    at: [
      -0.9,
      0.805,
      -3.76
    ],
    yaw: 90,
    scale: 0.7
  },
  {
    asset: 'bottle',
    at: [
      -1.7,
      1.115,
      -3.751
    ]
  },
  {
    asset: 'bottle',
    at: [
      -1.5,
      1.115,
      -3.75
    ],
    yaw: 90
  },
  {
    asset: 'jar',
    at: [
      -1.3,
      1.115,
      -3.751
    ],
    yaw: 180,
    scale: 0.5
  },
  {
    asset: 'bottle',
    at: [
      -1.1,
      1.115,
      -3.758
    ],
    yaw: 90
  },
  {
    asset: 'cheese',
    at: [
      -0.9,
      1.115,
      -3.76
    ],
    yaw: 270,
    scale: 0.7
  },
  {
    asset: 'shelf',
    at: [
      -4.74,
      0,
      -2.3
    ],
    yaw: 90
  },
  {
    asset: 'bottle',
    at: [
      -4.58,
      0.475,
      -2.7
    ],
    yaw: 180
  },
  {
    asset: 'jar',
    at: [
      -4.58,
      0.475,
      -2.5
    ],
    yaw: 90,
    scale: 0.5
  },
  {
    asset: 'bread',
    at: [
      -4.58,
      0.475,
      -2.3
    ],
    yaw: 180,
    scale: 0.7
  },
  {
    asset: 'jar',
    at: [
      -4.58,
      0.475,
      -2.1
    ],
    scale: 0.5
  },
  {
    asset: 'bottle',
    at: [
      -4.58,
      0.475,
      -1.9
    ],
    yaw: 90
  },
  {
    asset: 'bread',
    at: [
      -4.58,
      0.805,
      -2.7
    ],
    yaw: 90,
    scale: 0.7
  },
  {
    asset: 'pot',
    at: [
      -4.58,
      0.805,
      -2.5
    ],
    yaw: 180,
    scale: 0.45
  },
  {
    asset: 'bread',
    at: [
      -4.58,
      0.805,
      -2.3
    ],
    scale: 0.7
  },
  {
    asset: 'sack',
    at: [
      -4.58,
      0.805,
      -2.1
    ],
    yaw: 270,
    scale: 0.45
  },
  {
    asset: 'bottle',
    at: [
      -4.58,
      0.805,
      -1.9
    ],
    yaw: 90
  },
  {
    asset: 'jar',
    at: [
      -4.58,
      1.115,
      -2.7
    ],
    yaw: 90,
    scale: 0.5
  },
  {
    asset: 'bottle',
    at: [
      -4.58,
      1.115,
      -2.5
    ],
    yaw: 270
  },
  {
    asset: 'jar',
    at: [
      -4.58,
      1.115,
      -2.3
    ],
    yaw: 180,
    scale: 0.5
  },
  {
    asset: 'bread',
    at: [
      -4.58,
      1.115,
      -2.1
    ],
    yaw: 180,
    scale: 0.7
  },
  {
    asset: 'bottle',
    at: [
      -4.58,
      1.115,
      -1.9
    ],
    yaw: 270
  },
  {
    asset: 'shelf',
    at: [
      -4.74,
      0,
      -0.95
    ],
    yaw: 90
  },
  {
    asset: 'bottle',
    at: [
      -4.58,
      0.475,
      -1.35
    ],
    yaw: 90
  },
  {
    asset: 'bottle',
    at: [
      -4.58,
      0.475,
      -1.15
    ],
    yaw: 90
  },
  {
    asset: 'bottle',
    at: [
      -4.58,
      0.475,
      -0.95
    ],
    yaw: 180
  },
  {
    asset: 'sack',
    at: [
      -4.58,
      0.475,
      -0.75
    ],
    yaw: 180,
    scale: 0.45
  },
  {
    asset: 'pot',
    at: [
      -4.58,
      0.475,
      -0.55
    ],
    scale: 0.45
  },
  {
    asset: 'pot',
    at: [
      -4.58,
      0.805,
      -1.35
    ],
    yaw: 270,
    scale: 0.45
  },
  {
    asset: 'pot',
    at: [
      -4.58,
      0.805,
      -1.15
    ],
    yaw: 90,
    scale: 0.45
  },
  {
    asset: 'sack',
    at: [
      -4.58,
      0.805,
      -0.95
    ],
    scale: 0.45
  },
  {
    asset: 'jar',
    at: [
      -4.58,
      0.805,
      -0.75
    ],
    yaw: 270,
    scale: 0.5
  },
  {
    asset: 'jar',
    at: [
      -4.58,
      0.805,
      -0.55
    ],
    scale: 0.5
  },
  {
    asset: 'bread',
    at: [
      -4.58,
      1.115,
      -1.35
    ],
    yaw: 90,
    scale: 0.7
  },
  {
    asset: 'cheese',
    at: [
      -4.58,
      1.115,
      -1.15
    ],
    yaw: 270,
    scale: 0.7
  },
  {
    asset: 'jar',
    at: [
      -4.58,
      1.115,
      -0.95
    ],
    yaw: 180,
    scale: 0.5
  },
  {
    asset: 'bread',
    at: [
      -4.58,
      1.115,
      -0.75
    ],
    yaw: 270,
    scale: 0.7
  },
  {
    asset: 'pot',
    at: [
      -4.58,
      1.115,
      -0.55
    ],
    scale: 0.45
  },
  {
    asset: 'ladder',
    at: [
      -3.4,
      0,
      -3.45
    ]
  },
  {
    asset: 'lantern',
    at: [
      -0.1,
      0,
      -3.5
    ],
    scale: 0.9
  },
  {
    asset: 'counter',
    at: [
      2.6,
      0,
      -2.5
    ]
  },
  {
    asset: 'counter',
    at: [
      4.4,
      0,
      -2.5
    ]
  },
  {
    asset: 'counter',
    at: [
      4.45,
      0,
      -0.5
    ],
    yaw: 90
  },
  {
    asset: 'cupboard',
    at: [
      2,
      0,
      -3.65
    ]
  },
  {
    asset: 'cupboard',
    at: [
      3,
      0,
      -3.65
    ]
  },
  {
    asset: 'shopkeeper',
    at: [
      3.4,
      0,
      -3.3
    ]
  },
  {
    asset: 'cash-box',
    at: [
      2.2,
      0.75,
      -2.5
    ]
  },
  {
    asset: 'scales',
    at: [
      3.1,
      0.75,
      -2.5
    ]
  },
  {
    asset: 'bread',
    at: [
      3.7,
      0.75,
      -2.5
    ],
    yaw: 20,
    scale: 0.7
  },
  {
    asset: 'cheese',
    at: [
      4.2,
      0.75,
      -2.45
    ],
    scale: 0.7
  },
  {
    asset: 'fruit-basket',
    at: [
      4.45,
      0.75,
      -0.6
    ],
    scale: 0.8
  },
  {
    asset: 'mug',
    at: [
      4.45,
      0.75,
      -0.1
    ]
  },
  {
    asset: 'awning',
    at: [
      2.6,
      1.1,
      -2.9
    ]
  },
  {
    asset: 'awning',
    at: [
      4.4,
      1.1,
      -2.9
    ]
  },
  {
    asset: 'rug',
    at: [
      3.4,
      0,
      -1.2
    ],
    scale: 1.4
  },
  {
    asset: 'jar',
    at: [
      2,
      1.4,
      -3.68
    ],
    scale: 0.5
  },
  {
    asset: 'bottle',
    at: [
      3,
      1.4,
      -3.68
    ],
    scale: 0.5
  },
  {
    asset: 'lantern',
    at: [
      4.65,
      0,
      -3.65
    ],
    scale: 0.9
  },
  {
    asset: 'barrel',
    at: [
      -4.3,
      0,
      1
    ]
  },
  {
    asset: 'barrel',
    at: [
      -4.3,
      0,
      1.9
    ],
    yaw: 60
  },
  {
    asset: 'barrel',
    at: [
      -3.45,
      0,
      1.45
    ]
  },
  {
    asset: 'apple',
    at: [
      -4.4,
      0.88,
      0.9
    ],
    yaw: 180,
    scale: 0.8
  },
  {
    asset: 'apple',
    at: [
      -4.18,
      0.88,
      0.95
    ],
    yaw: 180,
    scale: 0.8
  },
  {
    asset: 'apple',
    at: [
      -4.3,
      0.88,
      1.14
    ],
    scale: 0.8
  },
  {
    asset: 'cabbage',
    at: [
      -4.4,
      0.88,
      1.8
    ],
    yaw: 90,
    scale: 0.6
  },
  {
    asset: 'cabbage',
    at: [
      -4.18,
      0.88,
      1.85
    ],
    yaw: 270,
    scale: 0.6
  },
  {
    asset: 'cabbage',
    at: [
      -4.3,
      0.88,
      2.04
    ],
    yaw: 90,
    scale: 0.6
  },
  {
    asset: 'pumpkin',
    at: [
      -3.55,
      0.88,
      1.35
    ],
    yaw: 180,
    scale: 0.6
  },
  {
    asset: 'pumpkin',
    at: [
      -3.33,
      0.88,
      1.4
    ],
    scale: 0.6
  },
  {
    asset: 'pumpkin',
    at: [
      -3.45,
      0.88,
      1.59
    ],
    scale: 0.6
  },
  {
    asset: 'basket',
    at: [
      -4.5,
      0,
      2.9
    ],
    yaw: 90
  },
  {
    asset: 'apple',
    at: [
      -4.5,
      0.3,
      2.9
    ],
    scale: 0.8
  },
  {
    asset: 'basket',
    at: [
      -3.8,
      0,
      3.4
    ],
    yaw: 20
  },
  {
    asset: 'cabbage',
    at: [
      -3.8,
      0.3,
      3.4
    ],
    scale: 0.7
  },
  {
    asset: 'basket',
    at: [
      -2.9,
      0,
      3.5
    ]
  },
  {
    asset: 'pumpkin',
    at: [
      -2.9,
      0.3,
      3.5
    ],
    scale: 0.7
  },
  {
    asset: 'sack',
    at: [
      -4.5,
      0,
      3.7
    ],
    yaw: 20
  },
  {
    asset: 'sack',
    at: [
      -3.2,
      0,
      2.6
    ],
    yaw: 70
  },
  {
    asset: 'sack',
    at: [
      -2.5,
      0,
      2.9
    ],
    yaw: 20
  },
  {
    asset: 'crate',
    at: [
      -2.4,
      0,
      3.7
    ]
  },
  {
    asset: 'crate',
    at: [
      -1.7,
      0,
      3.7
    ],
    yaw: 10
  },
  {
    asset: 'apple',
    at: [
      -1.7,
      0.41,
      3.7
    ],
    scale: 0.8
  },
  {
    asset: 'fruit-basket',
    at: [
      -4.7,
      0,
      0
    ],
    yaw: 90
  },
  {
    asset: 'workbench',
    at: [
      3.8,
      0,
      3.4
    ]
  },
  {
    asset: 'shovel',
    at: [
      3.4,
      0.9,
      3.4
    ],
    yaw: 90
  },
  {
    asset: 'pickaxe',
    at: [
      3.8,
      0.9,
      3.4
    ],
    yaw: 90
  },
  {
    asset: 'axe',
    at: [
      4.2,
      0.9,
      3.4
    ],
    yaw: 90
  },
  {
    asset: 'rope-coil',
    at: [
      2.4,
      0,
      3.6
    ],
    yaw: 20
  },
  {
    asset: 'rope-coil',
    at: [
      2.4,
      0.12,
      3.6
    ],
    yaw: 100
  },
  {
    asset: 'rope-coil',
    at: [
      2,
      0,
      3.4
    ],
    yaw: 60
  },
  {
    asset: 'bucket',
    at: [
      4.6,
      0,
      2.2
    ]
  },
  {
    asset: 'bucket',
    at: [
      4.5,
      0,
      2.7
    ],
    yaw: 90
  },
  {
    asset: 'barrel',
    at: [
      4.6,
      0,
      1.3
    ]
  },
  {
    asset: 'crate',
    at: [
      1.4,
      0,
      3.7
    ]
  },
  {
    asset: 'crate',
    at: [
      1.4,
      0.41,
      3.7
    ],
    yaw: 30
  },
  {
    asset: 'sack',
    at: [
      0.9,
      0,
      3.6
    ],
    yaw: 70
  },
  {
    asset: 'rug',
    at: [
      -0.4,
      0,
      0
    ],
    scale: 1.4
  },
  {
    asset: 'table',
    at: [
      -0.4,
      0.04,
      0
    ]
  },
  {
    asset: 'fruit-basket',
    at: [
      -0.65,
      0.64,
      -0.05
    ],
    scale: 0.8
  },
  {
    asset: 'bread',
    at: [
      -0.2,
      0.64,
      0.2
    ],
    yaw: 20,
    scale: 0.7
  },
  {
    asset: 'cheese',
    at: [
      -0.15,
      0.64,
      -0.15
    ],
    scale: 0.7
  },
  {
    asset: 'stool',
    at: [
      -1.4,
      0,
      0
    ]
  },
  {
    asset: 'stool',
    at: [
      0.6,
      0,
      0
    ]
  },
  {
    asset: 'crate',
    at: [
      1.2,
      0,
      1.2
    ],
    yaw: 15
  },
  {
    asset: 'crate',
    at: [
      1.25,
      0.41,
      1.2
    ],
    yaw: 40
  },
  {
    asset: 'pumpkin',
    at: [
      1.25,
      0.82,
      1.2
    ],
    scale: 0.8
  },
  {
    asset: 'barrel',
    at: [
      1.9,
      0,
      1.4
    ]
  },
  {
    asset: 'apple',
    at: [
      1.8,
      0.88,
      1.35
    ],
    scale: 0.8
  },
  {
    asset: 'apple',
    at: [
      2,
      0.88,
      1.45
    ],
    scale: 0.8
  }
];
}
