/** Generated by scripts/apk2d-pack.ts: the 2D camera of each baked background of labyrinth (backgrounds/<id>.png). */
import type { Projection2D } from '../../../apk3d/view2d/projection.js';

export const PROJECTIONS: Readonly<Record<string, Projection2D>> = {
  'labyrinth-1': {"elevation":45,"ppm":64,"uMin":-9.8,"vMax":6.508210845061064,"width":1254,"height":770},
  'labyrinth-2': {"elevation":45,"ppm":64,"uMin":-9.8,"vMax":6.508210845061064,"width":1254,"height":770},
  'labyrinth-3': {"elevation":45,"ppm":64,"uMin":-9.8,"vMax":6.508210845061064,"width":1254,"height":770},
};
