#!/usr/bin/env node
// Bank map generator: 14 m x 10 m cutaway hall, north and west walls standing.
import { writeFileSync } from 'node:fs';
const places = [];
const put = (asset, x, z, yaw = 0, o = {}) => {
  const p = { asset, at: [x, o.y ?? 0, z] };
  if (yaw) p.yaw = yaw;
  if (o.scale) p.scale = o.scale;
  places.push(p);
};
// Marble floor: 7 x 5 tiles of 2 m, x -6..6, z -4..4.
for (let c = 0; c < 7; c++) for (let r = 0; r < 5; r++) put(r === 0 && c < 4 ? 'stone-floor' : 'marble-floor', -6 + 2 * c, -4 + 2 * r);
// Rug runs from the door side to the counter.
put('rug', 2, 3.6, 0, { y: 0.01 });
put('rug', 3.6, 3.6, 0, { y: 0.01 });
// North wall (z=-5) and west wall (x=-7), windows.
const northWin = new Set([-4, -2, 0]);
for (let x = -6; x <= 6; x += 2) put(northWin.has(x) ? 'plaster-wall-window' : 'brick-wall', x, -5);
const westWin = new Set([-2, 2]);
for (let z = -4; z <= 4; z += 2) put(westWin.has(z) ? 'plaster-wall-window' : 'brick-wall', -7, z, 90);
put('wall-corner', -7, -5, 0);
for (const x of [-4, -2, 0]) put('wall-sconce', x + 0.8, -4.9, 0, { y: 1.0 });
for (const z of [-2, 2]) put('wall-sconce', -6.9, z + 0.8, 90, { y: 1.0 });
put('banner', -0.9, -4.5);
put('banner', 2.4, -4.5);
// Vault (focal): iron door in the north wall east end, flanked by pillars, strongboxes, coins.
put('iron-door', 5, -4.5, 0, { scale: 1.25 });
put('pillar', 3.2, -4.4);
put('pillar', 6.6, -4.4);
put('treasure-pile', 5, -2.7);
for (const [x, z] of [[2.6, -3.3], [6.6, -2.2], [5.6, -1.8], [4.4, -1.9]]) put('coin-pile', x, z, x * 40);
put('gold-pile', 3.1, -1.8);
put('gold-pile', 6.5, -1.0);
put('guard', 3.2, -0.6, 200);
// Teller counter along z=1.5 with a return end.
for (const x of [-5, -3, -1, 1]) put('counter', x, 1.5);
put('counter', 2.3, 2.5, 90);
for (const x of [-5.4, -3.4, -1.4, 0.6]) put('cash-box', x, 1.5, 0, { y: 0.75 });
for (const x of [-4.4, -2.4, -0.4, 1.4]) put('candle', x, 1.4, 0, { y: 0.75 });
put('coin-pile', -0.2, 1.5, 0, { y: 0.75, scale: 0.5 });
put('coin-pile', -5.8, 1.5, 0, { y: 0.75, scale: 0.5 });
// Clerks' side: desks, chairs, shelves, shopkeeper.
put('desk', -5.6, -3.4, 0);
put('chair', -5.6, -2.6, 180);
put('desk', -3.0, -3.8, 0);
put('chair', -3.0, -3.0, 180);
put('bookshelf', -6.6, -0.6, 90);
put('bookshelf', -6.6, 0.8, 90);
put('shopkeeper', -4.2, 0.4, 0);
put('cash-box', -5.8, -3.4, 0, { y: 0.75 });
put('scroll', -3.0, -3.8, 0, { y: 0.75 });
put('chest', -1.2, -3.8, 0);
put('column', -1.0, -1.2);
put('barrel', -6.4, -4.4);
put('crate', -6.4, -2.0);
// Customer side.
put('bench', -4, 4.2, 180);
put('bench', 0, 4.2, 180);
put('banner', -6.4, 3.0, 90);
put('banner', -6.5, -2.5, 90);
put('banner', 1.2, -4.6);
put('banner', 7.0 - 0.1, -1.5, 270);
put('villager', 0.6, 3.2, 150);
put('guard', 6.2, 3.8, 120);
put('table', 5.2, 1.6);
put('chair', 4.3, 1.6, 90);
put('chair', 6.1, 1.6, 270);
put('cash-box', 5.2, 1.6, 0, { y: 0.75 });
put('urn', 6.6, -0.1);
put('urn', -6.5, 4.4);
put('torch', 6.7, 4.4);
put('torch', 1.6, 4.5);
// Extra dressing: coin stacks, sacks, strongboxes, candles, curtains.
for (let i = 0; i < 8; i++) put('coin-pile', 3.4 + (i % 4) * 0.9, -3.7 + Math.floor(i / 4) * 0.7, i * 37, { scale: 0.8 });
for (const [x, z] of [[-6.4, -3.2], [-6.3, -1.2], [-1.8, -4.4]]) put('sack', x, z, x * 30);
for (const [x, z] of [[1.6, -3.9], [2.2, -3.4]]) put('chest', x, z, z * 40);
for (const [x, z] of [[-4.0, -2.2], [-5.2, -1.4]]) put('coin-pile', x, z, x * 50, { scale: 0.7 });
for (const x of [-6, -2, 0, 2, 4]) put('curtain', x + 1, -4.85, 0, { scale: 0.7 });
for (const [x, z] of [[-3, 4.6], [2, 4.6], [6.4, 4.4]]) put('banner', x, z, 180);
for (const [x, z] of [[-2.4, -3.8], [-5.0, -3.8], [3.7, -3.6], [5.2, -3.7]]) put('candle', x, z, 0, { y: 0.75 });
for (const [x, z] of [[2.4, 1.0], [-3.4, 3.8], [0.8, 1.9]]) put('stool', x, z);
put('column', 2.5, 4.2);
put('column', -6.4, 4.6);
put('column', 6.5, 4.6);
for (const [x, z, y] of [[-0.5, -2.2, 0], [4.6, 0.8, 90], [-5.0, 3.4, 0], [-1.5, 3.8, 90], [2.0, 3.0, 0]]) put('rug', x, z, y, { y: 0.01 });
put('treasure-chest', 6.3, -3.9);
// Chandeliers.
put('chandelier', -2, 2.2, 0, { y: 2.0 });
put('chandelier', 3.5, 0.5, 0, { y: 2.0 });
put('chandelier', -3.5, -2, 0, { y: 2.0 });
writeFileSync('scenes/maps/bank.ts', `// GENERATED by scripts/design-bank.mjs — edit the generator, not this file.
import type { Place } from '../chibi-quest.js';
export function places(): Place[] {
  return ${JSON.stringify(places)};
}
`);
const tally = {};
for (const p of places) tally[p.asset] = (tally[p.asset] ?? 0) + 1;
writeFileSync('docs/map-mockups/bank.md', `# Bank map (generated by scripts/design-bank.mjs)

14 m x 10 m marble hall, 7x5 stone-floor tiles, north and west plaster walls standing.
Zones: vault (north-east: iron door, strongboxes, coins, guard); teller counter along z=1.5
with clerk desks behind; customer floor with rug, benches, table.

Total placements: ${places.length}

Tally: ${JSON.stringify(tally)}
`);
console.log(places.length, JSON.stringify(tally));
