#!/usr/bin/env node
// Sewer map designer: 8 x 7 tiles of 2 m (16 x 14 m). Brick tunnels, green channel
// entering from the north at x=1, turning east at (1,0), plank walkways, props.
// Writes scenes/maps/sewer.ts and docs/map-mockups/sewer.md.
import { writeFileSync } from 'node:fs';
const P = [];
const add = (asset, x, z, yaw = 0, scale, y = 0) => P.push({ asset, at: [x, y, z], yaw, scale });
const cols = [-7, -5, -3, -1, 1, 3, 5, 7], rows = [-6, -4, -2, 0, 2, 4, 6];
// ground
for (const x of cols) for (const z of rows) {
  if ((x === -3 && z === -6) || (x === 1 && z < 0)) add('sewer-water', x, z);
  else if (x === 1 && z === 0) add('sewer-water', x, z);
  else if (x === 7 && z === 0) add('sewer-water', x, z);
  else if (x === 7 && z === 2) add('sewer-water', x, z);
  else if (x === 7 && z === 4) add('sewer-water', x, z);
  else if (z === 4 && x < 7) add('sewer-water', x, z);
  else if (z === 0 && x > 1) add('sewer-water', x, z);
  else add((x + z) % 7 === 0 ? 'floor-cracked' : 'floor', x, z);
}
// outer walls (north, west, east full; south low)
for (const x of cols) { add('brick-wall', x, -7, 0); add('brick-wall', x, 7, 0, 0.5); }
for (const z of rows) { add('brick-wall', -8, z, 90); if (z !== 2) add('brick-wall', 8, z, 90); }
// inner tunnel walls at z=-3 with gap at the channel (x 0..2)
for (const x of [-7, -5, -3, -1, 3, 5, 7]) add('brick-wall', x, -3, 0);
// divider between north bays at x=-4 and x=4
for (const z of [-6, -4]) { add('brick-wall', -4, z, 90); add('brick-wall', 4, z, 90); }

for (const x of cols) add('stone-wall', x, -7.18, 0);
for (const z of rows) { add('stone-wall', -8.18, z, 90); if (z !== 2) add('stone-wall', 8.18, z, 90); }
for (const x of [-7, -5, -3, -1, 3, 5, 7]) add('stone-wall', x, -2.82, 0);
for (const [x, z] of [[-7.5,-7],[-4,-7],[-1,-7],[3,-7],[6.5,-7],[8,-4],[8,2],[-8,-3],[-8,3],[-6,-3],[5,-3],[-4,-5],[4,-5]]) add('moss', x, z, x*30, 1, 1.5);
// walkways over the channel
add('walkway', 1, -4, 90); add('walkway', 4, 0, 0); add('walkway', 7, 2, 90); add('walkway', 3, 4, 0); add('walkway', -2, 4, 0);
// walkway along the south bank

// planks scattered on the walkway ends
add('plank', 2.4, -4, 0, 1, 0); add('plank', -0.4, -4, 0, 1, 0);
// grates / bars / door
add('iron-door', -6, -3, 0); add('cell-bars', -2, -3, 0);
add('cell-bars', 4.6, -3, 0);
add('stairs-stone', 6.2, -5.4, 0);
// torches on the inner wall faces (face +Z, south side) and outer north wall
for (const x of [-6, -2, 3, 6]) add('torch-sconce', x, -2.8, 0);
for (const x of [-6, -2, 2, 6]) add('torch-sconce', x, -6.8, 0);
add('torch-sconce', -7.8, 0, 90); add('torch-sconce', 7.8, -1.5, -90);
// lever at the sluice
add('lever', 2.4, -2.3, 0); add('lever', 5.4, 1.5, 0);
// barrels and crates
for (const [x, z, s] of [[-6.8, 1.0], [-6.2, 1.7], [-6.5, 5.5], [6.6, 6.0], [-6.8, 2.2]]) add('barrel', x, z, x * 40, s);
for (const [x, z] of [[-5.5, 5.6], [-4.6, 5.9], [5.2, 2.4], [-6.6, -5.6], [6.6, -6.0]]) add('crate', x, z, x * 31);
// rats
add('giant-rat', -4.5, 1.2, 40, 0.8); add('giant-rat', -1.5, 2.8, -120, 0.8); add('giant-rat', 4.5, 2.6, 160, 0.8);
add('giant-rat', -5.5, -4.6, 20, 0.8);
// bones
add('bone-pile', -6.2, -1.2, 30); add('bone-pile', 3.6, -5.4, 100); add('bone-pile', 3.6, 5.8, 0);
// moss on edges
const mossSpots = [[-7.4, -6.5], [-3.6, -6.6], [3.0, -6.6], [7.2, -6.5], [-7.4, 2.8], [5.0, 3.0], [-3, -2.6], [5.5, -2.6], [-1.2, 5.2], [2.4, 5.4], [5.5, 5.4], [-7.2, 6.2]];
mossSpots.forEach(([x, z], i) => add(i % 3 === 0 ? 'moss' : 'moss-tuft', x, z, i * 47));
for (const [x, z] of [[-1.6, -5.6], [0.2, -3], [2, 0.8], [3.2, -0.8], [-0.8, 0.6], [-3, 3.2], [0, 5.0], [3, 3.0]]) add('moss-tuft', x, z, x * 90);
// east exit: the walkway at (7,2) leads through an archway into a short corridor and up a stair
add('archway', 8, 2, 90);
add('floor', 9, 2); add('floor', 11, 2);
for (const x of [9, 11]) { add('brick-wall', x, 0.9, 0); add('brick-wall', x, 3.1, 0); }
add('stairs-stone', 10.8, 2, 270);
add('torch-sconce', 9.4, 1.1, 0); add('torch-sconce', 9.4, 2.9, 180);
// tidy: remove accidental junk entries
const out = P.filter((p) => p.asset);
const src = `// GENERATED by scripts/design-sewer.mjs — edit the generator, not this file.
import type { Place } from '../chibi-quest.js';
export function places(): Place[] {
  return [
${out.map((p) => `  { asset: '${p.asset}', at: [${p.at.map((n) => +n.toFixed(2)).join(', ')}]${p.yaw ? `, yaw: ${Math.round(p.yaw % 360)}` : ''}${p.scale ? `, scale: ${p.scale}` : ''} },`).join('\n')}
  ];
}
`;
writeFileSync('scenes/maps/sewer.ts', src);
const tally = {}; out.forEach((p) => (tally[p.asset] = (tally[p.asset] ?? 0) + 1));
writeFileSync('docs/map-mockups/sewer.md', `# Sewer map\n\n16 x 14 m. Channel enters from the north at x=1, turns east at (1,0). Plank walkways cross it. Tunnels north, rats, barrels, torches, moss.\n\nPieces: ${out.length}\n\n${Object.entries(tally).map(([k, v]) => `- ${k}: ${v}`).join('\n')}\n`);
console.log(out.length, 'pieces');
