#!/usr/bin/env node
// Flower meadow map designer: 24 m x 20 m, 12 x 10 tiles of 2 m.
// Cell (c,r): x=(c-6.5)*2, z=(r-5.5)*2. Creek runs N-S at col 8 (x=3). Bridge on row 7 (z=3).
// Zones: NW barn yard (hay, fence), NE windmill + flower field, SW picnic (bench, basket), S/E tall grass.
import { writeFileSync } from 'node:fs';
const X = (c) => (c - 6.5) * 2, Z = (r) => (r - 5.5) * 2;
const places = [];
const put = (asset, x, z, o = {}) => {
  const p = { asset, at: [x, o.y ?? 0, z] };
  if (o.yaw) p.yaw = o.yaw;
  if (o.scale) p.scale = o.scale;
  places.push(p);
};
let seed = 7;
const rnd = () => ((seed = (seed * 1664525 + 1013904223) % 4294967296) / 4294967296);

// curved path cells (dirt-ground)
const PATH = new Set(['1,7','2,7','3,7','4,7','5,7','6,7','7,7','9,7','10,7','10,6','10,5','10,4']);
for (let c = 1; c <= 12; c++) for (let r = 1; r <= 10; r++) {
  if (c === 8) { put('river-straight', X(c), Z(r)); continue; }
  put(PATH.has(`${c},${r}`) ? 'dirt-ground' : 'meadow-ground', X(c), Z(r));
}
// bridge over creek
put('bridge', 3, 3.0, { yaw: 0, scale: 1.0 });

// focal: windmill NE, barn NW
put('windmill', 7.0, -5.6, { yaw: 0, scale: 1.2 });
put('barn', -7.2, -5.8, { yaw: 0 });
// barn yard
put('hay-bale', -4.0, -4.6, { yaw: 20 }); put('hay-bale', -3.1, -4.9, { yaw: 350 });
put('hay-bale', -3.6, -4.2, { yaw: 10, y: 0.0, scale: 0.9 });
put('hay-bale', -10.0, -3.0, { yaw: 80 });
put('fence', -6.5, -2.4, { yaw: 0 }); put('fence', -8.4, -2.4, { yaw: 0 }); put('fence', -4.6, -2.4, { yaw: 0 });
put('fence', -10.6, -4.0, { yaw: 90 });
put('signpost', -2.0, 1.2, { yaw: 160 });
put('farmer', -4.6, -2.0, { yaw: 200, scale: 1.6 });
// picnic zone SW
put('bench', -6.4, 5.2, { yaw: 0, scale: 1.3 });
put('basket', -4.6, 5.6, { yaw: 30, scale: 1.6 });
put('cherry-tree', -9.2, 4.0, { yaw: 40, scale: 1.1 });
put('villager', -5.4, 6.8, { yaw: 200, scale: 1.6 });
// flower fields: [cx, cz, rx, rz, n, scale]
const FIELDS = [[-7, 0.5, 4, 4], [-1, 6.5, 4, 4], [9.6, 0.2, 3, 3], [-1.5, -1.5, 3, 3]];
for (const [cx, cz, nx, nz] of FIELDS) for (let i = 0; i < nx; i++) for (let j = 0; j < nz; j++)
  put('wildflowers', cx + (i - (nx - 1) / 2) * 0.95, cz + (j - (nz - 1) / 2) * 0.95, { yaw: Math.floor(rnd() * 360), scale: 1.4 + rnd() * 0.2 });
// tall grass along creek banks and corners
for (let z = -9; z <= 9; z += 1.9) {
  put('tall-grass', 1.45 + rnd() * 0.3, z + rnd(), { yaw: Math.floor(rnd() * 360), scale: 1.5 });
  put('tall-grass', 4.55 + rnd() * 0.3, z + 0.9 + rnd(), { yaw: Math.floor(rnd() * 360), scale: 1.5 });
}
// edge dressing: low bushes and a few trees
const BUSH = [[-11, -8.4],[-9,-8.8],[-5,-8.8],[-2,-8.5],[0.5,-8.7],[5.5,-8.8],[10.8,-8.4],[11,-4],[11,-1],[11,2.5],[10.8,8.5],[8,8.8],[5.8,8.8],[0,8.8],[-3,8.8],[-8,8.8],[-11,8.4],[-11,0],[-11,-1.5]];
for (const [x, z] of BUSH) put('bush', x, z, { yaw: Math.floor(rnd() * 360), scale: 1.3 });
put('apple-tree', 10.2, 3.3, { yaw: 60, scale: 1.3 });
put('apple-tree', 0.2, -8.0, { yaw: 120, scale: 1.2 });
put('apple-tree', -10.3, 8.0, { yaw: 200, scale: 1.2 });
put('signpost', 1.6, 4.8, { yaw: 20, scale: 1.0 });
put('crate', 5.3, -3.6, { yaw: 20 }); put('sack', 5.4, -2.7, { yaw: 350, scale: 1.3 }); put('sack', 4.9, -3.0, { yaw: 40, scale: 1.3 }); put('sack', 9.3, -4.2, { yaw: 10, scale: 1.3 });
put('basket', 9.0, -3.0, { yaw: 100, scale: 1.4 });
put('hay-bale', 10.0, -6.8, { yaw: 40 });

// output
const tally = {}; for (const p of places) tally[p.asset] = (tally[p.asset] || 0) + 1;
const head = `// GENERATED by scripts/design-meadow.mjs — edit the generator, not this file.\nimport type { Place } from '../chibi-quest.js';\nexport function places(): Place[] {\n  return [\n`;
const body = places.map((p) => '    ' + JSON.stringify(p).replace(/"(\w+)":/g, '$1:').replace(/"/g, "'").replace(/,/g, ', ').replace(/:/g, ': ')).join(',\n');
writeFileSync('scenes/maps/meadow.ts', head + body + ',\n  ];\n}\n');
const md = `# Flower meadow map\n\nGrid 12 x 10 tiles (24 x 20 m), meadow-ground with a curved dirt-ground path. Creek along x=3 with a bridge at z=3.\nZones: NW barn yard (barn, hay, fence, farmer), NE windmill and flower field, SW picnic (bench, basket, cherry tree).\n\n## Tally (${places.length} pieces)\n\n${Object.entries(tally).map(([k, v]) => `- ${k}: ${v}`).join('\n')}\n\nNotes: scale 1.3-1.6 on flowers, grass, people, bushes so they read at map distance.\n`;
writeFileSync('docs/map-mockups/meadow.md', md);
console.log(places.length, 'pieces');
