#!/usr/bin/env node
// Archive map designer: 14 m x 10 m cutaway records archive, north and west walls standing.
// x -7..7, z -5..5. Writes scenes/maps/archive.ts and docs/map-mockups/archive.md.
import { writeFileSync } from 'node:fs';

const places = [];
const put = (asset, x, z, o = {}) => {
  const p = { asset, at: [x, o.y ?? 0, z] };
  if (o.yaw) p.yaw = o.yaw;
  if (o.scale) p.scale = o.scale;
  places.push(p);
};

// Floor: 7 x 5 tiles, stone-floor border, wood-floor in the middle map zone.
for (let c = 0; c < 7; c++)
  for (let r = 0; r < 5; r++) {
    const x = -6 + c * 2, z = -4 + r * 2;
    const inner = c >= 1 && c <= 5 && r >= 1 && r <= 3;
    put(inner ? 'wood-floor' : 'stone-floor', x, z);
  }

// Walls: north (z=-5, faces south) and west (x=-7, faces east).
for (const x of [-6, -4, -2, 0, 2, 4, 6]) put(x === 2 ? 'plaster-wall-window' : 'plaster-wall', x, -5);
for (const z of [-4, -2, 0, 2, 4]) put('plaster-wall', -7, z, { yaw: 90 });
put('wall-corner', -7, -5, { yaw: 0 });
put('curtain', 2, -4.85);

// North wall shelving (aisle of stacks), faces south.
const nz = -4.7;
const north = [['bookcase', -6.2], ['bookshelf', -5.0], ['bookcase', -3.8], ['bookshelf', -2.6], ['bookcase', -1.4], ['bookshelf', -0.2],
  ['bookcase', 5.0], ['bookshelf', 6.2]];
for (const [a, x] of north) put(a, x, nz);
// West wall shelving, faces east.
const wx = -6.7;
for (const [a, z] of [['bookcase', -3.4], ['bookshelf', -2.2], ['bookcase', -1.0], ['bookshelf', 0.2], ['bookcase', 1.4], ['bookshelf', 3.0], ['bookcase', 4.2]])
  put(a, wx, z, { yaw: 90 });
// Free-standing stack row (aisle) in the NE zone.
for (const x of [2.6, 3.7]) put('bookshelf', x, -2.2);
for (const x of [2.6, 3.7]) put('bookshelf', x, -1.2, { yaw: 180 });
// Gallery stair in the NE corner.
put('stairs-wood', 6.4, -2.2, { yaw: 180 });
// Sliding ladder on the west stacks.
put('ladder', -6.3, 1.0, { yaw: 90 });

// Clerk desk (SW), with quills and a chair.
put('desk', -5.3, 3.3, { yaw: 90 });
put('chair', -4.3, 3.3, { yaw: 270 });
put('scroll', -5.3, 3.1, { y: 0.8 });
put('candle', -5.3, 3.7, { y: 0.8 });
put('cabinet', -6.4, 4.4, { yaw: 90 });

// Map table (center-south) with a rug beneath.
put('rug', 0, 0.4, { scale: 2.2 });
put('table', 0, 0.4);
put('map-fragment', 0.1, 0.4, { y: 0.6 });
put('candelabra', -0.3, 0.6, { y: 0.6 });
put('stool', -1.1, 0.4);
put('stool', 1.1, 0.5);
put('stool', 0, 1.5);

// Lockable cabinets and chests (SE).
put('cupboard', 6.6, 3.4, { yaw: 270 });
put('cupboard', 6.6, 4.4, { yaw: 270 });
put('chest', 3.0, 4.3, { yaw: 180 });
put('crate', 1.8, 4.4, { yaw: 170 });
put('scroll', 1.8, 4.3, { y: 0.41 });
// Reading nook, NE foreground.
put('table', 4.6, 1.6);
put('candle', 4.6, 1.6, { y: 0.6 });
put('chair', 4.6, 2.5, { yaw: 180 });
// Candle stands and lanterns.
for (const [x, z] of [[-2.2, -3.2], [-1.2, 2.8], [1.4, -3.4], [6.2, 0.8], [-6.2, -4.2]]) put('candelabra', x, z);
for (const [x, z] of [[-3.0, 4.5], [6.5, 3.0]]) put('lantern', x, z, { scale: 0.7 });
for (const [x, z, y] of [[3.0, 4.3, 0.46], [3.4, 4.3, 0.46], [-6.2, 1.8, 0], [0.4, 4.6, 0]]) put('candle', x, z, { y });
// Loose scrolls and barrels on the floor.
for (const [x, z, yaw] of [[-1.8, 1.4, 20], [1.8, -0.6, 70], [-2.8, -1.2, 120], [3.2, 1.0, 40], [0.9, 2.6, 100]]) put('scroll', x, z, { yaw });
put('barrel', -6.3, -3.6);
put('barrel', 5.6, 4.5, { scale: 0.8 });
put('banner', -3.2, -4.8, { yaw: 0, scale: 0.8 });
put('banner', 0.8, -4.85, { yaw: 0, scale: 0.8 });

// Scroll stacks atop the shelves and mid-shelf ledgers (dressing).
for (const [a, x] of north) for (const dx of [-0.25, 0.1, 0.35]) put('scroll', x + dx, nz, { y: a === 'bookcase' ? 2.02 : 1.667, yaw: 90 * (dx > 0 ? 1 : 0) });
for (const z of [-3.4, -2.2, -1.0, 0.2, 1.4, 3.0, 4.2]) for (const dz of [-0.2, 0.2]) put('scroll', wx, z + dz, { y: 1.7, yaw: 90 });
for (const x of [2.6, 3.7]) for (const dx of [-0.2, 0.15]) put('scroll', x + dx, -1.7, { y: 1.667 });
for (const x of [-5.4, -4.4, -3.4]) put('scroll', x, -4.3, { y: 0.0, yaw: 15 * x });
for (let i = 0; i < 12; i++) put('map-fragment', -2 + (i % 4) * 0.5, -0.4 + Math.floor(i / 4) * 0.6, { yaw: i * 37 });
for (const [x, z] of [[-6.5, -1.6], [-6.5, 2.4], [-6.5, 4.6], [6.5, -4.4], [6.4, 1.8]]) put('candle', x, z);

const fmt = (p) => {
  const n = (v) => (Number.isInteger(v) ? String(v) : String(+v.toFixed(2)));
  return `  { asset: '${p.asset}', at: [${n(p.at[0])}, ${n(p.at[1])}, ${n(p.at[2])}]${p.yaw ? `, yaw: ${p.yaw}` : ''}${p.scale ? `, scale: ${p.scale}` : ''} },`;
};
writeFileSync('scenes/maps/archive.ts', `// GENERATED by scripts/design-archive.mjs — edit the generator, not this file.
import type { Place } from '../chibi-quest.js';
export function places(): Place[] {
  return [
${places.map(fmt).join('\n')}
  ];
}
`);
const tally = {};
for (const p of places) tally[p.asset] = (tally[p.asset] ?? 0) + 1;
writeFileSync('docs/map-mockups/archive.md', `# Archive map (generated)

GENERATED by \`scripts/design-archive.mjs\`. 14 m x 10 m (x -7..7, z -5..5), north and west walls.

Zones: west stacks with sliding ladder and clerk desk (SW); map table on a rug (center);
cabinets, chests, reading nook (SE); free-standing aisle and gallery stair (NE).
Focal object: map table with rug. Path: open floor from the SE edge to the map table and the stair.

Pieces: ${places.length}

${Object.entries(tally).map(([k, v]) => `- ${k}: ${v}`).join('\n')}
`);
console.log('wrote', places.length);
