#!/usr/bin/env node
// Wayfarers inn: 12 x 10 m cutaway common room (floor x -6..6, z -5..5), north and west walls
// standing. Zones: hearth + long table (north/centre), counter and stairs (east), sleeping alcove
// behind curtains (south-west), travelers' corner (south). One floor family: wood-floor.
// Writes scenes/maps/inn.ts and docs/map-mockups/inn.md from the same data.
import { writeFileSync } from 'node:fs';

const places = [];
const put = (asset, x, z, yaw = 0, y = 0) => {
  const p = { asset, at: [+x.toFixed(3), +y.toFixed(3), +z.toFixed(3)] };
  if (yaw) p.yaw = yaw;
  places.push(p);
};

// Floor: 6 x 5 tiles, one material.
for (let c = 0; c < 6; c++) for (let r = 0; r < 5; r++) put('wood-floor', -5 + c * 2, -4 + r * 2);

const NZ = -4.92, WX = -5.92;

put('plaster-wall', -5, NZ); put('plaster-wall', WX, -4, 90);
const north = { '-3': 'plaster-wall-window', '-1': 'plaster-wall', '1': 'plaster-wall', '3': 'plaster-wall-window', '5': 'plaster-wall' };
for (const [x, a] of Object.entries(north)) put(a, +x, NZ);
const west = { '-2': 'plaster-wall-door', '0': 'plaster-wall', '2': 'plaster-wall-window', '4': 'plaster-wall' };
for (const [z, a] of Object.entries(west)) put(a, WX, +z, 90);

// Hearth zone: fireplace on the north wall, rug, two armchairs, firewood, sconces.
put('fireplace', -1, -4.74);
put('rug', -1, -3.3);
put('chair', -2.1, -3.3, 180); put('chair', 0.1, -3.3, 180);
put('firewood', -2.6, -4.55); put('bucket', 0.8, -4.55);
put('torch-sconce', -4.4, -4.8); put('torch-sconce', 2.0, -4.8);
put('torch-sconce', -5.8, -0.7, 90); put('torch-sconce', -5.8, -3.3, 90);
put('adventurer', 0.9, -2.5, 200);

// Long table: four tables end to end with a bench on each side.
const tabA = [-3, -2, -1, 0];
for (const x of tabA) put('table', x, -0.5);
for (const x of [-3, -1.5, 0]) { put('bench', x, -1.25); put('bench', x, 0.25, 180); }
for (const x of tabA) {
  put('plate', x - 0.2, -0.75, 0, 0.6); put('plate', x + 0.2, -0.25, 0, 0.6);
  put('mug', x + 0.2, -0.75, 0, 0.6); put('tankard', x - 0.2, -0.25, 0, 0.6);
}
put('candle', -1.5, -0.5, 0, 0.6); put('cheese', -2.5, -0.5, 0, 0.6);
put('bread-ration', -0.5, -0.5, 0, 0.6); put('bottle', 0.1, -0.5, 0, 0.6);

// Small table with stools (east of the long table).
for (const x of [1.8, 2.8]) put('table', x, 1.8);
for (const [x, z] of [[1.8, 2.75], [2.8, 2.75], [1.8, 0.85], [2.8, 0.85], [1.0, 1.8], [3.6, 1.8]]) put('stool', x, z);
put('plate', 1.6, 1.6, 0, 0.6); put('plate', 3.0, 2.0, 0, 0.6); put('mug', 2.0, 2.0, 0, 0.6);
put('mug', 2.6, 1.6, 0, 0.6); put('candle', 2.3, 1.8, 0, 0.6); put('apple', 2.9, 1.5, 0, 0.6);

// Counter along the east edge, barrels and innkeeper behind, bottles and mugs on top.
for (const z of [-0.8, 1.2, 3.2]) put('counter', 5.0, z, 270);
put('innkeeper', 5.65, 1.2, 270);
put('barrel', 5.62, -1.3); put('barrel', 5.62, 2.7); put('barrel', 5.62, 3.7);
for (const z of [-1.2, -0.4, 0.4, 2.1, 2.7, 3.5]) put('mug', 4.95, z, 0, 0.75);
for (const z of [-0.8, 3.0]) put('bottle', 5.1, z, 0, 0.75);
put('plate', 4.95, 1.6, 0, 0.75); put('candle', 5.1, 0.0, 0, 0.75); put('candle', 5.1, 3.9, 0, 0.75);
put('adventurer', 3.9, -0.3, 270);

// Stairs to the rooms (NE corner), crates under the north wall, lantern post.
put('stairs-wood', 5.3, -3.8);
put('crate', 3.9, -4.4); put('crate', 3.9, -3.85, 8); put('crate', 3.9, -4.4, 0, 0.41);
put('sack', 4.4, -4.5);
put('lantern', 4.2, -2.3);

// Sleeping alcove behind curtains (SW): bunk-bed, bed, luggage.
put('curtain', -5.3, 1.0); put('curtain', -3.9, 1.0);
put('bunk-bed', -5.4, 2.2); put('bed', -5.4, 4.05);
put('bed', -4.2, 2.25); put('bunk-bed', -4.2, 4.0);
put('backpack', -3.2, 1.7); put('satchel', -3.2, 2.4); put('bedroll', -3.1, 3.2, 90);
put('backpack', -3.2, 4.2); put('satchel', -3.2, 4.8);
put('chest', -5.4, 0.45, 0); put('candle', -5.4, 0.45, 0, 0.45);
put('torch-sconce', -5.8, 4.9, 90);

// Travelers' corner (south): small table, two chairs, luggage.
put('rug', 0.8, 3.9);
put('table', 0.8, 3.9); put('chair', 0.0, 3.9, 90); put('chair', 1.6, 3.9, 270);
put('mug', 0.7, 3.8, 0, 0.6); put('plate', 1.0, 4.0, 0, 0.6); put('candle', 0.8, 4.05, 0, 0.6);
put('backpack', -0.8, 4.5); put('satchel', 2.3, 4.6); put('bedroll', -1.6, 4.3, 90);
put('bucket', -1.0, 3.5);

// Wall-edge dressing: barrels NW, shelf and mirror-free plaster walls kept calm.
put('barrel', -5.3, -4.3); put('barrel', -4.6, -4.4); put('sack', -5.4, -3.6);
put('shelf', 1.6, -4.7);
put('bottle', 1.2, -4.7, 0, 1.0); put('mug', 1.9, -4.7, 0, 1.0); put('wood-log', -3.9, -4.5);

const header = `// GENERATED by scripts/design-inn.mjs — edit the generator, not this file.\nimport type { Place } from '../chibi-quest.js';\nexport function places(): Place[] {\n  return [\n`;
const body = places.map((p) => '    ' + JSON.stringify(p).replace(/"(\w+)":/g, '$1:').replace(/"/g, "'").replace(/,/g, ', ').replace(/:/g, ': ') + ',').join('\n');
writeFileSync('scenes/maps/inn.ts', header + body + '\n  ];\n}\n');

const tally = {};
for (const p of places) tally[p.asset] = (tally[p.asset] ?? 0) + 1;
const rows = Object.entries(tally).sort((a, b) => b[1] - a[1]).map(([a, n]) => `| ${a} | ${n} |`).join('\n');
writeFileSync('docs/map-mockups/inn.md', `# Wayfarers inn

Floor x -6..6, z -5..5 (6 x 5 wood-floor tiles). North and west walls stand; south and east are cutaway.

Zones: hearth and long table (north/centre), counter with barrels and innkeeper plus stairs (east),
sleeping alcove behind curtains (south-west), travelers' corner (south).
Focal object: the fireplace on the north wall. Path: west door (z=-2) across the room to the counter.

Pieces: ${places.length}

| asset | count |
|---|---|
${rows}
`);
console.log(`inn: ${places.length} placements`);
