#!/usr/bin/env node
// Island map designer. Grid 11 x 9 tiles of 2 m (22 x 18 m). Sand ring, grass hills, lagoon SW.
// Writes scenes/maps/island.ts and docs/map-mockups/island.md.
import { writeFileSync } from 'node:fs';
const places = [];
const put = (asset, x, z, o = {}) => {
  const p = { asset, at: [x, o.y ?? 0, z] };
  if (o.yaw) p.yaw = o.yaw;
  if (o.scale) p.scale = o.scale;
  places.push(p);
};
let s = 11; const rnd = () => ((s = (s * 16807) % 2147483647) / 2147483647);
const r2 = (a, b) => a + (b - a) * rnd();
const yawr = () => Math.round(r2(0, 359));
const cols = [-10, -8, -6, -4, -2, 0, 2, 4, 6, 8, 10];
const rows = [-8, -6, -4, -2, 0, 2, 4, 6, 8];
const land = (x, z) => (x / 10.6) ** 2 + (z / 8.6) ** 2 <= 1.0;
const lagoon = (x, z) => (x >= -6 && x <= 0 && z >= 2 && z <= 4) || (x >= -8 && x <= -4 && z === 4 ) || (x >= -4 && x <= 2 && z === 2 && false);
const grass = (x, z) => (z <= -2 && x <= 0 && x >= -6) || (z === -4 && x >= 4 && x <= 6) || (z === -2 && x >= -8 && x <= -6) || (z === 0 && x >= -8 && x <= -4) || (z === -2 && x === 6);
const glyph = [];
const inLand = [];
for (const z of rows) {
  let row = '';
  for (const x of cols) {
    if (lagoon(x, z)) { put('sea-water', x, z); row += '~'; }
    else if (land(x, z)) { put(grass(x, z) ? 'grass-ground' : 'desert-ground', x, z); row += grass(x, z) ? '"' : '.'; }
    else { put('sea-water', x, z); row += '~'; }
  }
  glyph.push(row);
}
// ---- hut + palms (north hill)
put('hut', -0.4, -5.2, { yaw: 10, scale: 1.0 });
put('palm-tree', -3.2, -3.6, { yaw: 30, scale: 1.1 });
put('palm-tree', 4.6, -4.6, { yaw: 200, scale: 1.0 });
put('palm-tree', -6.4, -0.6, { yaw: 120, scale: 0.9 });
put('palm-tree', 7.6, 1.6, { yaw: 300, scale: 0.85 });
for (const [x, z] of [[-1.8, -3.6], [-4.8, -2.4], [-2.4, -1.6], [-6.8, -1.6], [5.6, -3.6], [6.6, -2.2], [-1.6, -6.0]]) put('bush', x, z, { yaw: yawr(), scale: r2(0.7, 1.0) });
// ---- camp (east sand)
put('campfire', 4.0, 1.0, { scale: 1.3 });
put('fallen-log', 2.8, 1.6, { yaw: 100 });
put('barrel', 5.8, 0.2, { yaw: 40 });
put('crate', 5.9, 0.9, { yaw: 25, scale: 0.8 });
put('tent', 2.6, -1.6, { yaw: 160, scale: 0.7 });
// ---- treasure marker (south-east sand)
put('chest', 1.8, 4.6, { yaw: 200, scale: 0.8 });
put('shell', 0.6, 4.2, { yaw: 40 });
put('signpost', 3.0, 4.4, { yaw: 160, scale: 0.8 });
// ---- dock + rowboat in the lagoon
put('dock', -3.0, 2.4, { yaw: 90, scale: 0.85 });
put('rowboat', -2.6, 3.7, { yaw: 100, y: -0.03, scale: 0.9 });
put('fishing-net', -1.2, 1.6, { yaw: 180 });
put('coral', -5.2, 3.0, { y: -0.05, scale: 0.8 });
// ---- ring: dunes, rocks, shells, flowers around the coast
const ring = [];
for (let i = 0; i < 46; i++) {
  const a = (i / 46) * Math.PI * 2 + r2(-0.03, 0.03);
  const rr = 1.0 + r2(0.0, 0.04);
  ring.push([Math.cos(a) * 10.4 * rr, Math.sin(a) * 8.4 * rr, i]);
}
for (const [x, z, i] of ring) {
  const k = i % 5;
  if (k === 0) put('boulder', x, z, { yaw: yawr(), scale: r2(0.7, 1.2), y: -0.03 });
  else if (k === 1) put('rock-cluster', x, z, { yaw: yawr(), scale: r2(0.6, 0.9), y: -0.03 });
  else if (k === 2) put('sand-dune', x * 0.93, z * 0.93, { yaw: yawr(), scale: r2(0.4, 0.55) });
  else if (k === 3) put('river-rock', x, z, { yaw: yawr(), y: -0.03 });
  else put('sand-dune', x * 0.9, z * 0.9, { yaw: yawr(), scale: 0.35 });
}
for (const [x, z] of [[-9.0, 0.8], [-9.4, -2.6], [8.6, 3.6], [-1, 6.8], [-7.6, 5.2]]) put('coral', x, z, { y: -0.05, yaw: yawr(), scale: 0.7 });
for (let i = 0; i < 14; i++) {
  const a = r2(0, 6.283), rd = r2(0.55, 0.82);
  const x = Math.cos(a) * 9.4 * rd, z = Math.sin(a) * 7.2 * rd;
  if (land(x, z) && !lagoon(Math.round(x / 2) * 2, Math.round(z / 2) * 2)) put('wildflowers', x, z, { yaw: yawr() });
}
for (let i = 0; i < 10; i++) put('shell', r2(-7, 7), r2(0.2, 5.4), { yaw: yawr(), scale: 0.8 });
const ok = (p) => land(p.at[0], p.at[2]) || ['boulder','rock-cluster','river-rock','coral','sea-water','rowboat'].includes(p.asset);
void inLand;

const num = (v) => (Number.isInteger(v) ? String(v) : v.toFixed(2).replace(/0+$/, '').replace(/\.$/, ''));
const fmt = (p) => `    { asset: '${p.asset}', at: [${num(p.at[0])}, ${num(p.at[1])}, ${num(p.at[2])}]${p.yaw ? `, yaw: ${p.yaw}` : ''}${p.scale ? `, scale: ${p.scale}` : ''} },`;
writeFileSync('scenes/maps/island.ts', `// GENERATED by scripts/design-island.mjs — edit the generator, not this file.
import type { Place } from '../chibi-quest.js';
export function places(): Place[] {
  return [
${places.map(fmt).join('\n')}
  ];
}
`);
const tally = {};
for (const p of places) tally[p.asset] = (tally[p.asset] ?? 0) + 1;
writeFileSync('docs/map-mockups/island.md', `# Island (generated)

GENERATED by scripts/design-island.mjs. 22 x 18 m (11 x 9 tiles). Sand (desert-ground) ring, grass hills (north and west),
sea-water all around (top y=-0.03) plus a SW lagoon with dock and rowboat; hut north, campfire east, chest south-east.
Coast ringed with boulders, rock clusters, dunes and river rocks to hide straight tile edges.

\`\`\`
${glyph.join('\n')}
\`\`\`

| piece | count |
|---|---|
${Object.entries(tally).sort((a, b) => b[1] - a[1]).map(([k, v]) => `| ${k} | ${v} |`).join('\n')}

Total: ${places.length}
`);
console.log(glyph.join('\n'), '\n', places.length, JSON.stringify(tally));
for (const p of places) if (!ok(p)) console.log('OUT', p.asset, p.at);
