#!/usr/bin/env node
// Stable yard map: 8 x 6 tiles of 2 m (16 m x 12 m), dirt-ground only.
// Col c 1..8 west->east, row r 1..6 north->south. x = (c-4.5)*2, z = (r-3.5)*2.
// Zones: stall row (barn + 4 sheds on the north edge), paddock fence and horses (east/south),
// tack and hay yard (west), trough and cart (south-west of the paddock).
import { writeFileSync } from 'node:fs';

const places = [];
const put = (asset, x, z, o = {}) => {
  const p = { asset, at: [x, o.y ?? 0, z] };
  if (o.yaw) p.yaw = o.yaw;
  if (o.scale) p.scale = o.scale;
  places.push(p);
};

for (let c = 1; c <= 8; c++) for (let r = 1; r <= 6; r++) put('dirt-ground', (c - 4.5) * 2, (r - 3.5) * 2);

const FENCE = 1.93;
// --- zone 1: one long open-fronted stable (x -3..7, z -6..-4), hayloft barn at the west end ---
put('barn', -5.2, -3.9, { yaw: 0, scale: 0.95 });
const STALL_X = [-2, 0, 2, 4, 6];
for (const x of STALL_X) {
  put('timber-wall', x, -5.85); // back wall
  put('roof-thatch', x, -4.46, { y: 1.5 }); // south slope, eave over the open front
  put('roof-thatch', x, -5.82, { y: 1.5, yaw: 180 }); // north slope
  put('horse', x + 0.3, -4.9, { yaw: 0 });
  put('hay-bale', x - 0.55, -5.35, { yaw: 8 });
  put('bucket', x - 0.5, -4.4, { yaw: x * 20 });
}
for (const x of [-1, 1, 3, 5]) put('fence', x, -5.0, { yaw: 90, scale: 1.0 }); // stall dividers
put('fence', 7.0, -5.0, { yaw: 90 }); // east end rail
put('timber-wall', 7.0, -5.0, { yaw: 270 });
put('lantern', -2.9, -3.7);
put('lantern', 3.0, -3.7);

// --- zone 2: clear central yard, round trough as the focal object, hitching rail ---
put('well-apron', -0.2, 0.2, { scale: 0.8 });
put('water-trough', -0.2, 0.2, { scale: 0.8 });
for (let i = 0; i < 3; i++) put('fence', -2.9 + i * FENCE, -2.4, { yaw: 0 }); // hitching rail

for (let k = 0; k < 10; k++) { const a = k * Math.PI / 5; put('stepping-stone', -0.2 + Math.cos(a) * 1.55, 0.2 + Math.sin(a) * 1.55, { yaw: k * 36 }); }
put('bucket', 0.9, 1.6, { yaw: 30 });

// --- zone 3: paddock (east), rectangular, two horses, mounting block ---
for (let i = 0; i < 4; i++) put('fence', 7.7, -0.2 + i * 1.8, { yaw: 90 }); // east side
for (let i = 0; i < 2; i++) put('fence', 4.2 + i * FENCE, -1.1, { yaw: 0 }); // north side
for (const z of [-0.2, 1.7, 5.2]) put('fence', 3.2, z, { yaw: 90 }); // west side, gate gap z 3..4.4
for (let i = 0; i < 3; i++) put('fence', 6.6 - i * FENCE, 5.8, { yaw: 0 }); // south side
put('horse', 5.6, 1.4, { yaw: 230 });
put('horse', 4.8, 3.9, { yaw: 40 });
put('water-trough', 6.7, 4.7, { yaw: 0 });
put('crate', 3.9, 0.0, { yaw: 0 }); // mounting block: two stacked crates
put('crate', 3.9, 0.0, { yaw: 25, y: 0.41, scale: 0.9 });

// --- zone 4: tack and cart corner (south-west) ---
put('wagon', -5.6, 3.6, { yaw: 100 });
put('handcart', -3.4, 4.4, { yaw: 200 });
put('barrel', -7.2, 1.0, { yaw: 30 });
put('barrel', -7.2, 1.9, { yaw: 70 });
put('barrel', -6.5, 1.4, { yaw: 10 });
put('crate', -4.9, 1.6, { yaw: 15 });
put('crate', -4.3, 1.9, { yaw: 60 });
put('sack', -5.6, 1.5, { yaw: 120 });
put('sack', -6.0, 2.0, { yaw: 40 });
put('signpost', -2.2, 5.2, { yaw: 20 });
for (let i = 0; i < 3; i++) put('fence', -7.9, 1.0 + i * 1.8, { yaw: 90 });
for (let i = 0; i < 2; i++) put('fence', -7.9, -1.5 - i * 1.8, { yaw: 90 }); // west rail north
// hay store against the barn's south wall
for (const [x, z] of [[-6.6, -1.4], [-5.6, -1.4], [-4.6, -1.4]]) put('hay-bale', x, z, { yaw: 5 });
for (const [x, z] of [[-6.1, -1.4], [-5.1, -1.4]]) put('hay-bale', x, z, { yaw: 5, y: 0.62 });
put('villager', 1.6, -3.0, { yaw: 160 });

// --- edge dressing ---
for (const [x, z] of [[-3.0, -1.2], [-3.9, -0.2], [-4.2, 0.6]]) put('bush', x, z, { yaw: x * 33, scale: 0.8 });
put('barrel', -3.3, 2.6, { yaw: 50 });
put('sack', -3.6, 3.0, { yaw: 90 });
put('crate', -6.9, 4.5, { yaw: 80 });
put('barrel', -2.0, 4.2, { yaw: 10 });
put('oak-tree', -7.3, 5.2, { yaw: 20, scale: 0.55 });
for (const [x, z] of [[7.5, -3.0], [7.6, -5.6], [-2.8, 5.6], [-0.8, 5.6], [1.4, 5.6], [-7.5, -0.2]]) put('bush', x, z, { yaw: x * 40 });
for (const [x, z] of [[2.2, 5.5]]) put('oak-tree', x, z, { yaw: 90, scale: 0.5 });

const num = (v) => (Number.isInteger(v) ? String(v) : v.toFixed(2).replace(/0+$/, '').replace(/\.$/, ''));
const fmt = (p) => `  { asset: '${p.asset}', at: [${p.at.map(num).join(', ')}]${p.yaw ? `, yaw: ${p.yaw}` : ''}${p.scale ? `, scale: ${p.scale}` : ''} },`;
writeFileSync('scenes/maps/stable.ts', `// GENERATED by scripts/design-stable.mjs — edit the generator, not this file.
import type { Place } from '../chibi-quest.js';
export function places(): Place[] {
  return [
${places.map(fmt).join('\n')}
  ];
}
`);
const tally = {};
for (const p of places) tally[p.asset] = (tally[p.asset] ?? 0) + 1;
writeFileSync('docs/map-mockups/stable.md', `# Stable map (generated)

GENERATED by \`scripts/design-stable.mjs\`. 8 x 6 dirt-ground tiles (16 m x 12 m).

Zones: stall row on the north edge (barn plus four sheds with feed bales), paddock with fence and
horses (east and south), tack and hay yard (west), trough and carts (south-west).

| component | count |
|---|---|
${Object.entries(tally).map(([k, v]) => `| ${k} | ${v} |`).join('\n')}

Total: ${places.length}.
`);
console.log(places.length, JSON.stringify(tally));
