#!/usr/bin/env node
// Canyon map designer (P2, pass 3): 26 m x 18 m. Grid 13 x 9 tiles of 2 m: x=(c-6)*2, z=(r-4)*2.
// Canyon floor y=0 (c2-10, r2-8) with a winding dry riverbed; plateaus y=2.6 on west (c0-1), east (c11-12),
// north (r1) and y=5.2 on the north back cliff (r0), held by rock-wall-red faces (2.6 m per course).
import { writeFileSync } from 'node:fs';
const X = (c) => (c - 6) * 2, Z = (r) => (r - 4) * 2;
const places = [];
const put = (asset, x, y, z, o = {}) => {
  const p = { asset, at: [x, y, z] };
  if (o.yaw) p.yaw = o.yaw;
  if (o.scale) p.scale = o.scale;
  places.push(p);
};
let seed = 11;
const rnd = () => ((seed = (seed * 16807) % 2147483647) / 2147483647);
const MID = 2.6, UP = 5.2;
const H = (c, r) => (c < 0 || c > 12 || r < 0 || r > 8 ? null : r === 0 ? UP : r === 1 || c <= 1 || c >= 11 ? MID : 0);
// winding bed: south (c8) north to r5, west along r5 to c4, north to the cave at r2
const BED = new Map();
for (const r of [8, 7, 6]) BED.set(`8,${r}`, 0);
for (const c of [7, 6, 5]) BED.set(`${c},5`, 90);
for (const r of [4, 3, 2]) BED.set(`4,${r}`, 0);
const CORNER = new Set(['8,5', '4,5']);
for (let c = 0; c <= 12; c++)
  for (let r = 0; r <= 8; r++) {
    const h = H(c, r), k = `${c},${r}`;
    if (h > 0) put('desert-ground', X(c), h, Z(r));
    else if (BED.has(k)) put('dry-riverbed', X(c), 0, Z(r), { yaw: BED.get(k) });
    else put(CORNER.has(k) ? 'desert-ground' : 'desert-ground', X(c), 0, Z(r));
  }
const DIRS = [[0, 1, 0, 0.4], [0, -1, 180, -0.4], [1, 0, 90, 0.4], [-1, 0, 270, -0.4]];
for (let c = 0; c <= 12; c++)
  for (let r = 0; r <= 8; r++) {
    const h = H(c, r);
    if (!h) continue;
    for (const [dc, dr, yaw, off] of DIRS) {
      const nh = H(c + dc, r + dr);
      if (nh === null || nh >= h) continue;
      if (c === 4 && r === 1 && dr === 1) continue; // cave opening
      const wx = dc ? X(c) + dc + off : X(c), wz = dr ? Z(r) + dr + off : Z(r);
      for (let y = nh; y < h - 0.01; y += 2.6) put('rock-wall-red', wx, y, wz, { yaw });
    }
  }
put('cave-mouth', -4, 0, -4.9, { scale: 1.2 });
put('bridge', 0, 0, 2, { yaw: 90 });
put('signpost', 5.6, 0, 6.6, { yaw: 200 });
put('torch', -5.6, 0, -3.6);
// SW wagon camp
put('wagon', -6.4, 0, 4.6, { yaw: 60 }); put('crate', -4.8, 0, 3.6, { yaw: 20 }); put('crate', -4.4, 0, 4.4, { yaw: 70, scale: 0.8 });
put('barrel', -7.8, 0, 2.6); put('barrel', -8.1, 0, 3.4, { yaw: 40 }); put('bone-pile', -4.2, 0, 6.6, { yaw: 120 });
put('bandit', -5.2, 0, 2.2, { yaw: 200, scale: 1.6 }); put('dead-tree', -7.6, 0, 6.8, { yaw: 210 });
put('rock-cluster', -2.6, 0, 6.8, { yaw: 50, scale: 1.4 }); put('boulder', -8.2, 0, 0.6, { yaw: 80 });
// floor dressing
put('dead-tree', 1.6, 0, 6.0, { yaw: 100 }); put('dead-tree', 7.4, 0, 1.6, { yaw: 300 }); put('dead-tree', -6.6, 0, -1.8, { yaw: 40 });
for (const [x, z, s] of [[2, 4, 1], [7, 4.4, 0.9], [-1.5, 4.4, 1], [-8, -0.6, 0.8], [1.5, -2.6, 1], [7.8, 7.4, 1.1], [-3, 0.4, 0.9]]) put('cactus', x, 0, z, { scale: s });
for (const [x, z, y] of [[-2, -3, 10], [2.4, -1.4, 100], [6, 0, 40], [3, 7.4, 150], [-1, 1.4, 200], [0.4, -0.6, 270], [-2.4, 3.6, 250], [6.6, 3.2, 20]]) put(rnd() > 0.5 ? 'boulder' : 'rock-cluster', x, 0, z, { yaw: y, scale: 0.9 + rnd() * 0.4 });
put('adventurer', 4, 0, 7.4, { yaw: 180, scale: 1.6 }); put('ranger', 6.2, 0, 2.8, { yaw: 220, scale: 1.6 });
put('bone-pile', 2.4, 0, -3.4, { yaw: 40 });
// plateau dressing (west, east, north, back cliff)
for (const [a, x, y, z, yaw, s] of [
  ['dead-tree', -11, MID, 2, 30, 1], ['dead-tree', -11.4, MID, -4, 100, 1.1], ['boulder', -11, MID, 6, 60, 1.2], ['cactus', -11.6, MID, 0, 0, 1],
  ['rock-cluster', -11, MID, -1.8, 200, 1.3], ['cactus', -11.2, MID, 4.4, 0, 1], ['boulder', -12, MID, -6, 10, 1.2],
  ['dead-tree', 11, MID, -2, 200, 1], ['boulder', 11.2, MID, 2, 140, 1.3], ['rock-cluster', 11.4, MID, 5.6, 300, 1.3], ['cactus', 11, MID, 0, 0, 1],
  ['cactus', 11.8, MID, 3.6, 0, 1], ['dead-tree', 11.6, MID, 7, 80, 1], ['boulder', 11, MID, -5, 20, 1],
  ['boulder', 2, MID, -6.8, 0, 1.2], ['rock-cluster', 7, MID, -6.4, 90, 1.3], ['cactus', 5, MID, -6.6, 0, 1], ['dead-tree', -2, MID, -6.4, 20, 1.1],
  ['boulder', -8, MID, -6.6, 50, 1.2], ['rock-cluster', 10, MID, -7, 130, 1.2], ['cactus', -6, MID, -6.2, 0, 1],
  ['boulder', -6, UP, -8, 20, 1.5], ['rock-cluster', 0, UP, -8.2, 100, 1.5], ['dead-tree', 6, UP, -8, 60, 1.2], ['boulder', 9, UP, -8, 200, 1.4], ['cactus', -10, UP, -8, 0, 1], ['dead-tree', -2, UP, -7.6, 120, 1.1],
]) put(a, x, y, z, { yaw, scale: s });

const num = (v) => (Number.isInteger(v) ? String(v) : v.toFixed(2).replace(/0+$/, '').replace(/\.$/, ''));
const fmt = (p) => `  { asset: '${p.asset}', at: [${num(p.at[0])}, ${num(p.at[1])}, ${num(p.at[2])}]${p.yaw ? `, yaw: ${p.yaw}` : ''}${p.scale ? `, scale: ${num(p.scale)}` : ''} },`;
writeFileSync('scenes/maps/canyon.ts', `// GENERATED by scripts/design-canyon.mjs — edit the generator, not this file.
import type { Place } from '../chibi-quest.js';
export function places(): Place[] {
  return [
${places.map(fmt).join('\n')}
  ];
}
`);
const tally = {};
for (const p of places) tally[p.asset] = (tally[p.asset] ?? 0) + 1;
writeFileSync('docs/map-mockups/canyon.md', `# Canyon map (generated by scripts/design-canyon.mjs)

26 m x 18 m. Floor y=0 (c2-10, r2-8); plateaus y=2.6 west/east/north; back cliff y=5.2 (r0); rock-wall-red retaining faces.
Dry riverbed winds south (x=4) -> west along z=2 under the bridge -> north (x=-4) to the cave mouth. Two bends.
Zones: SW wagon camp, SE dry flats, plateau dressing. Focal: bridge and cave mouth.

## Tally (${places.length})
${Object.entries(tally).map(([a, n]) => `- ${a}: ${n}`).join('\n')}
`);
console.log(places.length, 'pieces');
