#!/usr/bin/env node
// Ancient tomb map designer: 14 x 12 m sandstone chamber (7 x 6 tiles of 2 m). One material family:
// desert-ground. The walls are the outer ring of tiles stacked 5 high (1.5 m). Interior tile
// centers x -6..6, z -5..5; wall inner faces on x=+-7 and z=+-6. North is -Z.
// Zones: three-step dais with sarcophagus (focal); north wall door + lever; east/south mummy
// groups; west vigil; south-west trap corridor from the entry gap at x=-4.
import { writeFileSync } from 'node:fs';
const places = [];
const put = (asset, x, z, o = {}) => {
  const p = { asset, at: [x, o.y ?? 0, z] };
  if (o.yaw) p.yaw = o.yaw;
  if (o.scale) p.scale = o.scale;
  places.push(p);
};
const WALL_LAYERS = 5; // y = 0 .. 1.2, top 1.5 m
const inside = (x, z) => Math.abs(x) <= 6 && Math.abs(z) <= 5;
const gaps = [[0, -7], [-4, 7]]; // door cells: only the base tile
for (let x = -8; x <= 8; x += 2)
  for (let z = -7; z <= 7; z += 2) {
    if (inside(x, z)) { put('desert-ground', x, z); continue; }
    const gap = gaps.some(([gx, gz]) => gx === x && gz === z);
    for (let k = 0; k < (gap ? 1 : WALL_LAYERS + 0); k++) put('desert-ground', x, z, { y: 0.3 * k });
  }
// three-step dais: level 1 (top 0.3) x -4..4, level 2 (0.6) x -2..2, level 3 (0.9) x 0
for (const z of [-3, -1]) {
  for (let x = -4; x <= 4; x += 2) put('desert-ground', x, z, { y: 0.3 });
  for (let x = -2; x <= 2; x += 2) put('desert-ground', x, z, { y: 0.6 });
  put('desert-ground', 0, z, { y: 0.9 });
}
put('sarcophagus', 0, -2, { y: 0.9, yaw: 90, scale: 1.05 });
for (const [x, z] of [[-3.6, -3.6], [3.6, -3.6], [-3.6, -0.4], [3.6, -0.4]]) put('statue', x, z, { y: 0.3, scale: 0.6, yaw: x < 0 ? 40 : -40 });
for (const [x, z] of [[-1.3, -3.6], [1.3, -3.6], [-1.3, -0.4], [1.3, -0.4]]) put('brazier', x, z, { y: 0.6, scale: 0.8 });
put('gold-pile', 2.8, -2, { y: 0.3, scale: 0.7 }); put('urn', -2.8, -2, { y: 0.3 });
// north wall: heavy door, lever, torches, pillars every 4 m
put('iron-door', 0, -6.1, { scale: 1.45 });
put('lever', 1.5, -5.7);
put('wall-sconce', -1.3, -6.2); put('wall-sconce', 1.3, -6.2);
put('brazier', -1.9, -5.4, { scale: 0.8 }); put('brazier', 1.9, -5.4, { scale: 0.8 });
for (const x of [-6, -2.4, 2.4, 6]) put('pillar', x, -6.4, { scale: 1.1 });
for (const z of [-1.2, 2.8]) { put('pillar', -6.5, z, { scale: 1.1, yaw: 90 }); put('pillar', 6.5, z, { scale: 1.1, yaw: 270 }); }
for (const x of [0, 4]) put('pillar', x, 5.5, { scale: 1.1, yaw: 180 });
put('torch-sconce', -6.7, -3.6, { yaw: 90 }); put('torch-sconce', 6.7, -3.6, { yaw: 270 });
// south entry doorway
put('wood-door', -4, 6.9, { scale: 1.6, yaw: 180 });
// mummy group A (east) and group B (south-centre)
[[4.4, 0.8, 250], [5.5, 1.9, 260], [4.2, 2.6, 280]].forEach(([x, z, y]) => put('mummy', x, z, { yaw: y, scale: 1.2 }));
put('urn', 5.6, 0.2); put('urn', 3.5, 1.6, { yaw: 40 }); put('jar', 5.8, 3.2);
[[1.4, 3.6, 200], [2.6, 4.4, 160]].forEach(([x, z, y]) => put('mummy', x, z, { yaw: y, scale: 1.2 }));
put('urn', 0.6, 4.6); put('urn', 3.5, 3.4, { yaw: 70 }); put('jar', 1.5, 4.9);
put('treasure-chest', 5.6, 4.6, { yaw: 240 }); put('gold-pile', 4.6, 4.9, { scale: 0.9 });
// west vigil
put('rug', -4.8, -2.4, { yaw: 90 });
put('brazier', -5.6, -4.2); put('brazier', -5.6, 0.4);
put('urn', -3.6, -4.6); put('jar', -6, -2.2);
put('skeleton', -5.2, 1.4, { yaw: 120 });
put('bone-pile', -5.8, 2.5); put('bone-pile', -3.2, 0.8, { yaw: 70 });
put('altar', 5.4, -4.7, { scale: 0.7 }); put('obelisk', -3.4, -5.3, { scale: 0.6 });
// trap corridor from the south gap along x=-4
put('spike-trap', -4, 4.5); put('pressure-plate', -4, 3); put('spike-trap', -4, 1.5); put('pressure-plate', -4, 0.2);
put('urn', -2.8, 4.8); put('jar', -2.9, 3.4); put('urn', -5.2, 4.6); put('jar', -5.3, 3.2);
// sand drifts inside along the walls
put('sand-dune', 5.6, -3.4, { yaw: 90, scale: 0.45 });
put('sand-dune', -6, 4.8, { yaw: 160, scale: 0.45 });
put('sand-dune', 2.4, 5.1, { yaw: 200, scale: 0.4 });
put('rubble', 6, 5, { yaw: 60 }); put('rubble', -6.2, -5, { yaw: 10 });

const tally = {};
for (const p of places) tally[p.asset] = (tally[p.asset] ?? 0) + 1;
const num = (v) => (Number.isInteger(v) ? String(v) : v.toFixed(2).replace(/0+$/, '').replace(/\.$/, ''));
const fmt = (p) => `  { asset: '${p.asset}', at: [${num(p.at[0])}, ${num(p.at[1])}, ${num(p.at[2])}]${p.yaw ? `, yaw: ${p.yaw}` : ''}${p.scale ? `, scale: ${p.scale}` : ''} },`;
writeFileSync('scenes/maps/tomb.ts', `// GENERATED by scripts/design-tomb.mjs — edit the generator, not this file.
import type { Place } from '../chibi-quest.js';
export function places(): Place[] {
  return [
${places.map(fmt).join('\n')}
  ];
}
`);
writeFileSync('docs/map-mockups/tomb.md', `# Ancient tomb map (generated by scripts/design-tomb.mjs)

14 x 12 m sandstone chamber, 7 x 6 desert-ground tiles; the walls are the outer ring of desert-ground
tiles stacked 5 high (1.5 m). Zones: three-step dais with sarcophagus (focal); north wall iron door with
lever and torches; two mummy groups; west vigil; south-west trap corridor from the entry doorway.

Pieces: ${places.length}

${Object.entries(tally).map(([a, n]) => `- ${a}: ${n}`).join('\n')}
`);
console.log(places.length);
