#!/usr/bin/env node
// City district map designer. 14 x 12 tiles of 2 m (28 x 24 m). +X east, -Z north.
// Cell (c,r): x=(c-7.5)*2, z=(r-6.5)*2. Writes scenes/maps/city.ts and docs/map-mockups/city.md.
import { writeFileSync } from 'node:fs';
const X = (c) => (c - 7.5) * 2, Z = (r) => (r - 6.5) * 2;
const places = [];
const put = (asset, x, z, o = {}) => {
  const p = { asset, at: [x, o.y ?? 0, z] };
  if (o.yaw) p.yaw = o.yaw;
  if (o.scale) p.scale = o.scale;
  places.push(p);
};
// ground: cobble streets (outer ring r2/r11-ish lanes, plaza), dirt elsewhere
let cob = 0;
for (let c = 1; c <= 14; c++) for (let r = 1; r <= 12; r++) {
  const x = X(c), z = Z(r);
  const plaza = Math.abs(x) <= 5 && Math.abs(z) <= 5;
  const street = (Math.abs(x) <= 1 && z > 5) || (Math.abs(z) <= 1 && Math.abs(x) > 5) || (Math.abs(x) <= 1 && z < -5);
  const lane = r === 4 || r === 9 ? false : false;
  if (plaza || street || lane) { put('cobble-floor', x, z); cob++; }
  else put(((c * 3 + r) % 7 === 0) ? 'grass-ground' : 'dirt-ground', x, z);
}
// north row of townhouses facing south, tower NW
put('tower', -11.6, -9.6, { yaw: 0, scale: 1.3 });
for (const [x, s] of [[-7.4, 1], [-3, 1], [1.4, 1], [5.8, 1], [10.2, 1]]) put('townhouse', x, -9.4, { scale: s });
// second tower NE-center, cottages behind plaza row
put('tower', 11.8, 9.6, { scale: 1.15 });
// west row facing east
for (const z of [-3.4, 1, 5.4, 9.6]) put('townhouse', -11.4, z, { yaw: 90 });
// east row facing west
for (const z of [-3.4, 1.0, 5.4]) put('townhouse', 11.4, z, { yaw: 270 });
// south row: cottages facing north, gate at south center
for (const x of [-9, -5.5, 5.5, 9]) put('cottage', x, 10.6, { yaw: 180, scale: 1.2 });
put('wall-gate', 0, 11.4, { yaw: 180 });
put('city-wall', -3.3, 11.8, { yaw: 180 }); put('city-wall', 3.3, 11.8, { yaw: 180 });
// plaza
put('fountain', 0, 0, { scale: 1.5 });
for (const [x, z] of [[-3.2, -3.2], [3.2, -3.2], [-3.2, 3.2], [3.2, 3.2]]) put('lantern', x, z);
put('statue', 0, -4, { scale: 0.8 });
put('market-tent', -3.5, 0.5, { yaw: 90 }); put('market-tent', 3.6, 0.8, { yaw: 270 });
put('market-tent', -3.0, 4.2, { yaw: 180 }); put('market-tent', 3.2, -3.4, { yaw: 0 });
put('market-cart', 2.2, 3.6, { yaw: 30 }); put('market-cart', -2.2, -2, { yaw: 200 });
put('market-cart', 7.5, 0.8, { yaw: 90 }); put('market-cart', -7.5, -0.8, { yaw: 270 });
put('well', 7, -5, { yaw: 20 });
put('bench', -1.5, 5.2, { yaw: 180 }); put('bench', 1.5, -5.4, { yaw: 0 });
for (const [x, z] of [[-1.2, -6], [1.2, -6], [-1.2, 8], [1.2, 8], [-6.5, 1.6], [6.5, -1.6]]) put('lantern', x, z);
put('banner', -5, -5.6); put('banner', 5, -5.6); put('banner', -1.8, 9.6); put('banner', 1.8, 9.6);
// dressing
for (const [a, x, z, y] of [['barrel', -9, -6.4, 0], ['barrel', -8.4, -6.8, 40], ['crate', 8.6, -6.6, 15], ['crate', 9.2, -6.2, 70],
  ['barrel', 8.8, 6.4, 0], ['crate', -8.8, 7, 30], ['sack', -9, 3.6, 0], ['sack', 8.8, 3.4, 90], ['hay-bale', 9, 8.2, 20],
  ['barrel', -6.2, 7.8, 0], ['crate', 6.4, 7.8, 50], ['bush', -9.4, -1.8, 0], ['bush', 9.4, -1.8, 90], ['bush', -6, 6.4, 0],
  ['bush', 6.2, 5.6, 40], ['signpost', 2.2, 7.4, 180], ['bench', -8.4, 1.8, 90], ['bench', 8.4, -1.4, 270],
  ['shop-stall', -6.4, -3, 0], ['shop-stall', 6.4, 3.4, 180], ['torch-sconce', -2, 10.2, 0]]) put(a, x, z, { yaw: y });
for (const x of [-12.6, 12.6]) for (const z of [-11, 11]) put('oak-tree', x, z, { scale: 0.7 });

const tally = {}; for (const p of places) tally[p.asset] = (tally[p.asset] ?? 0) + 1;
const body = places.map((p) => '  ' + JSON.stringify(p).replace(/"(\w+)":/g, '$1:').replace(/"/g, "'") + ',').join('\n');
writeFileSync(new URL('../scenes/maps/city.ts', import.meta.url),
`// GENERATED by scripts/design-city.mjs — edit the generator, not this file.
import type { Place } from '../chibi-quest.js';
export function places(): Place[] {
  return [
${body}
  ];
}
`);
writeFileSync(new URL('../docs/map-mockups/city.md', import.meta.url),
`# City map

28 x 24 m district, ${places.length} placements. Plaza (cobble, fountain, tents, carts) at center; north row of townhouses with a tower at NW; west and east townhouse rows; south gate with cottages. Streets of cobble-floor run N, E, W, S from the plaza.

## Tally
${Object.entries(tally).map(([k, v]) => `- ${k}: ${v}`).join('\n')}
`);
console.log(places.length, tally);
