#!/usr/bin/env node
// Rocky coast map designer: 12 x 9 tiles of 2 m (24 m x 18 m), all desert-ground sand.
// Two scaled-up ponds form the sea bay on the south (river tiles always show grass banks).
// Focal: tower as lighthouse + cottage on the NE headland. Writes scenes/maps/coast.ts and
// docs/map-mockups/coast.md. Cell (c,r): x = (c-6.5)*2, z = (r-5)*2.
import { writeFileSync } from 'node:fs';

const X = (c) => (c - 6.5) * 2;
const Z = (r) => (r - 5) * 2;
const places = [];
const put = (asset, x, z, o = {}) => {
  const p = { asset, at: [x, o.y ?? 0, z] };
  if (o.yaw) p.yaw = o.yaw;
  if (o.scale) p.scale = o.scale;
  places.push(p);
};
for (let c = 1; c <= 12; c++) for (let r = 1; r <= 9; r++) put('desert-ground', X(c), Z(r));

// --- sea: two big ponds on the south ---------------------------------------------------
put('pond', -6.2, 5.2, { scale: 3.8 });
put('pond', 5.2, 5.2, { scale: 3.8, yaw: 180 });

// --- pier going diagonally into the west bay, rowboat at its end -------------------------
put('dock', -4.3, 4.0, { yaw: 135 });
put('dock', -6.4, 6.1, { yaw: 135 });
put('rowboat', -8.0, 6.9, { yaw: 135, y: 0.05 });
put('barrel', -2.4, 2.0, { yaw: 30 });
put('crate', -1.8, 1.7, { yaw: 15 });
put('crate', -2.8, 1.6, { yaw: 70, scale: 0.9 });

// --- headland: lighthouse and cottage ---------------------------------------------------
put('tower', 4.4, -4.6, { scale: 1.4, yaw: 200 });
put('cottage', 7.6, -3.4, { yaw: 250, scale: 0.7 });
put('boulder', 1.8, -6.6, { yaw: 30, scale: 1.3 });
put('rock-cluster', 2.8, -7.4, { yaw: 60, scale: 1.5 });
put('boulder', 7.2, -6.6, { yaw: 120, scale: 1.4 });
put('boulder', 9.8, -5.0, { yaw: 210, scale: 1.2 });
put('boulder', 10.4, -2.8, { yaw: 300, scale: 1.3 });
put('tall-grass', 6.4, -5.2, { yaw: 40 });
put('tall-grass', 3.0, -2.2, { yaw: 200 });

// --- central sand mound -----------------------------------------------------------------
put('sand-dune', -0.6, -1.2, { yaw: 10, scale: 1.8 });
put('sand-dune', 1.6, -0.6, { yaw: 80, scale: 1.4 });
put('sand-dune', -2.4, -0.4, { yaw: 160, scale: 1.2 });
put('tall-grass', -0.6, 0.6, { yaw: 100 });
put('tall-grass', 1.4, 0.8, { yaw: 250 });

// --- loose palm group (NW) and two on the east --------------------------------------------
put('palm-tree', -7.4, -4.8, { yaw: 30, scale: 1.2 });
put('palm-tree', -5.2, -3.6, { yaw: 200, scale: 1.0 });
put('palm-tree', -9.2, -2.6, { yaw: 120, scale: 1.0 });
put('palm-tree', 8.0, 0.2, { yaw: 300, scale: 1.1 });
put('boulder', -4.2, -6.6, { yaw: 80, scale: 1.2 });
put('rock-cluster', -9.8, -6.2, { yaw: 150, scale: 1.3 });
put('boulder', -10.8, -0.4, { yaw: 10, scale: 1.3 });
put('tall-grass', -6.4, -2.2, { yaw: 20 });
put('tall-grass', -8.2, -0.8, { yaw: 110 });
put('stump', -8.0, 0.8, { yaw: 200 });

// --- tight rock stack on the east shore --------------------------------------------------
put('boulder', 10.2, 2.0, { yaw: 20, scale: 2.2 });
put('boulder', 9.6, 3.8, { yaw: 100, scale: 1.9 });
put('boulder', 10.8, 0.6, { yaw: 250, scale: 1.8 });
put('rock-cluster', 9.2, 1.4, { yaw: 70, scale: 1.6 });
put('boulder', 8.6, 3.0, { yaw: 160, scale: 1.4 });

// --- shore dressing (two groups at the water line) -----------------------------------------
put('fishing-net', -0.9, 3.4, { yaw: 200 });
put('log', 0.0, 4.4, { yaw: 25 });
put('coral', -1.0, 7.6, { yaw: 10 });
[[-1.4, 4.6], [-0.4, 5.6], [0.4, 3.0], [-1.6, 6.4]].forEach(([x, z], i) => put('shell', x, z, { yaw: i * 61 }));
put('rowboat', -0.3, 6.6, { yaw: 5, scale: 1.0 });
put('log', 0.6, 8.0, { yaw: 115, scale: 0.8 });
put('fallen-log', 3.4, 1.4, { yaw: 60, scale: 0.6 });
put('coral', 0.3, 7.4, { yaw: 150 });
[[-0.2, 2.2], [0.2, 5.2], [-1.2, 7.2], [0.4, 8.4]].forEach(([x, z], i) => put('shell', x, z, { yaw: i * 83 }));
put('river-rock', -4.4, 1.4, { yaw: 60, scale: 1.2 });
put('river-rock', 4.8, 1.8, { yaw: 140 });
put('campfire', -3.4, 0.4, { scale: 0.8 });
put('rope-coil', -3.0, 2.3, { yaw: 40 });

const glyph = Array.from({ length: 9 }, () => Array(12).fill('.'));
const mark = (x, z, g) => { const c = Math.round(x / 2 + 6.5), r = Math.round(z / 2 + 5); if (c >= 1 && c <= 12 && r >= 1 && r <= 9) glyph[r - 1][c - 1] = g; };
mark(-6, 5.8, '~'); mark(-8, 5.8, '~'); mark(-4, 5.8, '~'); mark(5, 5.8, '~'); mark(3, 5.8, '~'); mark(7, 5.8, '~');
mark(4.4, -4.6, 'L'); mark(-4.3, 4.7, 'P'); mark(1.8, 3.6, 'B'); mark(10, 2, 'R'); mark(-7.4, -4.8, 'T'); mark(-0.6, -1.2, 'M');
console.log(glyph.map((r) => '  ' + r.join(' ')).join('\n'));

const num = (v) => (Number.isInteger(v) ? String(v) : v.toFixed(2).replace(/0+$/, '').replace(/\.$/, ''));
const fmt = (p) => `  { asset: '${p.asset}', at: [${num(p.at[0])}, ${num(p.at[1])}, ${num(p.at[2])}]${p.yaw ? `, yaw: ${p.yaw}` : ''}${p.scale ? `, scale: ${p.scale}` : ''} },`;
writeFileSync('scenes/maps/coast.ts', `// GENERATED by scripts/design-coast.mjs — edit the generator, not this file.
import type { Place } from '../chibi-quest.js';
export function places(): Place[] {
  return [
${places.map(fmt).join('\n')}
  ];
}
`);
const tally = {};
for (const p of places) tally[p.asset] = (tally[p.asset] ?? 0) + 1;
writeFileSync('docs/map-mockups/coast.md', `# Rocky coast map (generated)

GENERATED by \`scripts/design-coast.mjs\`. 12 x 9 sand tiles of 2 m (24 m x 18 m). x = (c-6.5)*2, z = (r-5)*2.

\`\`\`
${glyph.map((r) => '  ' + r.join(' ')).join('\n')}
\`\`\`
~ bay (pond scaled 4)  L lighthouse (tower x1.4) + cottage  P diagonal pier  B beached rowboat  R rock stack  T palms  M sand mound

## Layout
Sand beach; a two-lobe sea bay on the south built from scaled ponds (river tiles show grass banks).
Lighthouse and cottage on the north-east headland, palms north-west, sand mound centre, rock stack
east, a diagonal pier with a rowboat at its end in the west bay. Two shoreline groups of shells,
coral, driftwood and a net sit at the water line.

## Tally
| piece | count |
|---|---|
${Object.entries(tally).sort((a, b) => b[1] - a[1]).map(([k, v]) => `| ${k} | ${v} |`).join('\n')}

Total: ${places.length}
`);
console.log('wrote', places.length, 'places');
