#!/usr/bin/env node
// Gladiator arena map designer (civic, sunny). One sand ground family (desert-ground) over a
// 12 x 10 tile footprint (24 m x 20 m). Stepped stands of stone-floor stacks ring a sand pit;
// a low stone wall rings the stands; two gates sit at the east/west ends; podium and statue
// stand in the middle. Writes scenes/maps/arena.ts and docs/map-mockups/arena.md.
import { writeFileSync } from 'node:fs';

const COLS = 12, ROWS = 10;
const X = (c) => (c - (COLS + 1) / 2) * 2;
const Z = (r) => (r - (ROWS + 1) / 2) * 2;
const A = 11, B = 9.2; // stand ellipse semi-axes
const nrm = (x, z) => Math.hypot(x / A, z / B);

let seed = 7;
const rnd = () => ((seed = (seed * 16807) % 2147483647) / 2147483647);

const places = [];
const put = (asset, x, y, z, o = {}) => {
  const p = { asset, at: [x, y, z] };
  if (o.yaw) p.yaw = Math.round(o.yaw);
  if (o.scale) p.scale = o.scale;
  places.push(p);
};
const faceCenter = (x, z) => ((Math.atan2(-x, -z) * 180) / Math.PI + 360) % 360;

const tally = {};
const level = (x, z) => {
  if (Math.abs(z) < 2.1 && Math.abs(x) > 4) return 0; // gate aisles
  const n = nrm(x, z);
  if (n < 0.55 || n > 0.97) return 0;
  if (n < 0.7) return 1;
  if (n < 0.83) return 2;
  return 3;
};
const tiers = [];
for (let c = 1; c <= COLS; c++)
  for (let r = 1; r <= ROWS; r++) {
    const x = X(c), z = Z(r);
    put(nrm(x, z) < 0.55 || (Math.abs(z) < 2.1 && Math.abs(x) > 4 && Math.abs(x) < 10.5) ? 'dirt-ground' : 'desert-ground', x, 0, z);
    const L = level(x, z);
    for (let k = 0; k < L; k++) put('desert-ground', x, 0.3 * k + 0.3, z);
    if (L) tiers.push([x, z, L]);
  }

// podium + statue
for (const dx of [-1, 1]) for (const dz of [-1, 1]) put('desert-ground', dx, 0.3, dz);
put('statue', 0, 0.6, 0, { scale: 0.7 });

// ring wall
const WA = 11.3, WB = 9.5;
const rampartT = [Math.PI / 4, (3 * Math.PI) / 4, (5 * Math.PI) / 4, (7 * Math.PI) / 4];
const pt = (t) => [WA * Math.cos(t), WB * Math.sin(t)];
const ramp = rampartT.map(pt);
for (let t = 0; t < Math.PI * 2; ) {
  const [x, z] = pt(t);
  const dt = 2 / Math.hypot(WA * Math.sin(t), WB * Math.cos(t));
  const tm = t + dt / 2;
  const [mx, mz] = pt(tm);
  const gate = Math.abs(mz) < 2.6 && Math.abs(mx) > 8;
  const nearRamp = false;
  if (!gate && !nearRamp) {
    const tx = -WA * Math.sin(tm), tz = WB * Math.cos(tm);
    for (const wy of [0, 1.5]) put('plaster-wall', mx, wy, mz, { yaw: (Math.atan2(-tz, tx) * 180) / Math.PI });
  }
  t += dt;
}
// gates, flanks, banners, torches
for (const s of [-1, 1]) {
  const gx = s * WA;
  put('archway', gx, 0, 0, { yaw: s > 0 ? 90 : 270, scale: 1.3 });
  for (const dz of [-1.6, 1.6]) {
    put('column', gx, 0, dz);
  }
  put('banner', gx + s * 0.9, 0, -4.6, { yaw: s > 0 ? 90 : 270 });
  put('banner', gx + s * 0.9, 0, 4.6, { yaw: s > 0 ? 90 : 270 });
  put('guard', s * 9.0, 0, -1.2, { yaw: s > 0 ? 270 : 90 });
  put('guard', s * 9.0, 0, 1.2, { yaw: s > 0 ? 270 : 90 });
}
// crowds on the tiers
for (const [x, z, L] of tiers) {
  const n = rnd() < 0.62 ? 1 : 0;
  for (let i = 0; i < n + (L === 3 && rnd() < 0.4 ? 1 : 0); i++) {
    const px = x + (rnd() - 0.5) * 1.2, pz = z + (rnd() - 0.5) * 1.2;
    put(rnd() < 0.8 ? 'villager' : 'guard', px, 0.3 * L, pz, { yaw: faceCenter(px, pz) });
  }
}
// duel in the pit + weapon table at the west pit edge
put('gladiator', -2.6, 0, 2.4, { yaw: 55 });
put('gladiator', 2.6, 0, -2.4, { yaw: 235 });
put('bench', -8.4, 0, -3.0, { yaw: 0 });
put('gladiator-sword', -8.9, 0.35, -3.0);
put('gladiator-shield', -8.4, 0.35, -3.0);
put('gladiator-helmet', -7.9, 0.35, -3.0);

const num = (v) => (Number.isInteger(v) ? String(v) : v.toFixed(2).replace(/0+$/, '').replace(/\.$/, ''));
const fmt = (p) => `  { asset: '${p.asset}', at: [${num(p.at[0])}, ${num(p.at[1])}, ${num(p.at[2])}]${p.yaw ? `, yaw: ${p.yaw}` : ''}${p.scale ? `, scale: ${p.scale}` : ''} },`;
writeFileSync('scenes/maps/arena.ts', `// GENERATED by scripts/design-arena.mjs — edit the generator, not this file.
import type { Place } from '../chibi-quest.js';
export function places(): Place[] {
  return [
${places.map(fmt).join('\n')}
  ];
}
`);
for (const p of places) tally[p.asset] = (tally[p.asset] ?? 0) + 1;
writeFileSync('docs/map-mockups/arena.md', `# Arena map plan (generated)

GENERATED by \`scripts/design-arena.mjs\`.

24 m x 20 m of desert-ground (12 x 10 tiles). A sand pit (ellipse) sits in the middle with a
stone podium and statue and a gladiator duel. Three rings of stepped stone-floor stands (1 to 3
tiles high) carry small crowds. A stone-wall ring closes the stands, with four rampart corner
towers and two wall-gates (east and west) with columns, torches, banners, and guards. Flags
stand at the corners; a bench by the pit holds sword, shield, and helmet.

| piece | count |
|-------|-------|
${Object.entries(tally).sort((a, b) => b[1] - a[1]).map(([k, v]) => `| ${k} | ${v} |`).join('\n')}

Total: ${places.length}.
`);
console.log(places.length, JSON.stringify(tally));
