#!/usr/bin/env node
// Village school map designer. Room x -6..6, z -5..5 (12 m x 10 m), cutaway: walls on
// north (z=-5) and west (x=-6). Students (yaw 180) face the teacher desk and notice-board on the north.
// Writes scenes/maps/school.ts and docs/map-mockups/school.md.
import { writeFileSync } from 'node:fs';

const places = [];
const put = (asset, x, z, o = {}) => {
  const p = { asset, at: [x, o.y ?? 0, z] };
  if (o.yaw) p.yaw = o.yaw;
  if (o.scale) p.scale = o.scale;
  places.push(p);
};

// Floor: one family, 6 x 5 tiles of 2 m
for (let x = -5; x <= 5; x += 2) for (let z = -4; z <= 4; z += 2) put('wood-floor', x, z);

// Walls
for (const x of [-5, -3, -1, 1, 3, 5]) put(x === 3 ? 'plaster-wall-window' : 'plaster-wall', x, -5);
for (const z of [-4, -2, 0, 2, 4]) put(z === 4 ? 'plaster-wall-door' : 'plaster-wall', -6, z, { yaw: 90 });

// North wall: bookcase corner, teacher area, notice-board, window
put('bookcase', -5.3, -4.7);
put('bookcase', -4.1, -4.7);
put('tapestry', -0.5, -4.93, { y: 0.2 });
put('tapestry', -2.2, -4.93, { y: 0.2 });
put('notice-board', 1.4, -4.5);
put('bookshelf', 5.3, -4.75);
put('cabinet', 4.1, -4.7);
put('jar', 4.1, -4.7, { y: 1.1 });
put('fern', 5.5, -3.4, { scale: 0.8 });
put('lectern', -2.7, -3.9);
put('scroll', -2.7, -3.9, { y: 1.2 });
// Teacher desk
put('desk', -0.5, -3.2, { scale: 1.5 });
put('chair', -0.5, -4.0);
put('tome', -1.0, -3.2, { y: 1.12, yaw: 20 });
put('scroll', 0.1, -3.2, { y: 1.12, yaw: 80 });
put('candle', -0.3, -3.35, { y: 1.12 });
put('apple', 0.35, -3.1, { y: 1.12 });
put('mug', -0.75, -3.4, { y: 1.12 });

// West wall: shelves, orb on cabinet, reading corner, door
put('bookshelf', -5.65, -2.7, { yaw: 90 });
put('bookshelf', -5.65, -1.6, { yaw: 90 });
put('cabinet', -5.6, -0.4, { yaw: 90 });
put('orb', -5.6, -0.4, { y: 1.1, scale: 2 });
put('tapestry', -5.93, 1.9, { y: 0.2, yaw: 90 });
put('bench', -5.55, 1.9, { yaw: 90 });
put('rug', -4.4, 1.9, { yaw: 90, scale: 1.5 });
put('stool', -4.2, 1.0);
put('stool', -4.2, 2.8);
put('tome', -4.5, 1.5, { y: 0.03, yaw: 30 });
put('tome', -4.6, 2.3, { y: 0.03, yaw: 100 });
put('tome', -5.55, 1.5, { y: 0.35, yaw: 90 });
put('tome', -5.55, 2.3, { y: 0.35, yaw: 70 });
put('scroll', -5.55, 1.9, { y: 0.35, yaw: 90 });
put('fern', -5.5, 0.55, { scale: 0.7 });
// Entrance, door at z=4
put('lantern', -5.2, 3.2, { scale: 0.7 });
put('barrel', -5.5, 4.65, { scale: 0.7 });
put('bucket', -4.8, 4.7);
put('bench', -5.6, 3.35, { yaw: 90 });
put('sack', -5.5, 3.35, { y: 0.35, scale: 0.5 });
put('torch-sconce', -5.95, 3.2, { y: 0.2, yaw: 90, scale: 0.7 });

// Desk rows facing north
const cols = [-2, 0, 2, 4];
const rows = [-1.0, 0.8, 2.6, 4.2];
let k = 0;
for (const z of rows) for (const x of cols) {
  if (z === 4.2 && x === -2) continue; // aisle from the door
  put('desk', x, z, { yaw: 180 });
  put('stool', x, z + 0.62);
  const j = k++;
  if (j % 2 === 1) put('scroll', x + 0.3, z + 0.05, { y: 0.75, yaw: 175 });
  if (j % 2 === 0) put('tome', x - 0.3, z + 0.1, { y: 0.75, yaw: 170 });
}
// East edge: low dressing seen from the cutaway side
put('bench', 5.7, -1.2, { yaw: 90 });
put('bench', 5.7, 1.2, { yaw: 90 });
put('basket', 5.75, 3.2, { scale: 0.8 });
put('basket', 5.75, -2.4, { scale: 0.7 });
put('tome', 5.7, -1.2, { y: 0.35, yaw: 90 });
put('tome', 5.7, 1.2, { y: 0.35, yaw: 80 });
put('fern', 5.7, 4.5, { scale: 0.8 });

// Extra dressing against walls and the teacher area
put('rug', -0.5, -2.35, { scale: 1.4 });
put('torch-sconce', -3.4, -4.93, { y: 0.35 });
put('torch-sconce', 0.7, -4.93, { y: 0.35 });
put('torch-sconce', -5.93, -0.9, { y: 0.35, yaw: 90 });
put('wildflowers', 3.0, -4.5, { scale: 0.8 });
put('wildflowers', -3.3, -4.5, { scale: 0.7 });
put('wildflowers', 5.6, 0.0, { scale: 0.8 });
put('wildflowers', -5.5, 4.0, { scale: 0.6 });
put('tome', -3.4, -3.7, { y: 0.03, yaw: 20 });
put('tome', -3.4, -3.7, { y: 0.11, yaw: 50 });
put('tome', 5.0, -3.8, { y: 0.03, yaw: 70 });
put('tome', 5.0, -3.8, { y: 0.11, yaw: 100 });
put('apple', 4.4, -4.7, { y: 1.1 });
put('mug', -5.6, 0.1, { y: 1.1, scale: 1 });
put('scroll', -5.6, -0.8, { y: 1.1, yaw: 90 });
put('stool', 5.2, -1.2);
put('stool', 5.2, 1.2);
put('jar', -2.9, -3.9, { y: 0 });
put('basket', 3.5, -4.4, { scale: 0.8 });
put('sack', 2.7, -4.5, { scale: 0.7 });
put('fern', -3.5, 4.7, { scale: 0.7 });
put('fern', 1.0, 4.8, { scale: 0.7 });
put('basket', 3.2, 4.8, { scale: 0.7 });

// ---- output -----
const num = (n) => Number(n.toFixed(2));
const lines = places.map((p) => `  { asset: '${p.asset}', at: [${p.at.map(num).join(', ')}]${p.yaw ? `, yaw: ${p.yaw}` : ''}${p.scale ? `, scale: ${p.scale}` : ''} },`);
writeFileSync('scenes/maps/school.ts', `// GENERATED by scripts/design-school.mjs — edit the generator, not this file.
import type { Place } from '../chibi-quest.js';
export function places(): Place[] {
  return [
${lines.join('\n')}
  ];
}
`);
const tally = {};
for (const p of places) tally[p.asset] = (tally[p.asset] ?? 0) + 1;
writeFileSync('docs/map-mockups/school.md', `# School (12 m x 10 m cutaway classroom)

## Layout
- Floor: 30 wood-floor tiles. Walls on the north and west sides; window north-east, door west (z=4).
- Teacher end (north): teacher desk, chair, lectern, notice-board, two tapestries, bookcases, cabinet.
- Centre: ${k} small desks with stools in four rows facing north, a book or scroll and a candle on each.
- West: bookshelf wall, orb on a cabinet (focal), reading corner with rug, bench, stools and tomes.
- Entrance (SW): door, lantern, sconce, barrel, bucket, bench with a sack. No bell or coat hooks exist.

## Tally (${places.length} placements)
${Object.entries(tally).map(([a, n]) => `- ${a}: ${n}`).join('\n')}
`);
console.log('placements', places.length);
