#!/usr/bin/env node
// Glacier map designer: 12 x 10 tiles of 2 m (24 m x 20 m). Writes scenes/maps/glacier.ts and docs/map-mockups/glacier.md.
// Cell (c,r) center: x = (c-5.5)*2, z = (r-4.5)*2, c 1..12, r 1..10. +X east, -Z north.
// Anchor: docs/map-mockups/glacier.jpg. A frozen lake fills the south-west, a crevasse of water
// tiles runs north from it to the centre, and a bridge crosses the crevasse.
import { writeFileSync } from 'node:fs';

const X = (c) => (c - 6.5) * 2;
const Z = (r) => (r - 5.5) * 2;
const places = [];
const tally = {};
const put = (asset, x, z, o = {}) => {
  const p = { asset, at: [x, o.y ?? 0, z] };
  if (o.yaw) p.yaw = o.yaw;
  if (o.scale) p.scale = o.scale;
  places.push(p);
  tally[asset] = (tally[asset] || 0) + 1;
};

// water cells: lake (c1..6, r6..10 irregular) + crevasse column c7 up to r4 (+ c6 at r5)
const water = new Set();
for (let c = 1; c <= 6; c++)
  for (let r = 6; r <= 10; r++) {
    if (r === 6 && c < 3) continue; // snow shelf on the north-west of the lake
    if (c === 1 && r < 8) continue;
    water.add(`${c},${r}`);
  }
for (let r = 3; r <= 10; r++) water.add(`7,${r}`);
water.add('8,10');

const ice = new Set(['9,4','10,5','9,8','11,8','3,4','2,3','11,2','5,3']); // glossy ice patches
const ascii = [];
for (let r = 1; r <= 10; r++) {
  let row = '';
  for (let c = 1; c <= 12; c++) {
    const w = water.has(`${c},${r}`);
    row += w ? '~' : ice.has(`${c},${r}`) ? ':' : '.';
    put(w || ice.has(`${c},${r}`) ? 'ice-ground' : 'snow-ground', X(c), Z(r));
  }
  ascii.push(row);
}

// focal bridge across the crevasse (span along X, centred on column 7 at r4/r5 boundary)
put('bridge', X(7), Z(4), { yaw: 0, scale: 1.0 });
// mountaineer camp NE
put('tent', 8.2, -5.6, { yaw: 200, scale: 1.5 });
put('campfire', 6.0, -4.2, { scale: 1.2 });
put('barrel', 9.9, -4.2, { scale: 0.9 });
put('crate', 10.0, -3.2, { yaw: 20 });
put('crate', 9.5, -3.0, { yaw: 60, scale: 0.7 });
put('rope-coil', 5.6, -2.2, { yaw: 40 });
put('lantern', 6.9, -6.4, { scale: 0.9 });

// pines along the north and east edges
const pines = [[-9.5,-8.6,0.9],[-6.5,-8.8,0.7],[-3.2,-8.5,1.0],[-0.5,-8.9,0.75],[2.4,-8.6,1.0],[5.2,-8.8,0.8],[8.0,-8.6,1.1],[10.6,-8.4,0.9],
  [11.2,-5.6,0.8],[11.0,-1.8,0.7],[11.3,1.6,0.6],[-11,-5,0.7],[-10.8,-1.8,0.6],[10.8,5.5,0.55],[3.5,-6.6,0.55]];
pines.forEach(([x, z, s], i) => put('pine-tree', x, z, { yaw: i * 47, scale: s * 0.8 }));

// ice spires: crystals scattered on both banks, small
const spires = [[-9,-4,0.45],[-7.2,-3.4,0.4],[-4.5,-4.5,0.5],[-2.8,-1.4,0.35],[2.5,-1.0,0.4],[3.4,-3.8,0.55],[9.0,0.6,0.45],
  [5.5,3.5,0.4],[8.5,6.5,0.5],[1.8,6.5,0.35],[-10.2,0.3,0.5],[-5,-0.6,0.4],[11,-7,0.4],[-1.8,-6.6,0.6]];
spires.forEach(([x, z, s], i) => { put('ice-spire', x, z, { yaw: i * 61, scale: s * 1.6 }); put('ice-spire', x + 0.6, z + 0.4, { yaw: i * 37, scale: s }); });
put('ice-spire', -0.6, -5.0, { scale: 0.9, yaw: 20 }); // big landmark spire north of the crevasse

// snow drifts: ridges that break the flat sheet
const drifts = [[-8.5,-6.5,2.0],[-4,-7,1.8],[1,-7.2,2.2],[7.5,-7.4,1.6],[-9.6,-2.3,1.8],[-3.6,-2.6,1.7],[3.8,-1.6,1.8],
  [9.4,2.2,1.8],[10,7.8,1.6],[4.6,6.8,1.8],[3,8.4,1.6],[8,4.2,1.4],[-9,3.6,1.5],[6.4,-0.2,1.3],[-6.4,-5.3,1.4],[1.8,3,1.4],[-1.6,0.6,1.2]];
drifts.forEach(([x, z, s], i) => put('snowbank', x, z, { yaw: (i % 2 ? 180 : 0) + (i * 23) % 40, scale: s }));

// boulders, shore rock
[[-10.8,3.6,0.9],[4.2,2,0.8],[10.4,3.8,0.9],[1.9,-4.6,0.7],[-6.8,-1.4,0.8],[3.2,9,0.8]].forEach(([x,z,s],i)=>put('boulder',x,z,{yaw:i*70,scale:s}));

const inB = places.every((p) => Math.abs(p.at[0]) <= 12 && Math.abs(p.at[2]) <= 10);
const ts = `// GENERATED by scripts/design-glacier.mjs — edit the generator, not this file.
import type { Place } from '../chibi-quest.js';
export function places(): Place[] {
  return [
${places.map((p) => '    ' + JSON.stringify(p) + ',').join('\n')}
  ];
}
`;
writeFileSync('scenes/maps/glacier.ts', ts);
writeFileSync('docs/map-mockups/glacier.md', `# Glacier map

24 m x 20 m, 12 x 10 tiles. \`~\` = frozen lake / crevasse (ice-ground tile), \`.\` = snow.

\`\`\`
${ascii.join('\n')}
\`\`\`

A frozen lake fills the south-west. A crevasse runs north from it; the bridge crosses it at the centre.
The mountaineer camp (tent, fire, barrel, crates, rope) stands north-east. Pines line the north and east edges.
Ice spires (small), snowbanks, and boulders dress the sheet.

Notes: the ice colour variant of rock-wall is not used (Place has no variant field). 

## Tally

| piece | count |
|---|---|
${Object.entries(tally).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`| ${k} | ${v} |`).join('\n')}

Total: ${places.length}.
`);
console.log(places.length, 'places; in bounds', inB);
