#!/usr/bin/env node
// Temple map designer: 14 m x 12 m cutaway hall. Nave runs N-S, altar apse on the north (-Z),
// entry on the south. Floor grid 7 x 6 tiles of 2 m, x -7..7, z -6..6. North and west walls
// are full height (2.4 m, the apse wall 3.6 m); east and south edges stay open (cutaway).
import { writeFileSync } from 'node:fs';
const places = [];
const put = (asset, x, y, z, o = {}) => {
  const p = { asset, at: [+x.toFixed(3), +y.toFixed(3), +z.toFixed(3)] };
  if (o.yaw) p.yaw = o.yaw;
  if (o.scale) p.scale = o.scale;
  places.push(p);
};
// floor
for (let i = 0; i < 7; i++) for (let j = 0; j < 6; j++) put('stone-floor', -6 + 2 * i, 0, -5 + 2 * j);
// altar dais (top 0.3) and entry step (top 0.15)
for (const x of [-4, -2, 0, 2, 4]) put('stone-floor', x, 0.3, -5);
for (const x of [-2, 0, 2]) put('stone-floor', x, 0.15, -3);
// north wall: 2 layers across, third layer behind the apse
for (let i = 0; i < 7; i++) {
  const x = -6 + 2 * i;
  put('wall', x, 0, -5.78); put('wall', x, 1.2, -5.78);
  if (Math.abs(x) <= 4) put('wall', x, 2.4, -5.78);
}
// west wall
for (let j = 0; j < 6; j++) { const z = -5 + 2 * j; put('wall', -6.78, 0, z, { yaw: 90 }); put('wall', -6.78, 1.2, z, { yaw: 90 }); }
// windows
put('stained-glass-window', 0, 0.5, -5.5, { scale: 1.3 });
for (const x of [-4.4, 4.4]) put('stained-glass-window', x, 0.4, -5.52);
for (const z of [-3, 0, 3]) put('stained-glass-window', -6.52, 0.4, z, { yaw: 90 });
// banners on the apse wall and west wall
for (const x of [-2.6, 2.6]) put('banner', x, 0.45, -5.3);
// columns: corner, flanks, aisle rows
put('column', -6.7, 0, -5.7); put('column', 6.7, 0, -5.7);
for (const s of [-1, 1]) {
  for (const z of [-1.5, 1.5, 4.5]) put('column', s * 6.3, 0, z);
  put('column', s * 3.2, 0.3, -3.9);
  put('column', s * 6.7, 0, 5.7);
}
// altar group
put('altar', 0, 0.3, -4.9);
put('candle-cluster', -0.4, 1.33, -4.9); put('candle-cluster', 0.4, 1.33, -4.9);
for (const s of [-1, 1]) { put('candelabra', s * 1.5, 0.3, -5.0); put('brazier', s * 2.5, 0.3, -4.3); }
put('priest', 1.0, 0.3, -4.0);
put('cleric', -2.9, 0.15, -2.4);
// side shrines
for (const s of [-1, 1]) {
  put('statue', s * 5.9, 0, -4.4, { yaw: s * -45 });
  put('brazier', s * 4.9, 0, -3.3);
  put('candle-cluster', s * 6.2, 0, -2.9);
  put('candelabra', s * 6.3, 0, 0);
}
// rug along the aisle (yaw 90 = runs N-S)
for (let k = 0; k < 4; k++) put('rug', 0, 0, -1.65 + 2.2 * k, { yaw: 90, scale: 1.2 });
// pews: 5 rows x 2 each side, facing the altar
for (const z of [-0.6, 0.6, 1.8, 3.0, 4.2]) for (const s of [-1, 1]) for (const x of [2.4, 4.0]) {
  put('bench', s * x, 0, z, { yaw: 180 });
  put('candle-cluster', s * (x + 0.55), 0.36, z);
}
// entry
for (const s of [-1, 1]) { put('brazier', s * 1.9, 0, 5.5); put('candelabra', s * 1.9, 0.86, 5.5); }

const src = `// GENERATED by scripts/design-temple.mjs — edit the generator, not this file.
import type { Place } from '../chibi-quest.js';
export function places(): Place[] { return ${JSON.stringify(places)}; }
`.replace(/\},\{/g, '},\n{');
writeFileSync('scenes/maps/temple.ts', src);
const tally = {};
for (const p of places) tally[p.asset] = (tally[p.asset] ?? 0) + 1;
writeFileSync('docs/map-mockups/temple.md', `# Temple map plan (generated)

GENERATED by \`scripts/design-temple.mjs\`. 14 m x 12 m, floor x -7..7, z -6..6, +X east, -Z north.

Layout: apse dais (top 0.3 m) with altar, candles, priest and a tall stained glass window on the north wall;
a three-step entry slab; a nave with 20 pews and a gold rug aisle; side shrines with statues, braziers and
candles; stone columns along both sides; west wall with three windows; open east and south edges (cutaway).

Total placements: ${places.length}

Tally: ${Object.entries(tally).map(([k, v]) => k + ' ' + v).join(', ')}
`);
console.log(places.length, JSON.stringify(tally));
