#!/usr/bin/env node
// Theater map generator: 16 x 12 m, stage north, benches, red aisle, balcony south.
// Writes scenes/maps/theater.ts and docs/map-mockups/theater.md.
import { writeFileSync } from 'node:fs';

const places = [];
const tally = {};
const put = (asset, x, y, z, yaw = 0, scale) => {
  const p = { asset, at: [+x.toFixed(3), +y.toFixed(3), +z.toFixed(3)] };
  if (yaw) p.yaw = yaw;
  if (scale) p.scale = scale;
  places.push(p);
  tally[asset] = (tally[asset] || 0) + 1;
};
const S = 0.3; // stage height
const xs = [-7, -5, -3, -1, 1, 3, 5, 7];

// Floors: stage rows (north), stone audience, marble lobby (south).
for (const x of xs) for (const z of [-5, -3]) put('wood-floor', x, S, z);
for (const x of xs) for (const z of [-5, -3]) put('stone-floor', x, 0, z); // under-stage base
for (const x of xs) for (const z of [-1, 1, 3]) put('stone-floor', x, 0, z);
for (const x of xs) put('marble-floor', x, 0, 5);

// Walls: north (behind stage) and west, 1.5 m, windows on the west.
for (const x of xs) put(x === -3 || x === 3 ? 'plaster-wall-window' : 'plaster-wall', x, S, -6);
[-5, -3, -1, 1, 3, 5].forEach((z, i) => put(i % 2 ? 'plaster-wall-window' : 'plaster-wall', -8, 0, z, 90));
for (const z of [-5, -3, -1, 1, 3, 5]) put('plaster-wall', -8, 0, z, 90);

// Proscenium columns and curtains.
for (const x of [-5.4, 5.4]) put('column', x, S, -2.4);
for (const x of [-7.4, 7.4]) put('column', x, S, -2.4);
for (const x of [-3.7, -2.2, -0.7, 0.7, 2.2, 3.7]) put('curtain', x, S, -5.7); // backdrop
for (const x of [-4.4, 4.4]) put('curtain', x, S, -2.5, 0);
for (const x of [-6.0, 6.0]) put('curtain', x, S, -2.5, 0);
for (const x of [-5.5, 5.5]) put('banner', x, S, -5.5);
put('banner', 0, S, -5.45, 0, 0.9);

// Stage set and actors.
put('statue', -1.8, S, -4.2, 20, 0.8);
put('statue', 1.6, S, -3.9, -30, 0.7);
put('table', 0.2, S, -4.3);
put('chair', -0.4, S, -3.6, 160);
put('chest', 2.9, S, -4.9, -15);
put('stool', -3.2, S, -3.5);
put('candelabra', -2.9, S, -4.9);
put('candelabra', 3.2, S, -3.2);
put('barrel', -6.6, S, -4.9);
put('barrel', -6.6, S, -4.1, 0, 0.8);
put('crate', 6.5, S, -4.9);
put('crate', 6.5, S, -4.0, 20, 0.7);
put('drum', 4.8, S, -4.7);
put('lute', -4.6, S, -3.0, 40);
put('chest', 5.2, S, -3.4, 10, 0.8);

// Prompter box and red carpet aisle.
put('crate', 0, 0, -1.6, 0, 0.55);
for (const [z, s] of [[-0.3, 1.3], [2.1, 1.3], [3.8, 0.9]]) put('rug', 0, 0, z, 90, s);

// Benches: four per side, six rows.
for (const z of [-0.8, 0, 0.8, 1.6, 2.4, 3.2].map((v, i) => -0.8 + i * 0.8))
  for (const sx of [-1, 1]) for (const x of [2.2, 3.7, 5.2, 6.7]) put('bench', sx * x, 0, z);

// Balcony along the south edge, gap at the entry; chairs and lanterns.
for (const x of [-5.75, -3.45, 3.45, 5.75]) put('balcony', x, 0, 4.6, 0);
for (const x of [-7, 7]) put('railing', x, 0, 5.4);
for (const x of [-7.4, -2.2, 2.2, 7.4]) put('lantern', x, 0, 4.0, 0, 0.8);
for (const z of [-1.4, 1.4, 3.8]) put('lantern', 7.6, 0, z, 0, 0.8);
for (const z of [-1.4, 1.4, 3.8]) put('lantern', -7.5, 0, z, 0, 0.8);
for (const x of [-1.2, 1.2]) put('chair', x, 0, 4.6, 180);
put('statue', -7.0, 0, 5.0, 0, 0.7);
put('table', 7.0, 0, 4.9, 0, 0.9);
put('candelabra', 7.0, 0.54, 4.9);
put('banner', -7.5, 0, -1.4, 90, 0.8);
put('banner', -7.6, 0, 2.6, 90, 0.8);

// ASCII map.
const g = Array.from({ length: 12 }, () => Array(16).fill('.'));
for (const p of places) {
  const c = Math.floor(p.at[0] + 8), r = Math.floor(p.at[2] + 6);
  if (r < 0 || r > 11 || c < 0 || c > 15) continue;
  const a = p.asset;
  if (a === 'bench') g[r][c] = 'b';
  else if (a === 'rug') g[r][c] = '=';
  else if (/wall/.test(a)) g[r][c] = '#';
  else if (/curtain|banner/.test(a)) g[r][c] = 'c';
  else if (a === 'balcony') g[r][c] = 'B';
  else if (a === 'lantern') g[r][c] = 'l';
}
const ascii = g.map((r) => r.join('')).join('\n');
console.log(ascii);

writeFileSync(
  'scenes/maps/theater.ts',
  `// GENERATED by scripts/design-theater.mjs — edit the generator, not this file.
import type { Place } from '../chibi-quest.js';
export function places(): Place[] { return ${JSON.stringify(places)}; }
`,
);
const rows = Object.entries(tally).sort().map(([k, v]) => `| ${k} | ${v} |`).join('\n');
writeFileSync(
  'docs/map-mockups/theater.md',
  `# Theater map (16 x 12 m)

Stage (wood, 0.3 m up) on the north 4 m with curtains, columns, banners, statues as actors and props.
Audience: stone floor, 48 benches in two blocks, red rug aisle with a prompter crate at the stage
front. Balcony along the south edge with an entry gap, marble lobby strip. Walls: north and west.
Lanterns line both sides.

\`\`\`
${ascii}
\`\`\`

| piece | count |
|-------|-------|
${rows}

Total: ${places.length} placements.
`,
);
console.log('places', places.length);
