#!/usr/bin/env node
// Mill map designer: riverside watermill, 10x8 tiles of 2 m inside a one-tile ring (12x10 tiles).
// Cell (c,r): x = (c-5.5)*2, z = (r-4.5)*2. River runs N-S on c=8 (x=5); the pond ends at the north.
import { writeFileSync } from 'node:fs';
const X = (c) => (c - 5.5) * 2;
const Z = (r) => (r - 4.5) * 2;
const places = [];
const put = (asset, x, z, o = {}) => {
  const p = { asset, at: [x, o.y ?? 0, z] };
  if (o.yaw) p.yaw = o.yaw;
  if (o.scale) p.scale = o.scale;
  places.push(p);
};
// tiles
for (let c = 0; c <= 11; c++)
  for (let r = 0; r <= 9; r++) {
    const x = X(c), z = Z(r);
    if (c === 8) { put(r === 0 ? 'river-bank' : 'river-straight', x, z); continue; }
    if (c === 6 && r >= 4) { put('dirt-road-straight', x, z); continue; }
    if (r === 6 && c === 7) { put('dirt-road-straight', x, z, { yaw: 90 }); continue; }
    if (c === 5 && r === 3) { put('dirt-road-straight', x, z, { yaw: 90 }); continue; }
    put('grass-ground', x, z);
  }
// focal: watermill, wheel on +X toward the river
put('watermill', 2.2, -3.4);
// bridge over the river, south of the mill
put('bridge', 5, 3);
// mill yard: sacks, barrels, hay, crates
for (const [x, z, y] of [[-0.6, -0.9, 20], [-0.1, -0.7, 80], [0.4, -0.95, 150], [-0.35, -0.3, 40]]) put('sack', x, z, { yaw: y });
put('barrel', 3.9, -0.6, { yaw: 30 }); put('barrel', 3.2, -0.3, { yaw: 120 });
put('crate', -1.7, -1.0, { yaw: 15 });
put('hay-bale', -3.4, -2.8, { yaw: 10 }); put('hay-bale', -3.4, -1.7, { yaw: 350 }); put('hay-bale', -4.6, -2.3, { yaw: 40 });
put('handcart', 8.4 - 0, 4.8, { yaw: 250 });
put('wagon', -6.5, 3.8, { yaw: 70 });
put('farmer', 0.5, 0.2, { yaw: 160 });
// fenced field to the west
for (let i = 0; i < 6; i++) put('fence', -9.2 + i * 1.5, 7.2, { yaw: 0 });
for (let i = 0; i < 4; i++) put('fence', -9.4, 5.6 - i * 1.5, { yaw: 90 });
for (let i = 0; i < 5; i++) for (let j = 0; j < 3; j++) put('wheat-sheaf', -8.2 + i * 1.3, 4.6 + j * 0.8 + (i % 2) * 0.2, { yaw: i * 40 + j * 70 });
// willows by the river
put('willow-tree', 7.2, -5.6, { yaw: 30, scale: 1.2 });
put('willow-tree', 7.0, 1.0, { yaw: 200, scale: 1.1 });
put('willow-tree', 3.2, 6.8, { yaw: 100 });
// edge trees
for (const [x, z, a, s] of [[-10.5, -7.5, 'oak-tree', 1.1], [-8, -8, 'apple-tree', 1], [-5, -8.3, 'oak-tree', 1.0], [-1.5, -8.2, 'birch-tree', 1], [9.6, -7.5, 'oak-tree', 1.1], [10.3, -3, 'birch-tree', 0.95], [10.4, 2.5, 'oak-tree', 1.1], [10.2, 7.6, 'apple-tree', 1], [-10.6, 0, 'birch-tree', 1], [-10.4, 8, 'oak-tree', 1.05]].map(([x, z, a, s]) => [x, z, a, s])) put(a, x, z, { yaw: (x * 37 + z * 11) % 360 | 0, scale: s });
// river dressing
for (const [x, z] of [[4.2, -6.8], [6.0, -3.6], [4.0, -1.2], [6.1, 5.4], [4.1, 7.6], [6.0, 8.4]]) put('reeds', x, z, { yaw: (x * 50 + z * 20) % 360 | 0 });
for (const [x, z] of [[3.9, 1.6], [6.2, 2.0], [3.8, 4.6], [6.3, 6.6]]) put('river-rock', x, z, { yaw: 40 });
// rocks, bushes, grass, flowers
for (const [x, z] of [[-4.2, 0.2], [-2.6, 2.4], [2.6, 3.0], [-0.3, 6.6], [4.8, -6.0]]) put('rock-cluster', x, z, { yaw: (x * 31) % 360 | 0 });
for (const [x, z] of [[-7.2, -5.5], [-6, -6.8], [-2.8, -7], [0.8, -7.2], [8.4, -6.8], [9, 0.2], [9, 4.6], [8.8, 8.4], [-9.5, -2.6], [-9.6, 1.6], [-4.4, 8.6], [-1, 8.5]]) put('bush', x, z, { yaw: (x * 53 + z * 7) % 360 | 0 });
for (let i = 0; i < 26; i++) {
  const x = -9 + ((i * 7.3) % 12.5) + (i % 3) * 0.3, z = -7.2 + ((i * 5.9) % 15);
  if (Math.abs(x - 1.0) < 0.9 && z > -1.5) continue;
  if (Math.abs(x - 5) < 1.4 || (x > -2 && x < 3.2 && z > -5.7 && z < -1.8)) continue;
  put(i % 3 === 0 ? 'wildflowers' : 'tall-grass', x, z, { yaw: i * 47 % 360 });
}
put('signpost', 1.9, 7.4, { yaw: 190 });
put('lantern', 0.5, -0.9);
put('tree-stump', -2.2, 5.2, { yaw: 40 });
put('well', -2.6, -5.8, { yaw: 0 });
put('villager', 3.0, 5.2, { yaw: 180 });
const fmt = (p) => { const n = (v) => +v.toFixed(2); return `  { asset: '${p.asset}', at: [${n(p.at[0])}, ${n(p.at[1])}, ${n(p.at[2])}]${p.yaw ? `, yaw: ${p.yaw}` : ''}${p.scale ? `, scale: ${p.scale}` : ''} },`; };
writeFileSync('scenes/maps/mill.ts', `// GENERATED by scripts/design-mill.mjs — edit the generator, not this file.\nimport type { Place } from '../chibi-quest.js';\nexport function places(): Place[] {\n  return [\n${places.map(fmt).join('\n')}\n  ];\n}\n`);
const tally = {};
for (const p of places) tally[p.asset] = (tally[p.asset] ?? 0) + 1;
writeFileSync('docs/map-mockups/mill.md', `# Mill map (generated)\n\nGENERATED by scripts/design-mill.mjs.\n\n20 m x 16 m riverside mill inside a one-tile grass ring. River runs north-south on x=5 and ends in a pool at the north (river-bank). The watermill stands at (1.4, -3.4), wheel toward the river. A dirt road runs from the south to the mill door and east to the stone bridge at z=3. Sacks, barrels, hay, a handcart, a wagon and the miller fill the yard; a fenced wheat field lies in the south-west; willows line the river.\n\n| component | count |\n|---|---|\n${Object.entries(tally).sort((a, b) => b[1] - a[1]).map(([k, v]) => `| ${k} | ${v} |`).join('\n')}\n\nTotal: ${places.length}\n\nNotes: the mockup has a windmill-style sail on the mill; the watermill asset has none. The miller asset does not exist; a farmer stands in (see report).\n`);
console.log(places.length, JSON.stringify(tally));
