#!/usr/bin/env node
// Small town map: 13 x 11 cobble tiles (26 m x 22 m). N-S main street at x=0 ending at the
// chapel (north) and the town gate (south); cross street at z=2; two house rows; market corner SE;
// well on the west edge of the street; back-yard gardens and trees behind the rows.
// Cell centers: x = -12..12, z = -10..10 step 2. +X east, -Z north.
import { writeFileSync } from 'node:fs';

const places = [];
const put = (asset, x, z, o = {}) => {
  const p = { asset, at: [x, o.y ?? 0, z] };
  if (o.yaw) p.yaw = o.yaw;
  if (o.scale) p.scale = o.scale;
  places.push(p);
};

// ground: cobble-floor only; grass patches behind the house rows (|x|>=10), cross street z=2 stays cobble
for (let x = -12; x <= 12; x += 2)
  for (let z = -10; z <= 10; z += 2)
    put(Math.abs(x) >= 10 && z !== 2 ? 'grass-ground' : 'cobble-floor', x, z);

// church: big townhouse + bell tower at the north end of the main street
put('townhouse', 0, -8.2, { scale: 1.3 });
put('tower', -3.6, -8.8, { scale: 0.9 });
put('signpost', 1.2, -5.0, { yaw: 10 });
put('bench', -2.4, -4.6); put('bench', 2.4, -4.6);
// west row
put('townhouse', -7.5, -7.5, { yaw: 90 });
put('farmhouse', -7.5, -2.2, { yaw: 90, scale: 0.8 });
put('cottage', -7.5, 7, { yaw: 90 });
// east row
put('farmhouse', 7.5, -5.5, { yaw: 270, scale: 0.8 });
put('cottage', 7.5, -1, { yaw: 270 });
put('townhouse', 7.5, 7.5, { yaw: 270 });
for (const [x, z] of [[-5.2, -7.5], [-5.2, -2.2], [-5.2, 7], [5.2, -5.5], [5.2, -1], [5.2, 7.5]])
  put('wildflowers', x, z, { yaw: x < 0 ? 90 : 270 });
// square at the crossing: well in the middle, stalls around
put('well', 0, 2, { scale: 1.1 });
put('bucket', 0.9, 2.8);
put('shop-stall', -2.4, -0.4); put('shop-stall', 2.4, -0.4);
put('shop-stall', 2.6, 4.6, { yaw: 180 });
put('barrel', -2.6, 4.2); put('crate', -3.2, 3.2, { yaw: 20 }); put('barrel', 4.2, 4.2); put('hay-bale', 4.4, -0.6);
// gate
put('wall-gate', 0, 10.5);
put('hedge', -3.6, 10.4, { scale: 1.2 }); put('hedge', 3.6, 10.4, { scale: 1.2 });
put('signpost', 1.8, 8.6, { yaw: 200 });
put('villager', 0.8, 6, { yaw: 180 }); put('villager', -1.2, -2.8, { yaw: 160 }); put('villager', 3.4, 2.2, { yaw: 90 }); put('villager', -4, 2.6, { yaw: 40 });
// back yards and edge dressing
for (const s of [-1, 1]) {
  for (const z of [-7, -3, 5.5, 9]) put('garden-bed', s * 11.6, z, { yaw: 90 });
  for (const z of [-9.5, -5.5, -1.5, 2.5, 6.5, 10]) put('oak-tree', s * 12.2, z + (s > 0 ? 0.7 : -0.5), { yaw: z * 20, scale: 0.9 + ((z * 7) % 3) / 10 });
  for (const z of [-8, -3, 6, 9]) put('wildflowers', s * 10.6, z + 1.2);
}
for (const x of [-9, -5, 5, 9]) put('bush', x, -10.4, { yaw: x * 9 });
for (const x of [-12, -8, 8, 12]) put('bush', x, 10.6, { yaw: x * 7 });
for (const x of [-9, 9, 11]) put('barrel', x > 0 ? x + 0.3 : x, -10.2, {});
put('crate', -9.5, 10.3); put('barrel', 9.5, 10.3);

const fmt = (p) => { const n = (v) => String(+v.toFixed(2)); return `  { asset: '${p.asset}', at: [${n(p.at[0])}, ${n(p.at[1])}, ${n(p.at[2])}]${p.yaw ? `, yaw: ${p.yaw}` : ''}${p.scale ? `, scale: ${p.scale}` : ''} },`; };
writeFileSync('scenes/maps/town.ts', `// GENERATED by scripts/design-town.mjs — edit the generator, not this file.\nimport type { Place } from '../chibi-quest.js';\nexport function places(): Place[] {\n  return [\n${places.map(fmt).join('\n')}\n  ];\n}\n`);
const tally = {};
for (const p of places) tally[p.asset] = (tally[p.asset] ?? 0) + 1;
writeFileSync('docs/map-mockups/town.md', `# Town map (generated by scripts/design-town.mjs)\n\n13 x 11 cobble tiles (26 m x 22 m). N-S main street at x=0 from the chapel (north focal) to the wall-gate (south); cross street at z=2; two house rows facing the street; market corner SE; well west of the street; back-yard gardens and oaks at the east/west edges.\n\n## Tally (${places.length})\n\n${Object.entries(tally).map(([k, v]) => `- ${k}: ${v}`).join('\n')}\n`);
console.log(places.length, tally);
