#!/usr/bin/env node
// Prison map generator: 14 x 12 m low-walled cell block. Writes scenes/maps/prison.ts
// and docs/map-mockups/prison.md. x -7..7 (W..E), z -6..6 (N..S). North and west walls
// are full height (two courses), south and east walls are low so the camera sees in.
import { writeFileSync } from 'node:fs';

const FY = 0.08; // floor top
const places = [];
const put = (asset, x, z, yaw = 0, y = FY) => places.push({ asset, at: [x, y, z], ...(yaw ? { yaw } : {}) });

// Floor: one family, 7 x 6 tiles of 2 m; a few cracked tiles for age.
for (let i = 0; i < 7; i++)
  for (let j = 0; j < 6; j++) {
    const cracked = (i * 3 + j * 5) % 7 === 0;
    put(cracked ? 'floor-cracked' : 'floor', -6 + i * 2, -5 + j * 2, 0, 0);
  }

// Walls. Centerlines 0.2 m outside the floor. North and west: two courses.
for (let i = 0; i < 7; i++) {
  const x = -6 + i * 2;
  put('wall', x, -6.2, 0, 0); put('wall', x, -6.2, 0, 1.2);
  put('wall', x, 6.2, 180, 0);
}
for (let j = 0; j < 6; j++) {
  const z = -5 + j * 2;
  put('wall', -7.2, z, 90, 0); put('wall', -7.2, z, 90, 1.2);
  if (j !== 4) put('wall', 7.2, z, 270, 0); // j=4 (z=3) is the barred gate
}
// Corners: yaw 0 = SE, 90 = NE, 180 = NW, 270 = SW; origin = vertex - 0.8 * sign.
const corner = (sx, sz, yaw, tall) => {
  const x = sx * 7.2 - sx * 0.8, z = sz * 6.2 - sz * 0.8;
  put('wall-corner', x, z, yaw, 0);
  if (tall) put('wall-corner', x, z, yaw, 1.2);
};
corner(1, 1, 0, false); corner(1, -1, 90, true); corner(-1, -1, 180, true); corner(-1, 1, 270, true);

// Zone 1: cell row on the west side (three cells, z centers -4, 0, 4).
for (const c of [-4, 0, 4]) {
  put('cell-bars', -3.4, c - 1, 90); put('cell-bars', -3.4, c + 1, 90);
  put('bed', -6.3, c, 0);
  put('hay-bale', -4.6, c - 1.3, 20);
  put('bucket', -4.2, c + 1.45);
  put('chains', -6.85, c + 1.3, 90, 0.55);
  put('chains', -6.85, c - 1.3, 90, 0.55);
  put('torch-sconce', -6.8, c + 0.0, 90, 0.35);
}
for (const z of [-2, 2]) for (const x of [-6.0, -4.4]) put('wall', x, z, 0, 0);
put('bone-pile', -5.2, 3.0, 40); put('bone-pile', -6.2, -2.8, 100); put('skeleton', -5.0, -0.8, 60);
put('rope-coil', -5.6, 1.4, 0); put('mug', -4.6, 0.9);

// Zone 2: guard room at the north-east (desk with keys, stair up).
put('desk', 0.8, -5.4, 0); put('chair', 0.8, -4.55, 180);
put('key-iron', 0.5, -5.35, 0, FY + 0.76); put('tankard', 1.15, -5.4, 0, FY + 0.76);
put('lantern', -1.3, -5.5); put('guard', 2.6, -4.4, 200);
put('bookshelf', 3.5, -5.6, 0); put('barrel', 3.8, -5.6 + 0.0 + 0.6); put('crate', -0.3, -5.5, 0);
put('stairs-stone', 5.9, -5.1, 0, FY);
put('torch-sconce', -1.0, -5.8, 0, 0.55); put('torch-sconce', 4.7, -5.8, 0, 0.55);
put('banner', 2.2, -5.9, 0, 0.3);
put('chains', 1.9, -5.9, 0, 0.5); put('chains', -2.6, -5.9, 0, 0.5);
put('bench', -2.6, -5.4, 0);
put('sack', 4.6, -5.5, 20);

// Zone 3: interrogation corner at the south-east.
put('table', 4.2, 3.4, 0); put('chair', 4.2, 4.35, 180); put('chair', 4.2, 2.45, 0);
put('brazier', 6.1, 4.8); put('anvil', 2.8, 5.2, 90);
put('chains', 6.85, 1.2, 270, 0.55); put('chains', 6.85, 5.0, 270, 0.55);
put('chains', 2.3, 5.9, 180, 0.55); put('chains', 5.3, 5.9, 180, 0.55);
put('torch-sconce', 6.8, -0.5, 270, 0.35); put('torch-sconce', 6.8, 5.2, 270, 0.35);
put('torch-sconce', 0.0, 5.8, 180, 0.35); put('torch-sconce', -2.3, 5.8, 180, 0.35);
put('bucket', 3.2, 4.6); put('bone-pile', 5.5, 5.3, 30); put('barrel', 2.8, 4.7 + 0.0, 0);
put('stool', 5.6, 3.9);

// Zone 4: barred gate on the east wall, with a guard post.
put('iron-door', 7.2, 3.0, 270, 0);
put('barrel', 6.2, 0.6); put('barrel', 6.2, 1.5); put('crate', 6.3, -1.4); put('crate', 6.3, -2.4);
put('lantern', 6.2, 2.1, 0);
put('bone-pile', 6.1, -3.5, 10); put('hay-bale', 6.2, -0.5, 90);
put('torch', -2.8, 5.4); put('torch', -2.8, -5.3);
put('candle', 0.2, -5.4, 0, FY + 0.76);
put('bucket', 6.3, 4.4);

const fmt = (p) => `  { asset: '${p.asset}', at: [${p.at.map((v) => +v.toFixed(2)).join(', ')}]${p.yaw ? `, yaw: ${p.yaw}` : ''} },`;
writeFileSync('scenes/maps/prison.ts', `// GENERATED by scripts/design-prison.mjs — edit the generator, not this file.
import type { Place } from '../chibi-quest.js';
export function places(): Place[] {
  return [
${places.map(fmt).join('\n')}
  ];
}
`);
const tally = {};
for (const p of places) tally[p.asset] = (tally[p.asset] ?? 0) + 1;
writeFileSync('docs/map-mockups/prison.md', `# Prison map

14 x 12 m cell block, x -7..7, z -6..6. North and west walls full height, south and east low.

Zones: cell row (west, 3 cells with bars, straw beds, chains), guard room (north-east, desk with keys,
stair up), interrogation corner (south-east, table, chairs, anvil, brazier), barred gate (east wall).

Tally (${places.length} pieces):

${Object.entries(tally).sort().map(([a, n]) => `- ${a}: ${n}`).join('\n')}
`);
console.log(places.length, 'pieces');
