#!/usr/bin/env node
// Castle courtyard map designer. Writes scenes/maps/castle.ts and docs/map-mockups/castle.md.
import { writeFileSync } from 'node:fs';

const places = [];
const put = (asset, x, z, yaw = 0, extra = {}) => {
  const p = { asset, at: [x, extra.y ?? 0, z] };
  if (yaw) p.yaw = yaw;
  if (extra.scale) p.scale = extra.scale;
  places.push(p);
};

// Ground: cobble everywhere, stone-floor forecourt in front of the keep
const forecourt = (x, z) => x >= -4 && x <= 4 && z >= -8 && z <= -2;
for (let c = 0; c < 12; c++) for (let r = 0; r < 12; r++) {
  const x = -11 + c * 2, z = -11 + r * 2;
  put(forecourt(x, z) ? 'stone-floor' : 'cobble-floor', x, z);
}

// Walls: city-wall stairs face the courtyard (local -Z is the stair side)
for (const x of [-8, -4, 0, 4, 8]) {
  put('city-wall', x, -10, 180);
  if (x === 0) put('wall-gate', 0, 10, 0);
  else put('city-wall', x, 10, 0);
}
for (const z of [-8, -4, 0, 4, 8]) {
  put('city-wall', -10, z, 270);
  put('city-wall', 10, z, 90);
}
for (const sx of [-1, 1]) for (const sz of [-1, 1]) put('rampart', sx * 10.1, sz * 10.1);

// Keep forecourt
put('tower', 0, -6.6);
put('rug', 0, -4.2, 90); put('rug', 0, -2.8, 90);
put('banner', -2.6, -4.4); put('banner', 2.6, -4.4);
put('brazier', -1.6, -2.4); put('brazier', 1.6, -2.4);
put('guard', -1.2, -1.2, 0); put('guard', 1.2, -1.2, 0);
put('throne', 5.8, -6.6); put('rug', 5.8, -5.0, 90); put('banner', 7.0, -7.4);

// Well square (NW)
put('well', -5.6, -3.6);
put('bench', -5.6, -1.6, 90); put('lantern', -4.4, -5.6); put('lantern', -6.8, -5.6);
put('bucket', -4.8, -3.0, 40);

// Barracks (east wall)
put('longhouse', 5.6, 0, 270);
put('barrel', 3.2, -4.2); put('crate', 3.2, 4.2, 10);

// Stable corner (SE)
put('fence', 4.5, 4.9); put('fence', 6.3, 4.9); put('fence', 3.6, 6.4, 90); put('fence', 3.6, 8.0, 90);
put('horse', 5.0, 6.4, 270); put('horse', 6.6, 6.4, 90);
put('water-trough', 6.0, 7.7); put('hay-bale', 4.6, 7.7); put('hay-bale', 7.0, 5.6, 90);

// Training yard (SW)
for (const z of [1.2, 3.0, 4.8]) put('hay-bale', -7.0, z, 90);
for (const z of [1.2, 3.0, 4.8]) { put('barrel', -5.6, z); put('crate', -5.6, z, 15, { y: 0.85 }); }
put('spear-warden', -3.6, 3.0, 90); put('knight', -3.6, 4.8, 90);
for (const x of [-7.0, -6.4, -5.8, -5.2]) put('spear', x, -0.2);
put('guard', -2.4, 6.6, 180);
put('barrel', -7.0, 6.8); put('sack', -6.2, 6.9, 20);

// Gate
put('guard', -2.6, 8, 0); put('guard', 2.6, 8, 0);
put('flag', -3.8, 8.4); put('flag', 3.8, 8.4);

// Bushes outside corner towers
for (const sx of [-1, 1]) for (const sz of [-1, 1]) {
  put('bush', sx * 11.7, sz * 11.3); put('bush', sx * 10.4, sz * 11.8);
}

const fmt = (p) => `  { asset: '${p.asset}', at: [${p.at.join(', ')}]${p.yaw ? `, yaw: ${p.yaw}` : ''}${p.scale ? `, scale: ${p.scale}` : ''} },`;
writeFileSync('scenes/maps/castle.ts', `// GENERATED by scripts/design-castle.mjs — edit the generator, not this file.
import type { Place } from '../chibi-quest.js';
export function places(): Place[] {
  return [
${places.map(fmt).join('\n')}
  ];
}
`);
const tally = {};
for (const p of places) tally[p.asset] = (tally[p.asset] ?? 0) + 1;
writeFileSync('docs/map-mockups/castle.md', `# Castle courtyard map (generated)

GENERATED by scripts/design-castle.mjs. 24 m x 24 m ground (12 x 12 cobble-floor), walls on a 20 m square.

Zones: keep forecourt (stone-floor, tower, rug, braziers, banners, guards, throne corner), NW well square, east barracks (longhouse), SE stable pen, SW training yard, 4 m cobble road gate to keep. Four rampart drums at the corners; bushes outside them.

Tally (${places.length} pieces): ${Object.entries(tally).map(([k, v]) => `${k} ${v}`).join(', ')}
`);
console.log(places.length, JSON.stringify(tally));
