import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { dirname, extname, join, relative, resolve } from 'node:path';
import process from 'node:process';

import {
  referenceDocuments,
  rusticMaterials,
  rusticTemplates,
} from '../src/fantasy-kit/index.js';
import { MVP_RENDER_PROFILE, SPRITE_DIRECTIONS } from '../src/render/index.js';
import { CAPABILITY_FACTS, PUBLIC_TOOL_CATALOG } from '../src/tools/index.js';

interface ModuleFact {
  readonly name: string;
  readonly publicEntry: string | null;
  readonly sourceFiles: readonly string[];
  readonly projectDependencies: readonly string[];
  readonly externalDependencies: readonly string[];
}

const PROJECT_ROOT = resolve(import.meta.dirname, '..');
const SOURCE_ROOT = join(PROJECT_ROOT, 'src');
const GENERATED_ROOT = join(PROJECT_ROOT, 'measure/generated');
const SOURCE_EXTENSIONS = new Set(['.ts', '.tsx', '.js', '.mjs']);

async function sourceFiles(directory: string): Promise<string[]> {
  const files: string[] = [];
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) files.push(...(await sourceFiles(path)));
    else if (
      SOURCE_EXTENSIONS.has(extname(entry.name)) &&
      !entry.name.endsWith('.test.ts')
    )
      files.push(path);
  }
  return files.sort();
}

function moduleFromImport(importPath: string): string | undefined {
  if (!importPath.startsWith('.')) return undefined;
  const normalized = importPath.replaceAll('\\', '/');
  const match = normalized.match(
    /(?:^|\/)\.\.\/(contracts|document|geometry|assembly|fantasy-kit|scene|render|export|validation|tools|mcp|inspector)(?:\/|$)/,
  );
  return match?.[1];
}

function packageFromImport(importPath: string): string | undefined {
  if (importPath.startsWith('.') || importPath.startsWith('node:'))
    return undefined;
  const segments = importPath.split('/');
  return importPath.startsWith('@')
    ? segments.slice(0, 2).join('/')
    : segments[0];
}

async function moduleFact(
  name: string,
  directory: string,
): Promise<ModuleFact> {
  const files = await sourceFiles(directory);
  const projectDependencies = new Set<string>();
  const externalDependencies = new Set<string>();
  for (const file of files) {
    const source = await readFile(file, 'utf8');
    for (const match of source.matchAll(
      /(?:from\s+|import\s*\()['"]([^'"]+)['"]/g,
    )) {
      const importPath = match[1];
      if (!importPath) continue;
      const projectDependency = moduleFromImport(importPath);
      if (projectDependency && projectDependency !== name)
        projectDependencies.add(projectDependency);
      const packageName = packageFromImport(importPath);
      if (packageName) externalDependencies.add(packageName);
    }
  }
  const publicEntryPath = join(directory, 'index.ts');
  return {
    name,
    publicEntry: files.includes(publicEntryPath)
      ? relative(PROJECT_ROOT, publicEntryPath)
      : null,
    sourceFiles: files.map((file) => relative(PROJECT_ROOT, file)),
    projectDependencies: [...projectDependencies].sort(),
    externalDependencies: [...externalDependencies].sort(),
  };
}

async function architectureJson(): Promise<string> {
  const directories = (await readdir(SOURCE_ROOT, { withFileTypes: true }))
    .filter((entry) => entry.isDirectory())
    .sort((left, right) => left.name.localeCompare(right.name));
  const modules = await Promise.all(
    directories.map((entry) =>
      moduleFact(entry.name, join(SOURCE_ROOT, entry.name)),
    ),
  );
  return `${JSON.stringify({ formatVersion: 1, sourceRoot: 'src', modules }, null, 2)}\n`;
}

async function routesMarkdown(): Promise<string> {
  const rows = PUBLIC_TOOL_CATALOG.map(
    ({ name }) => `| \`${name}\` | Semantic domain tool |`,
  ).join('\n');
  return [
    '# Generated Domain Tool Routes',
    '',
    '> Generated by `scripts/generate.ts`. Do not edit by hand.',
    '',
    '| Tool | Surface |',
    '|---|---|',
    rows || '| _None registered_ | S1 scaffold only |',
    '',
  ].join('\n');
}

function kitCatalogMarkdown(): string {
  const templateRows = rusticTemplates
    .map(
      (template) =>
        `| \`${template.id}\` | ${template.role} | \`${template.shape.kind}\` | ${template.materialSlots.join(', ')} | ${template.ports.map((port) => port.id).join(', ') || 'none'} |`,
    )
    .join('\n');
  const materialRows = rusticMaterials
    .map(
      (material) =>
        `| \`${material.id}\` | ${material.family} | \`${material.color}\` | ${material.roughness} | ${material.metalness} |`,
    )
    .join('\n');
  const referenceRows = Object.entries(referenceDocuments)
    .map(
      ([name, document]) =>
        `| ${name} | ${document.id} | ${document.assembly.parts.length} | ${document.variants.length} | ${document.poses.length} | ${document.triangleBudget} | ${document.renderProfiles[0]?.requiredFeaturePartIds.join(', ') ?? 'none'} |`,
    )
    .join('\n');
  return [
    '# Generated Rustic Fantasy Kit Catalog',
    '',
    '> Generated by `scripts/generate.ts` from the canonical kit manifests. Do not edit by hand.',
    '',
    `Kit ID: \`${referenceDocuments.adventurer.kitId}\``,
    '',
    '## Templates',
    '',
    '| Template | Semantic role | Shape | Material slots | Ports |',
    '|---|---|---|---|---|',
    templateRows,
    '',
    '## Palette and Material Families',
    '',
    '| Material | Family | Color | Roughness | Metalness |',
    '|---|---|---|---:|---:|',
    materialRows,
    '',
    '## Canonical References',
    '',
    '| Reference | Asset ID | Parts | Variants | Poses | Triangle budget | Required feature parts |',
    '|---|---|---:|---:|---:|---:|---|',
    referenceRows,
    '',
  ].join('\n');
}

function toolCatalogMarkdown(): string {
  const rows = PUBLIC_TOOL_CATALOG.map(
    (tool) =>
      `| \`${tool.name}\` | ${tool.mutates ? 'yes' : 'no'} | ${tool.description} |`,
  ).join('\n');
  return [
    '# Generated Public Tool Catalog',
    '',
    '> Generated by `scripts/generate.ts` from the registered semantic tool catalog. Do not edit by hand.',
    '',
    '| Tool | Mutates revision | Purpose |',
    '|---|---|---|',
    rows,
    '',
    'No public tool exposes arbitrary code execution, shell access, unrestricted filesystem access, network retrieval, UI automation, Blender, or raw mesh mutation.',
    '',
  ].join('\n');
}

function capabilityCatalogMarkdown(): string {
  const rows = CAPABILITY_FACTS.map(
    (fact) =>
      `| \`${fact.id}\` | ${fact.category} | ${fact.status} | ${fact.summary} | ${fact.guidance ?? 'Available through the listed public evidence.'} |`,
  ).join('\n');
  return [
    '# Generated Capability Catalog',
    '',
    '> Generated by `scripts/generate.ts` from executable public tool, kit, render, and output facts. Do not edit by hand.',
    '',
    '| Capability | Category | Status | Current scope | Guidance |',
    '|---|---|---|---|---|',
    rows,
    '',
  ].join('\n');
}

function outputContractsMarkdown(): string {
  return [
    '# Generated Output Contracts',
    '',
    '> Generated by `scripts/generate.ts` from the fixed MVP render profile. Do not edit by hand.',
    '',
    '## Sprite profile',
    '',
    `- Profile: \`${MVP_RENDER_PROFILE.id}\``,
    `- Frame: ${MVP_RENDER_PROFILE.widthPixels}x${MVP_RENDER_PROFILE.heightPixels} transparent PNG`,
    `- Camera: orthographic, ${MVP_RENDER_PROFILE.elevationDegrees} degree elevation`,
    `- Directions: ${MVP_RENDER_PROFILE.directions} in ${SPRITE_DIRECTIONS.join(' -> ')} order`,
    `- Padding: ${MVP_RENDER_PROFILE.paddingPixels}px`,
    `- Minimum feature: ${MVP_RENDER_PROFILE.minimumFeaturePixels}px`,
    `- Required feature evidence: ${MVP_RENDER_PROFILE.requiredFeaturePartIds.join(', ')}`,
    '',
    '## Coordinate system',
    '',
    '- Right-handed world coordinates in meters: +X east/right, +Y up, and +Z north/forward.',
    '- Transforms use position XYZ, quaternion rotation XYZW, and scale XYZ; N/E/S/W labels identify camera positions around the asset.',
    '- Ground contact is normalized to Y=0 in world space and to the declared bottom padding row in sprite space.',
    '',
    '## Mechanical validation',
    '',
    '- Every asset declares a positive integer triangle budget; `validate_asset` rejects evaluated scenes above it.',
    '- Reports occupied bounds, transparent and occupied pixel counts, clipped edges, exact ground-anchor deviation, and representative silhouette-feature width.',
    '- Emits one PNG per direction plus a labeled contact sheet associated with the canonical asset revision.',
    '',
    '## 3D export',
    '',
    '- Emits binary glTF 2.0 in meters as GLB.',
    '- Reload-verifies semantic IDs, material names, world transforms, scales, bounds, and unit scale within explicit tolerances.',
    '- Rejects animations, textures, unsupported materials or shaders, skins, cameras, and lights.',
    '- Rejects output paths outside the active workspace, including symbolic-link traversal, and stores artifacts in collision-safe revision directories.',
    '',
  ].join('\n');
}

async function generatedFiles(): Promise<ReadonlyMap<string, string>> {
  return new Map([
    [join(GENERATED_ROOT, 'architecture.json'), await architectureJson()],
    [join(GENERATED_ROOT, 'routes.md'), await routesMarkdown()],
    [join(GENERATED_ROOT, 'kit-catalog.md'), kitCatalogMarkdown()],
    [join(GENERATED_ROOT, 'tool-catalog.md'), toolCatalogMarkdown()],
    [
      join(GENERATED_ROOT, 'capability-catalog.md'),
      capabilityCatalogMarkdown(),
    ],
    [join(GENERATED_ROOT, 'output-contracts.md'), outputContractsMarkdown()],
  ]);
}

async function main(): Promise<void> {
  const check = process.argv.includes('--check');
  const outputs = await generatedFiles();
  const stale: string[] = [];
  for (const [path, content] of outputs) {
    if (check) {
      let current = '';
      try {
        current = await readFile(path, 'utf8');
      } catch {
        /* Missing generated files are stale. */
      }
      if (current !== content) stale.push(relative(PROJECT_ROOT, path));
    } else {
      await mkdir(dirname(path), { recursive: true });
      await writeFile(path, content, 'utf8');
    }
  }
  if (stale.length > 0) {
    console.error(`Generated facts are stale: ${stale.join(', ')}`);
    process.exitCode = 1;
  } else {
    console.log(
      check
        ? 'Generated facts are current.'
        : 'Generated architecture, route, kit, tool, capability, and output facts.',
    );
  }
}

await main();
