import type { ReferenceFiveClipBatchAuthoringRequest } from './authoring.js';

type JointValues = Readonly<{
  shoulderLeft: number;
  shoulderRight: number;
  elbowLeft: number;
  elbowRight: number;
  hipLeft: number;
  hipRight: number;
  kneeLeft: number;
  kneeRight: number;
}>;

type RootMotion = Readonly<{
  offset: [number, number, number];
  yawDegrees: number;
}>;

const pose = (
  id: string,
  values: JointValues,
  rootMotion: RootMotion = { offset: [0, 0, 0], yawDegrees: 0 },
) => ({
  id,
  channels: [
    { jointId: 'shoulder.left', valueDegrees: values.shoulderLeft },
    { jointId: 'shoulder.right', valueDegrees: values.shoulderRight },
    { jointId: 'elbow.left', valueDegrees: values.elbowLeft },
    { jointId: 'elbow.right', valueDegrees: values.elbowRight },
    { jointId: 'hip.left', valueDegrees: values.hipLeft },
    { jointId: 'hip.right', valueDegrees: values.hipRight },
    { jointId: 'knee.left', valueDegrees: values.kneeLeft },
    { jointId: 'knee.right', valueDegrees: values.kneeRight },
  ],
  rootMotion,
});

const keyframes = (
  action: string,
  phases: readonly string[],
  times: readonly number[],
  poseIds: readonly string[],
) =>
  phases.map((phase, index) => ({
    id: `${action}.${index}`,
    phase,
    timeMs: times[index]!,
    poseId: poseIds[index]!,
  }));

const neutral = {
  shoulderLeft: 6,
  shoulderRight: -6,
  elbowLeft: 8,
  elbowRight: -8,
  hipLeft: 0,
  hipRight: 0,
  kneeLeft: 0,
  kneeRight: 0,
};

/**
 * Canonical production-reference request for the public five-clip profile.
 *
 * The reference adventurer exposes one rigid Z-axis hinge per shoulder, elbow,
 * hip, and knee. These poses deliberately use every supported limb chain plus
 * bounded torso-root translation/yaw so temporal captures read as full-body
 * actions instead of arm-only substitutions.
 */
export const REFERENCE_FULL_BODY_FIVE_CLIP_ANIMATION_REQUEST = {
  contractId: 'forge-reference-five-clip-authoring/v1',
  rig: {
    id: 'rig.adventurer.reference-five.full-body',
    rootJointId: 'root',
    joints: [
      {
        id: 'root',
        partId: 'torso',
        axis: 'y',
        minimumDegrees: 0,
        maximumDegrees: 0,
        restDegrees: 0,
      },
      {
        id: 'shoulder.left',
        parentJointId: 'root',
        partId: 'upper-arm.left',
        axis: 'z',
        minimumDegrees: -85,
        maximumDegrees: 85,
        restDegrees: 0,
        mirrorJointId: 'shoulder.right',
      },
      {
        id: 'shoulder.right',
        parentJointId: 'root',
        partId: 'upper-arm.right',
        axis: 'z',
        minimumDegrees: -85,
        maximumDegrees: 85,
        restDegrees: 0,
        mirrorJointId: 'shoulder.left',
      },
      {
        id: 'elbow.left',
        parentJointId: 'shoulder.left',
        partId: 'forearm.left',
        axis: 'z',
        minimumDegrees: -90,
        maximumDegrees: 90,
        restDegrees: 0,
        mirrorJointId: 'elbow.right',
      },
      {
        id: 'elbow.right',
        parentJointId: 'shoulder.right',
        partId: 'forearm.right',
        axis: 'z',
        minimumDegrees: -90,
        maximumDegrees: 90,
        restDegrees: 0,
        mirrorJointId: 'elbow.left',
      },
      {
        id: 'hip.left',
        parentJointId: 'root',
        partId: 'thigh.left',
        axis: 'z',
        minimumDegrees: -55,
        maximumDegrees: 55,
        restDegrees: 0,
        mirrorJointId: 'hip.right',
      },
      {
        id: 'hip.right',
        parentJointId: 'root',
        partId: 'thigh.right',
        axis: 'z',
        minimumDegrees: -55,
        maximumDegrees: 55,
        restDegrees: 0,
        mirrorJointId: 'hip.left',
      },
      {
        id: 'knee.left',
        parentJointId: 'hip.left',
        partId: 'shin.left',
        axis: 'z',
        minimumDegrees: -75,
        maximumDegrees: 75,
        restDegrees: 0,
        mirrorJointId: 'knee.right',
      },
      {
        id: 'knee.right',
        parentJointId: 'hip.right',
        partId: 'shin.right',
        axis: 'z',
        minimumDegrees: -75,
        maximumDegrees: 75,
        restDegrees: 0,
        mirrorJointId: 'knee.left',
      },
    ],
  },
  poses: [
    pose('neutral', neutral),
    pose(
      'idle.inhale',
      {
        ...neutral,
        shoulderLeft: 10,
        shoulderRight: -10,
        elbowLeft: 11,
        elbowRight: -11,
        hipLeft: -2,
        hipRight: 2,
        kneeLeft: 2,
        kneeRight: -2,
      },
      { offset: [0, 0.03, 0], yawDegrees: 0 },
    ),
    pose(
      'idle.shift',
      {
        ...neutral,
        shoulderLeft: 4,
        shoulderRight: -9,
        elbowLeft: 7,
        elbowRight: -12,
        hipLeft: 5,
        hipRight: -4,
        kneeLeft: 4,
        kneeRight: -3,
      },
      { offset: [0.025, 0.01, 0], yawDegrees: -2 },
    ),
    pose(
      'idle.exhale',
      {
        ...neutral,
        shoulderLeft: 2,
        shoulderRight: -2,
        elbowLeft: 5,
        elbowRight: -5,
        hipLeft: 1,
        hipRight: -1,
      },
      { offset: [-0.01, -0.015, 0], yawDegrees: 1 },
    ),
    pose(
      'wf.contact-left',
      {
        ...neutral,
        shoulderLeft: -28,
        shoulderRight: 28,
        elbowLeft: 14,
        elbowRight: -14,
        hipLeft: -36,
        hipRight: 36,
        kneeLeft: 5,
        kneeRight: -5,
      },
      { offset: [-0.02, 0, 0], yawDegrees: -2 },
    ),
    pose(
      'wf.down-left',
      {
        ...neutral,
        shoulderLeft: -20,
        shoulderRight: 20,
        elbowLeft: 18,
        elbowRight: -18,
        hipLeft: -28,
        hipRight: 24,
        kneeLeft: 20,
        kneeRight: -44,
      },
      { offset: [-0.018, -0.055, 0], yawDegrees: -1 },
    ),
    pose(
      'wf.passing-left',
      {
        ...neutral,
        shoulderLeft: -8,
        shoulderRight: 8,
        elbowLeft: 12,
        elbowRight: -12,
        hipLeft: -7,
        hipRight: 13,
        kneeLeft: 44,
        kneeRight: -18,
      },
      { offset: [-0.008, 0.018, 0], yawDegrees: 0 },
    ),
    pose(
      'wf.contact-right',
      {
        ...neutral,
        shoulderLeft: 28,
        shoulderRight: -28,
        elbowLeft: 14,
        elbowRight: -14,
        hipLeft: 36,
        hipRight: -36,
        kneeLeft: 5,
        kneeRight: -5,
      },
      { offset: [0.02, 0, 0], yawDegrees: 2 },
    ),
    pose(
      'wf.down-right',
      {
        ...neutral,
        shoulderLeft: 20,
        shoulderRight: -20,
        elbowLeft: 18,
        elbowRight: -18,
        hipLeft: 24,
        hipRight: -28,
        kneeLeft: 44,
        kneeRight: -20,
      },
      { offset: [0.018, -0.055, 0], yawDegrees: 1 },
    ),
    pose(
      'wf.passing-right',
      {
        ...neutral,
        shoulderLeft: 8,
        shoulderRight: -8,
        elbowLeft: 12,
        elbowRight: -12,
        hipLeft: 13,
        hipRight: -7,
        kneeLeft: 18,
        kneeRight: -44,
      },
      { offset: [0.008, 0.018, 0], yawDegrees: 0 },
    ),
    pose(
      'wr.contact-left',
      {
        ...neutral,
        shoulderLeft: -8,
        shoulderRight: 6,
        elbowLeft: 14,
        elbowRight: -12,
        hipLeft: -52,
        hipRight: 38,
        kneeLeft: 8,
        kneeRight: -14,
      },
      { offset: [0, 0, -0.015], yawDegrees: 10 },
    ),
    pose(
      'wr.down-left',
      {
        ...neutral,
        shoulderLeft: -4,
        shoulderRight: 3,
        elbowLeft: 16,
        elbowRight: -13,
        hipLeft: -42,
        hipRight: 30,
        kneeLeft: 32,
        kneeRight: -62,
      },
      { offset: [0, -0.06, -0.01], yawDegrees: 10 },
    ),
    pose(
      'wr.passing-left',
      {
        ...neutral,
        shoulderLeft: 2,
        shoulderRight: -2,
        elbowLeft: 13,
        elbowRight: -11,
        hipLeft: -16,
        hipRight: 22,
        kneeLeft: 64,
        kneeRight: -24,
      },
      { offset: [0, 0.02, -0.005], yawDegrees: 10 },
    ),
    pose(
      'wr.contact-right',
      {
        ...neutral,
        shoulderLeft: 6,
        shoulderRight: -8,
        elbowLeft: 12,
        elbowRight: -14,
        hipLeft: 38,
        hipRight: -52,
        kneeLeft: 14,
        kneeRight: -8,
      },
      { offset: [0, 0, 0.015], yawDegrees: 10 },
    ),
    pose(
      'wr.down-right',
      {
        ...neutral,
        shoulderLeft: 3,
        shoulderRight: -4,
        elbowLeft: 13,
        elbowRight: -16,
        hipLeft: 30,
        hipRight: -42,
        kneeLeft: 62,
        kneeRight: -32,
      },
      { offset: [0, -0.06, 0.01], yawDegrees: 10 },
    ),
    pose(
      'wr.passing-right',
      {
        ...neutral,
        shoulderLeft: -2,
        shoulderRight: 2,
        elbowLeft: 11,
        elbowRight: -13,
        hipLeft: 22,
        hipRight: -16,
        kneeLeft: 24,
        kneeRight: -64,
      },
      { offset: [0, 0.02, 0.005], yawDegrees: 10 },
    ),
    pose(
      'attack.anticipation',
      {
        ...neutral,
        shoulderLeft: 13,
        shoulderRight: -24,
        elbowLeft: 19,
        elbowRight: -54,
        hipLeft: -13,
        hipRight: 19,
        kneeLeft: 19,
        kneeRight: -11,
      },
      { offset: [-0.06, -0.035, -0.03], yawDegrees: -6 },
    ),
    pose(
      'attack.windup',
      {
        ...neutral,
        shoulderLeft: 20,
        shoulderRight: -74,
        elbowLeft: 25,
        elbowRight: -72,
        hipLeft: -21,
        hipRight: 25,
        kneeLeft: 29,
        kneeRight: -17,
      },
      { offset: [-0.1, -0.045, -0.055], yawDegrees: -11 },
    ),
    pose(
      'attack.contact',
      {
        ...neutral,
        shoulderLeft: -13,
        shoulderRight: 60,
        elbowLeft: 11,
        elbowRight: 21,
        hipLeft: 19,
        hipRight: -25,
        kneeLeft: 13,
        kneeRight: -23,
      },
      { offset: [0.125, 0.015, 0.055], yawDegrees: 11 },
    ),
    pose(
      'attack.follow-through',
      {
        ...neutral,
        shoulderLeft: -21,
        shoulderRight: 78,
        elbowLeft: 9,
        elbowRight: 54,
        hipLeft: 27,
        hipRight: -29,
        kneeLeft: 11,
        kneeRight: -34,
      },
      { offset: [0.165, -0.015, 0.075], yawDegrees: 15 },
    ),
    pose(
      'attack.recovery',
      {
        ...neutral,
        shoulderLeft: 9,
        shoulderRight: -13,
        elbowLeft: 13,
        elbowRight: -21,
        hipLeft: 6,
        hipRight: -8,
        kneeLeft: 5,
        kneeRight: -6,
      },
      { offset: [0.02, 0, 0.01], yawDegrees: 2 },
    ),
    pose(
      'damage.impact',
      {
        ...neutral,
        shoulderLeft: -35,
        shoulderRight: 12,
        elbowLeft: 48,
        elbowRight: -18,
        hipLeft: -20,
        hipRight: 8,
        kneeLeft: 34,
        kneeRight: -10,
      },
      { offset: [-0.08, 0.025, -0.015], yawDegrees: -2 },
    ),
    pose(
      'damage.recoil',
      {
        ...neutral,
        shoulderLeft: -65,
        shoulderRight: 28,
        elbowLeft: 75,
        elbowRight: -38,
        hipLeft: -42,
        hipRight: 18,
        kneeLeft: 58,
        kneeRight: -22,
      },
      { offset: [-0.24, 0.13, -0.02], yawDegrees: -2 },
    ),
    pose(
      'damage.recovery',
      {
        ...neutral,
        shoulderLeft: 14,
        shoulderRight: -8,
        elbowLeft: 20,
        elbowRight: -12,
        hipLeft: 8,
        hipRight: -4,
        kneeLeft: 12,
        kneeRight: -7,
      },
      { offset: [-0.045, 0.02, -0.01], yawDegrees: -2 },
    ),
  ],
  seed: 722,
  clips: [
    {
      action: 'idle',
      durationMs: 800,
      interpolation: 'linear',
      rootAnchorPolicy: 'locked',
      loop: { mode: 'loop', startMs: 0, endMs: 800 },
      capture: { directions: ['S'], framesPerSecond: 5 },
      keyframes: keyframes(
        'idle',
        ['neutral', 'inhale', 'shift', 'exhale', 'loop_seam'],
        [0, 200, 400, 600, 800],
        ['neutral', 'idle.inhale', 'idle.shift', 'idle.exhale', 'neutral'],
      ),
    },
    {
      action: 'walk_forward',
      durationMs: 750,
      interpolation: 'linear',
      rootAnchorPolicy: 'in_place',
      loop: { mode: 'loop', startMs: 0, endMs: 750 },
      capture: { directions: ['S'], framesPerSecond: 8 },
      keyframes: keyframes(
        'walk_forward',
        [
          'contact_left',
          'down_left',
          'passing_left',
          'contact_right',
          'down_right',
          'passing_right',
          'loop_seam',
        ],
        [0, 125, 250, 375, 500, 625, 750],
        [
          'wf.contact-left',
          'wf.down-left',
          'wf.passing-left',
          'wf.contact-right',
          'wf.down-right',
          'wf.passing-right',
          'wf.contact-left',
        ],
      ),
    },
    {
      action: 'walk_right',
      durationMs: 750,
      interpolation: 'linear',
      rootAnchorPolicy: 'in_place',
      loop: { mode: 'loop', startMs: 0, endMs: 750 },
      capture: { directions: ['E'], framesPerSecond: 8 },
      keyframes: keyframes(
        'walk_right',
        [
          'contact_left',
          'down_left',
          'passing_left',
          'contact_right',
          'down_right',
          'passing_right',
          'loop_seam',
        ],
        [0, 125, 250, 375, 500, 625, 750],
        [
          'wr.contact-left',
          'wr.down-left',
          'wr.passing-left',
          'wr.contact-right',
          'wr.down-right',
          'wr.passing-right',
          'wr.contact-left',
        ],
      ),
    },
    {
      action: 'attack',
      durationMs: 750,
      interpolation: 'linear',
      rootAnchorPolicy: 'bounded_motion',
      loop: { mode: 'once' },
      capture: { directions: ['S'], framesPerSecond: 8 },
      keyframes: keyframes(
        'attack',
        [
          'neutral',
          'anticipation',
          'windup',
          'contact',
          'follow_through',
          'recovery',
          'terminal_hold',
        ],
        [0, 125, 250, 375, 500, 625, 750],
        [
          'neutral',
          'attack.anticipation',
          'attack.windup',
          'attack.contact',
          'attack.follow-through',
          'attack.recovery',
          'attack.recovery',
        ],
      ),
    },
    {
      action: 'receive_damage',
      durationMs: 500,
      interpolation: 'linear',
      rootAnchorPolicy: 'bounded_motion',
      loop: { mode: 'once' },
      capture: { directions: ['S'], framesPerSecond: 8 },
      keyframes: keyframes(
        'receive_damage',
        ['neutral', 'impact', 'recoil', 'recovery', 'terminal_hold'],
        [0, 125, 250, 375, 500],
        [
          'neutral',
          'damage.impact',
          'damage.recoil',
          'damage.recovery',
          'damage.recovery',
        ],
      ),
    },
  ],
} as const satisfies ReferenceFiveClipBatchAuthoringRequest;
